ヘルスチェックエンドポイントハンドラを追加
nablarch/nablarch-document pull request #312
Opened 2020-08-26 01:07 UTC by kiyohome

https://github.com/nablarch/nablarch-fw-web/pull/80
上記対応をドキュメントに反映しました。

2020-08-26 07:30 UTC, backpaper0 requested changes

2020-08-26 07:30 UTC, backpaper0 commented on application_framework/application_framework/handlers/web/health_check_endpoint_handler.rst
> +以下にヘルスチェックの成功時と失敗時のレスポンスを示す。
ステータスコードにも触れておいた方が良いと思いました。
ロードバランサーのヘルスチェックはステータスコードのみで判断することが多いみたいなので、ステータスコードは関心ごとだと思います。

2020-08-26 08:33 UTC, kiyohome commented on application_framework/application_framework/handlers/web/health_check_endpoint_handler.rst
> +以下にヘルスチェックの成功時と失敗時のレスポンスを示す。
ステータスコードを明示しました！　https://github.com/nablarch/nablarch-document/pull/312/commits/5df8a223d482ae49c3b153411cce2b621d0b557a

2020-08-27 05:24 UTC, backpaper0 approved these changes

2020-08-28 04:32 UTC, mseko commented
LGTM!

2020-08-28 04:32 UTC, merged