Micrometerアダプタの機能拡充分を英訳
nablarch/nablarch-document pull request #342
Opened 2021-02-18 04:29 UTC by opengl-8080

以前対応した、Micrometerアダプタの機能拡充対応分のドキュメントの英訳対応です。

- [当該プルリクエスト](https://github.com/nablarch/nablarch-document/pull/337)

一部、既存（日本語）のドキュメントにも不備があったので、あわせて対応しています。

- [最新のコードで出力したスタックトレースと行番号が異なっていたので修正](https://github.com/nablarch/nablarch-document/commit/4a65feb920be4fffe338f712f020b68f38b0d5ea)
- [誤記修正](https://github.com/nablarch/nablarch-document/commit/0637544f3da9d81a8025e141c7ea411e7df6d452)

2021-02-19 06:12 UTC, kumagoro1202 requested changes

2021-02-19 06:12 UTC, kumagoro1202 commented on en/application_framework/application_framework/libraries/log.rst
> +That's all, the ``LogPublisher`` sends the output log information to the ``CustomLogListener``.
That's allはなんとなくニュアンスが違う気がします。話の結びとかこれで全部ですみたいな感じ。
The ``LogPublisher`` sends the output log information to the ``CustomLogListener`` by undergoing the steps.
とかかなと思います。

2021-02-25 00:08 UTC, opengl-8080 commented on en/application_framework/application_framework/libraries/log.rst
> +That's all, the ``LogPublisher`` sends the output log information to the ``CustomLogListener``.
https://github.com/nablarch/nablarch-document/pull/342/commits/eb3ab50e8e030f4d4d430fab14ec4ca0097a7b48

micrometer-adaptor の方で使っていた `Now S can V ...` の表現で修正してみました。

2021-02-25 00:12 UTC, kumagoro1202 approved these changes

2021-02-25 00:13 UTC, merged