[WIP]テスティングフレームワークフレームワークについて
nablarch/nablarch-document pull request #344
Opened 2021-02-22 08:15 UTC by mseko

## 背景
- https://nablarch.atlassian.net/jira/software/c/projects/NAB/issues/NAB-399

## 実施したこと
- NAB-399の対応
- 参照先ドキュメントと見出しが異なっていて対応が読み取りづらい部分について、見出しの文言を直した。

2021-03-01 04:37 UTC, kumagoro1202 requested changes

2021-03-01 04:37 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/02_RequestUnitTest/delayed_receive.rst
> +このため、レスポンスメッセージ(「MESSAGE=expectedMessages」)の記述は不要である。
期待値の確認が一切不要に見えるので「期待するデータベースの状態のみ確認を行う。」は追記して欲しいです。

2021-03-01 05:19 UTC, mseko commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/02_RequestUnitTest/delayed_receive.rst
> +このため、レスポンスメッセージ(「MESSAGE=expectedMessages」)の記述は不要である。
追記しました。

2021-03-02 02:58 UTC, kumagoro1202 requested changes

2021-03-02 02:58 UTC, kumagoro1202 commented on en/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/02_RequestUnitTest/http_send_sync.rst
> + It throws  out a different class than \ :ref:`message_sendSyncMessage_test`\.
throwsの後のスペースが2個

2021-03-02 04:12 UTC, mseko commented on en/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/02_RequestUnitTest/http_send_sync.rst
> + It throws  out a different class than \ :ref:`message_sendSyncMessage_test`\.
1個に修正しました。

2021-03-02 04:13 UTC, merged