動的属性の利用を追記
nablarch/nablarch-document pull request #351
Opened 2021-03-04 11:03 UTC by kumagoro1202

https://nablarch.atlassian.net/browse/NAB-402

2021-03-08 07:42 UTC, kiyohome requested changes

2021-03-08 07:42 UTC, kiyohome commented on ja/application_framework/application_framework/libraries/tag.rst
> +* 一部のタグで動的属性をサポートする。
制約でないので、この記載は不要だと思います。

2021-03-08 07:42 UTC, kiyohome commented on ja/application_framework/application_framework/libraries/tag.rst
> +タグごとの動的属性の利用可否は :ref:`tag_reference` を参照。
方針として、HTML出力するカスタムタグは動的属性に対応している、ってこと書いておけば、詳細見なくてよくないですか？

2021-03-08 07:42 UTC, kiyohome commented on ja/application_framework/application_framework/libraries/tag.rst
> +論理属性を出力する
これ、「任意の属性を指定する」の入れ子だよね。
それだれば「Boolean属性の扱い」とかの方がよくないですか？

2021-03-08 07:42 UTC, kiyohome commented on ja/application_framework/application_framework/libraries/tag.rst
> +タグライブラリ記述子に宣言されていない動的属性を論理属性として出力することができる。
この文は必要ですか？

2021-03-08 07:42 UTC, kiyohome commented on ja/application_framework/application_framework/libraries/tag.rst
> +論理属性に指定した属性は、値に `true` を指定した場合は属性名と同じ値が属性の値として出力される。
動的属性のBoolean属性についても、既存カスタムタグのBoolean属性と同じように、JSPでJavaのtrue/falseを指定して出力有無を操作できる、という説明をしたいのでは？

2021-03-08 07:42 UTC, kiyohome commented on ja/application_framework/application_framework/libraries/tag.rst
> +デフォルトでは以下の属性が論理属性として定義されている。
定義されている→扱う、とかでは？

2021-03-08 07:42 UTC, kiyohome commented on ja/application_framework/application_framework/libraries/tag.rst
> +上記に含まれない属性を論理属性として扱いたい場合は論理属性のリストを ``CustomTagConfig`` の :java:extdoc:`dynamicBooleanAttributesプロパティ<nablarch.common.web.tag.CustomTagConfig.setDynamicBooleanAttributes(java.util.List)>` に設定する。
変更できる、って伝えた方が分かり易くないですか？

2021-03-08 08:04 UTC, kumagoro1202 commented on ja/application_framework/application_framework/libraries/tag.rst
> +* 一部のタグで動的属性をサポートする。
削除しました。
https://github.com/nablarch/nablarch-document/pull/351/commits/da61fff0c811cf4676342ba52d5687fbab68ba95#diff-84f365256a89b3a1ee8b7f2fd59294136cfe5fac8bb32c6a8aa1d61948a7ad71L24

2021-03-08 08:07 UTC, kumagoro1202 commented on ja/application_framework/application_framework/libraries/tag.rst
> +タグごとの動的属性の利用可否は :ref:`tag_reference` を参照。
確かにそうですね。
https://github.com/nablarch/nablarch-document/pull/351/commits/da61fff0c811cf4676342ba52d5687fbab68ba95#diff-84f365256a89b3a1ee8b7f2fd59294136cfe5fac8bb32c6a8aa1d61948a7ad71L2586
https://github.com/nablarch/nablarch-document/pull/351/commits/f53501b744fc7035aeae9f2eedcf0a953e8a58d8#diff-84f365256a89b3a1ee8b7f2fd59294136cfe5fac8bb32c6a8aa1d61948a7ad71R2585

あわせてHTMLチェックで静的チェックするよう注意喚起しました。

2021-03-08 08:08 UTC, kumagoro1202 commented on ja/application_framework/application_framework/libraries/tag.rst
> +タグライブラリ記述子に宣言されていない動的属性を論理属性として出力することができる。
入れ子になっているので冗長ですね。削除しました。
https://github.com/nablarch/nablarch-document/pull/351/commits/da61fff0c811cf4676342ba52d5687fbab68ba95#diff-84f365256a89b3a1ee8b7f2fd59294136cfe5fac8bb32c6a8aa1d61948a7ad71L2590

2021-03-08 08:09 UTC, kumagoro1202 commented on ja/application_framework/application_framework/libraries/tag.rst
> +論理属性に指定した属性は、値に `true` を指定した場合は属性名と同じ値が属性の値として出力される。
そうです。見直しました。
https://github.com/nablarch/nablarch-document/pull/351/commits/da61fff0c811cf4676342ba52d5687fbab68ba95#diff-84f365256a89b3a1ee8b7f2fd59294136cfe5fac8bb32c6a8aa1d61948a7ad71L2591-R2589

2021-03-08 08:09 UTC, kumagoro1202 commented on ja/application_framework/application_framework/libraries/tag.rst
> +デフォルトでは以下の属性が論理属性として定義されている。
ソース内部なので扱うの方がいいですね。
https://github.com/nablarch/nablarch-document/pull/351/commits/da61fff0c811cf4676342ba52d5687fbab68ba95#diff-84f365256a89b3a1ee8b7f2fd59294136cfe5fac8bb32c6a8aa1d61948a7ad71R2590

2021-03-08 08:09 UTC, kumagoro1202 commented on ja/application_framework/application_framework/libraries/tag.rst
> +上記に含まれない属性を論理属性として扱いたい場合は論理属性のリストを ``CustomTagConfig`` の :java:extdoc:`dynamicBooleanAttributesプロパティ<nablarch.common.web.tag.CustomTagConfig.setDynamicBooleanAttributes(java.util.List)>` に設定する。
修正しました。
https://github.com/nablarch/nablarch-document/pull/351/commits/da61fff0c811cf4676342ba52d5687fbab68ba95#diff-84f365256a89b3a1ee8b7f2fd59294136cfe5fac8bb32c6a8aa1d61948a7ad71L2637-R2635

2021-03-09 06:47 UTC, mseko commented on en/application_framework/application_framework/libraries/tag.rst
>   Custom tags are not compatible with HTML5.
`Custom tags are not compatible with HTML5.` は不要だと思います。

2021-03-12 04:51 UTC, mseko commented on en/application_framework/application_framework/libraries/tag.rst
> +This allows custom tags to output any attributes, including those added in HTML5.
「This allows ～」とありますが、「allow」は「許す」「許可する」というニュアンスだと思います。
原文で言いたいのは「可能である」だと思いますので「This can ～」の方が良いのでは無いでしょうか。

2021-03-12 04:54 UTC, mseko commented on en/application_framework/application_framework/libraries/tag.rst
> +See :ref:`tag_reference` for availability of dynamic attributes per tag.
日本語版コンテンツにはこの箇所にtag_referenceへの参照がないです。
日本語版コンテンツと英語版コンテンツ、どちらかのミスではないでしょうか。

2021-03-12 05:08 UTC, mseko commented on en/application_framework/application_framework/libraries/tag.rst
> +Handling of Boolean attributes
ここでは扱うを「handle」としていますが、本文中では「treat」としています。どちらかに合わせるべきだと思います。おそらくここはtreatだと思います。

2021-03-12 05:15 UTC, mseko commented on en/application_framework/application_framework/libraries/tag.rst
> +Attributes that are treated as Boolean attributes can be changed.
「change」は「別のものに変える」というニュアンスです。
原文で言いたいのは「追加/変更できる」というニュアンスだと思いますので、「modify」の方が良いのでは無いでしょうか。

2021-03-12 05:20 UTC, mseko commented on en/application_framework/application_framework/libraries/tag.rst
> +To do so, set the list of Boolean attributes to :java:extdoc:`dynamicBooleanAttributes property <nablarch.common.web.tag.CustomTagConfig.se tDynamicBooleanAttributes(java.util.List)>` of ``CustomTagC
「set the ～」の部分ですが「configure the ～」にしてください。
厳密なルールではないのですが、Nablarch解説書では設定ファイルに設定する場合、configureで表現出来る場合はconfigureを使用しています。

2021-03-12 05:25 UTC, mseko commented on en/application_framework/application_framework/libraries/tag.rst
> +  * :ref:`tag-search_tag`
日本語版コンテンツ及び、日英のtag_reference.rstの方ではリンクの後ろに補足説明(search等)があります。
補足有無を統一した方が良いと思います。

2021-03-15 01:28 UTC, kumagoro1202 commented on en/application_framework/application_framework/libraries/tag.rst
>   Custom tags are not compatible with HTML5.
日本語版に合わせて修正しました。

2021-03-15 01:29 UTC, kumagoro1202 commented on en/application_framework/application_framework/libraries/tag.rst
> +This allows custom tags to output any attributes, including those added in HTML5.
make it possibleに変えました。

2021-03-15 01:29 UTC, kumagoro1202 commented on en/application_framework/application_framework/libraries/tag.rst
> +See :ref:`tag_reference` for availability of dynamic attributes per tag.
英語版が日本語版に追随できていないので修正しました。

2021-03-15 01:30 UTC, kumagoro1202 commented on en/application_framework/application_framework/libraries/tag.rst
> +Handling of Boolean attributes
見出しはhandleでいきたいので、本文をtreatではなくregard as（みなす）にしました。

2021-03-15 01:33 UTC, kumagoro1202 commented on en/application_framework/application_framework/libraries/tag.rst
> +Attributes that are treated as Boolean attributes can be changed.
modifyにしました。

2021-03-15 01:34 UTC, kumagoro1202 commented on en/application_framework/application_framework/libraries/tag.rst
> +To do so, set the list of Boolean attributes to :java:extdoc:`dynamicBooleanAttributes property <nablarch.common.web.tag.CustomTagConfig.se tDynamicBooleanAttributes(java.util.List)>` of ``CustomTagC
configureにしました。

2021-03-15 01:39 UTC, kumagoro1202 commented on en/application_framework/application_framework/libraries/tag.rst
> +  * :ref:`tag-search_tag`
英語にした場合タグの名前そのままになるので消していましたが、タグリファレンスの記載に合わせて()を追加しました。

2021-03-15 07:14 UTC, mseko commented
LGTM!

2021-03-15 07:15 UTC, merged