AWS X-Ray SDKを組み込むガイド追記
nablarch/nablarch-document pull request #353
Opened 2021-03-09 11:41 UTC by kumagoro1202

2021-03-10 02:59 UTC, backpaper0 requested changes

2021-03-10 02:59 UTC, backpaper0 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +  しかし、2021年3月現在production-readyとなっているが、正式リリースはされておらずNablarchでも動作確認は行っていない。
production-readyだけど正式リリースされていないことを表すには https://aws.amazon.com/jp/otel/ へリンクしている方が良いと思いました。

ttps://aws.amazon.com/jp/otel/ だと大きく`(Preview)`と書かれているため。

2021-03-10 02:59 UTC, backpaper0 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +      <param-value>gateway</param-value>
もっと読者にとってわかりやすい名前にしましょう。

2021-03-10 02:59 UTC, backpaper0 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +Jerseyは、デフォルトでは ``java.net.HttpURLConnection`` をトランスポート層に利用する。
唐突な印象を受けました。

- JerseyでApache HttpComponentsを使うためには設定が必要である
- デフォルトではHttpURLConnectionを使う

という順の方が自然です。

2021-03-10 02:59 UTC, backpaper0 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +下記では ``HttpClientBuilder`` をAWS SDKの ``com.amazonaws.xray.proxies.apache.http.HttpClientBuilder`` に差し替えている。
差し替っとらんのでは？？？

> import org.apache.http.impl.client.HttpClientBuilder;

2021-03-10 02:59 UTC, backpaper0 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +  package com.example.system.httpclient;
単なる例だし、`com.example`ぐらいのパッケージで良いと思いました。

解説書内の他のコードと合わせているなら、このコメントは取り下げます。

2021-03-10 02:59 UTC, backpaper0 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +システムリポジトリに登録したHTTPクライアントを使用するクラスの例を以下に示す。
見せたいのは「`SystemRepository`からJAX-RSクライアントを取り出して使う」ですよね。
見せたいところ以外のコードが多いので、もっと削った方がいいです。

あと普通に`SystemRepository.get()`で取得する例も書いておいても良いんじゃないでしょうか。

2021-03-10 06:20 UTC, kumagoro1202 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +  しかし、2021年3月現在production-readyとなっているが、正式リリースはされておらずNablarchでも動作確認は行っていない。
確かにそうですね。リンク先を変更しました。
https://github.com/nablarch/nablarch-document/pull/353/commits/602cca6bf36044947cc5c7caf46280bb85dab8fd

2021-03-10 06:20 UTC, kumagoro1202 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +      <param-value>gateway</param-value>
名前を修正しました。
https://github.com/nablarch/nablarch-document/pull/353/commits/234d209298a08465e9a53c0f628fd2f9f823c69b

2021-03-10 06:21 UTC, kumagoro1202 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +Jerseyは、デフォルトでは ``java.net.HttpURLConnection`` をトランスポート層に利用する。
構成を見直しました。
https://github.com/nablarch/nablarch-document/pull/353/commits/5aff94ef5e69cc4e100fac0e81a4f48c66d3b386

2021-03-10 06:24 UTC, kumagoro1202 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +  package com.example.system.httpclient;
`com.example`にしました。`HttpProductRepository`だけインフラ層であることわかるパッケージにしようかと思いましたが、あまり意味はなさそうなのでこちらも修正しました。
https://github.com/nablarch/nablarch-document/pull/353/commits/1457e07856390f2d98fcdbed5d4d88bfedad61e9
https://github.com/nablarch/nablarch-document/pull/353/commits/d2c26bee1bcf1103ed1f68938868490b74ccd343

2021-03-10 06:25 UTC, kumagoro1202 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +システムリポジトリに登録したHTTPクライアントを使用するクラスの例を以下に示す。
確かにどこを見ていいかわからなくなりそうなので削りました。システムリポジトリから取得する例も追記しました。
https://github.com/nablarch/nablarch-document/pull/353/commits/11fc4417f630fba5a08a69a4e7eb000107a9a558

2021-03-10 07:42 UTC, backpaper0 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +Jerseyは、デフォルトでは ``java.net.HttpURLConnection`` をトランスポート層に利用する。
「トランスポート層」という言葉が唐突に出てきてよくわからないです。
読者はこのコンテキストにおける「トランスポート層」という言葉が指す意味を理解していることが前提であるように思えます。

2021-03-10 10:40 UTC, kumagoro1202 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +Jerseyは、デフォルトでは ``java.net.HttpURLConnection`` をトランスポート層に利用する。
トランスポート層という言葉を使わず説明を書き直しました。
https://github.com/nablarch/nablarch-document/pull/353/commits/0de494bc18ac600abd67c62e39233c9ce18ac149#diff-10dc7bf7518dbc624fd4bb58913bc67e0de1d8e3cfe7c92e501db5dce192cde5L117-R123

2021-03-10 10:40 UTC, kumagoro1202 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +システムリポジトリに登録したHTTPクライアントを使用するクラスの例を以下に示す。
https://github.com/nablarch/nablarch-document/pull/353/commits/0de494bc18ac600abd67c62e39233c9ce18ac149#diff-10dc7bf7518dbc624fd4bb58913bc67e0de1d8e3cfe7c92e501db5dce192cde5L225-R228

2021-03-10 11:11 UTC, backpaper0 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +システムリポジトリに登録したHTTPクライアントを使用するクラスの例を以下に示す。
`implements ProductRepository`もなくていいと思いました。

あと`GenericType`は（ぱっと見）ややこしいので`get(ProductResponse.class)`みたいな例でいいと思います。

2021-03-10 11:13 UTC, backpaper0 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +JerseyクライアントにConnectorSPIを実装する ``HttpUrlConnectorProvider`` を登録することで ``java.net.HttpURLConnection`` 以外の方法でHTTP通信が可能となる。
`ConnectorSPI`って言葉はJerseyのドメインなので説明なしに使うのは違和感があります。

「HttpUrlConnectorProviderというインターフェースが用意されているので、それの実装クラスを作成してJerseyクライアントに登録することで java.net.HttpURLConnection 以外の方法でHTTP通信が可能となる。」みたいな説明が良いと思います。

2021-03-10 11:19 UTC, kumagoro1202 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +システムリポジトリに登録したHTTPクライアントを使用するクラスの例を以下に示す。
https://github.com/nablarch/nablarch-document/pull/353/commits/b1560f5b8fe8b9c1056f46871d3ad15bcb0e3364

2021-03-10 11:19 UTC, kumagoro1202 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +JerseyクライアントにConnectorSPIを実装する ``HttpUrlConnectorProvider`` を登録することで ``java.net.HttpURLConnection`` 以外の方法でHTTP通信が可能となる。
https://github.com/nablarch/nablarch-document/pull/353/commits/37b0723f7bd34d0849468c9053f3d3f146f23f14

2021-03-10 11:26 UTC, backpaper0 requested changes

2021-03-10 11:26 UTC, backpaper0 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +Apache HttpComponentsを利用するための ``HttpUrlConnectorProvider`` として ``org.glassfish.jersey.apache.connector.ApacheConnectorProvider`` が用意されている。
`ApacheConnectorProvider`がFQCNなのに`HttpUrlConnectorProvider`が単純名なのは違和感がありますね、、、

2021-03-10 11:26 UTC, backpaper0 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +受信HTTPリクエスト
「受信HTTPリクエスト」ってX-Rayのドキュメントに書かれていた言葉ですか？
めちゃくちゃ造語っぽくて違和感があります。

2021-03-10 11:26 UTC, backpaper0 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +送信HTTP呼び出し
「送信HTTP呼び出し」も造語っぽくて違和感が、、、

2021-03-10 11:37 UTC, kumagoro1202 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +受信HTTPリクエスト
はい、X-Rayの記述に合わせています。

https://docs.aws.amazon.com/ja_jp/xray/latest/devguide/xray-sdk-java.html

2021-03-10 11:37 UTC, kumagoro1202 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +Apache HttpComponentsを利用するための ``HttpUrlConnectorProvider`` として ``org.glassfish.jersey.apache.connector.ApacheConnectorProvider`` が用意されている。
公式サイトに記載されている`HttpUrlConnectorProvider`という名前も誤っていることがわかったので修正しFQCNで記載ました。
https://github.com/nablarch/nablarch-document/pull/353/commits/3bed2875a26ae1a01fac2409893bb146e98964fe

2021-03-10 11:47 UTC, backpaper0 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +      public ProductResponse findAll() {
こまかいけどメソッド名と型が合っていない感じがします。

`Products`とか`ProductList`みたいな名前の方が良いと思います。

2021-03-10 11:58 UTC, kumagoro1202 commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +      public ProductResponse findAll() {
ProductListにしました。
https://github.com/nablarch/nablarch-document/pull/353/commits/0ac74621f8395213cb2820e4c6d704800c391431

2021-03-11 01:30 UTC, SaitoTakuma approved these changes

2021-03-11 01:40 UTC, merged