NAB-417 container-batchアーキタイプのドキュメントの追加（日本語）
nablarch/nablarch-document pull request #370
Opened 2021-09-09 11:13 UTC by fyamvbf

2021-09-14 11:56 UTC, kumagoro1202 requested changes

2021-09-14 11:56 UTC, kumagoro1202 commented on ja/application_framework/application_framework/cloud_native/containerize/index.rst
> +:ref:`標準のバッチアプリケーションのブランクプロジェクト <firstStepGenerateBatchBlankProject>` を使ってNablarchバッチアプリケーションを構築した場合、以下の点が `The Twelve-Factor App`_ (外部サイト)に反した状態になっている。
バッチに12FAを絡めるのは違和感があるので、構成を変えてNablarchウェブアプリケーションの中に12FAの言及を入れ込み、バッチでは12FAに則るわけではないが同様にコンテナ化することでIaaS、FaaSで実行できるようログや設定を12FAに準じたクラウドネイティブに最適化しているというような論調で記載してください。

2021-09-15 08:53 UTC, fyamvbf commented on ja/application_framework/application_framework/blank_project/setup_containerBlankProject/setup_ContainerBatch.rst
> +例えば、ベースイメージに ``tomcat:9.0.31-jdk11-adoptopenjdk-hotspot`` を使用したい場合は、次のように ``pom.xml`` に記述する。
adoptopenjdkに変更
https://github.com/nablarch/nablarch-document/pull/370/commits/d22b530841688b19b01bbab75495b4d5125c5c1d

2021-09-15 08:53 UTC, fyamvbf commented on ja/application_framework/application_framework/blank_project/setup_containerBlankProject/setup_ContainerBatch.rst
> +    SAMPLE.h2.dbを使用しない場合は、ボリュームの指定(``-v``)は不要になる。
SAMPLE.h2.dbに対するボリューム指定箇所の明示
https://github.com/nablarch/nablarch-document/pull/370/commits/6c4f8cbbfd99c7c9302b3d5c52df58ab05b38917

2021-09-15 08:54 UTC, fyamvbf commented on ja/application_framework/application_framework/blank_project/MavenModuleStructures/index.rst
> +        |   +---jib                             … コンテナイメージ上に配置するファイルが格納されている。
コンテナ版Webと重複する記述の削除
https://github.com/nablarch/nablarch-document/pull/370/commits/666ed8d454533a0013e7f16f174a9561f6bb8d3a

2021-09-15 08:55 UTC, fyamvbf commented on ja/application_framework/application_framework/blank_project/MavenModuleStructures/index.rst
> +(ディレクトリ及びファイルの説明は、Webに存在しない要素についてのみ記載)
コンテナ版Webと重複する記述の削除
https://github.com/nablarch/nablarch-document/pull/370/commits/666ed8d454533a0013e7f16f174a9561f6bb8d3a

2021-09-15 08:55 UTC, fyamvbf commented on ja/application_framework/application_framework/blank_project/MavenModuleStructures/index.rst
> +src/main/jib について
コンテナ版Webと重複する記述の削除
https://github.com/nablarch/nablarch-document/pull/370/commits/666ed8d454533a0013e7f16f174a9561f6bb8d3a

2021-09-15 08:59 UTC, fyamvbf commented on ja/application_framework/application_framework/cloud_native/containerize/index.rst
> +Nablarchバッチアプリケーションにに必要な修正
誤植を修正
https://github.com/nablarch/nablarch-document/pull/370/commits/25937bb198b7753e7430ad223c66630162cfc751

2021-09-15 11:18 UTC, fyamvbf commented on ja/application_framework/application_framework/cloud_native/containerize/index.rst
> +
ログ出力について追記
https://github.com/nablarch/nablarch-document/pull/370/commits/c3cdc1e9e16e73250a6791d9cf57c87c6b828b36

2021-09-15 11:30 UTC, fyamvbf commented on ja/application_framework/application_framework/cloud_native/containerize/index.rst
> +:ref:`標準のバッチアプリケーションのブランクプロジェクト <firstStepGenerateBatchBlankProject>` を使ってNablarchバッチアプリケーションを構築した場合、以下の点が `The Twelve-Factor App`_ (外部サイト)に反した状態になっている。
12FAの主戦場はSaaSであるが、バッチを非該当とは名言していない。実際に、多くのFactorは適用可能である。
これについて、「11.1.3. Nablarchバッチアプリケーションに必要な修正」の冒頭にその旨を記述したので、以前のような、12FA＝バッチのような不自然さはなくなったと考えている。
冒頭の「11.1.1.2. The Twelve-Factor App」の場所については、Webにもバッチにも関与しているところは間違っていないので、このままとしている。
https://github.com/nablarch/nablarch-document/pull/370/commits/c3cdc1e9e16e73250a6791d9cf57c87c6b828b36

2021-09-16 02:34 UTC, kumagoro1202 commented on ja/application_framework/application_framework/blank_project/MavenModuleStructures/index.rst
> +src/main/jib について
コンテナ版batchじゃなくコンテナ版Webからsrc/main/jibの記述が消えてしまっています。

2021-09-16 02:38 UTC, kumagoro1202 commented on ja/application_framework/application_framework/cloud_native/containerize/index.rst
> +
意図がないならWebの順番と合わせてください。
・ログ出力
・環境変数
の順番。
12FAの項番に合わせるならWebの方も
・環境変数
・ステートレス
・ログ出力
の順番に変更してください。

2021-09-16 09:43 UTC, fyamvbf commented on ja/application_framework/application_framework/cloud_native/containerize/index.rst
> +
12FAの順にそった並びに変更
https://github.com/nablarch/nablarch-document/pull/370/commits/bcf668bbe3b5b17fe26095e226f7fc3ded35f5c8

2021-09-16 09:43 UTC, fyamvbf commented on ja/application_framework/application_framework/blank_project/MavenModuleStructures/index.rst
> +src/main/jib について
コンテナ版Webを元に戻し、コンテナ版バッチの記述を削除
https://github.com/nablarch/nablarch-document/pull/370/commits/853ad14394de28c46cf6868f381ca80a7cbdcf1a

2021-09-17 00:10 UTC, kumagoro1202 commented on ja/application_framework/application_framework/cloud_native/containerize/index.rst
> +
12FAではなくWebの順番に合わせたと理解。

2021-09-17 00:11 UTC, kumagoro1202 approved these changes

2021-09-17 00:12 UTC, merged