Nab 424 グローバルエラーハンドラ、リクエストディスパッチハンドラの記述修正
nablarch/nablarch-document pull request #382
Opened 2021-10-08 08:31 UTC by fyamvbf

2021-10-08 10:07 UTC, kumagoro1202 requested changes

2021-10-08 10:07 UTC, kumagoro1202 commented on ja/application_framework/application_framework/handlers/common/request_path_java_package_mapping.rst
> +    -   本ハンドラの実行直後にアクションのhandleメソッドが呼び出される。アクション内で明示的に後続のハンドラを呼び出す処理を記述しない場合は、後続のハンドラは呼び出されない。
この辺も他の解説書の感じと違いを感じるので↓みたいな記載にしてほしいです。

デフォルトではディスパッチ対象クラスへの委譲は即時実行されるが、ハンドラキュー上の後続のハンドラ実行後にディスパッチ対象クラスへの委譲を行いたい場合は、以下の例を参照してimmediateプロパティにfalseを設定すること。

    <!-- ディスパッチ -->
    <component class="nablarch.fw.handler.RequestPathJavaPackageMapping">
      <property name="basePackage" value="${nablarch.commonProperty.basePackage}" />
      <property name="immediate" value="false" />
    </component>

2021-10-08 10:07 UTC, kumagoro1202 commented on ja/application_framework/application_framework/handlers/common/request_path_java_package_mapping.rst
> +``immediate`` プロパティを未設定もしくはtrueに設定する場合は、本ハンドラはハンドラキューの最後に置くこと。( :ref:`request_path_java_package_mapping_optional_immediate` 参照)
これは制約じゃないです。もしこの条件だけであれば制約なしにしてください。
実装上スレッドコンテキストのリクエストIDを見てるからスレッドコンテキスト変数保存ハンドラより後ろに置かないといけないとか（例です。実際そうなっているという意味ではないです。）そういう制約だけを書いてください。デフォルトだと最後に置かないといけないは記載する必要ないです。

2021-10-08 10:26 UTC, kumagoro1202 requested changes

2021-10-08 10:26 UTC, kumagoro1202 commented on ja/application_framework/application_framework/handlers/common/global_error_handler.rst
> +  スレッドコンテキストの情報をログに出力する場合は、 :ref:`thread_context_clear_handler` より後に配置すること。
「例外を補足した際にスレッドコンテキストの情報をログに出力したい場合は」とかにしてください。

2021-10-11 04:47 UTC, fyamvbf commented on ja/application_framework/application_framework/handlers/common/request_path_java_package_mapping.rst
> +``immediate`` プロパティを未設定もしくはtrueに設定する場合は、本ハンドラはハンドラキューの最後に置くこと。( :ref:`request_path_java_package_mapping_optional_immediate` 参照)
制約記述を削除　https://github.com/nablarch/nablarch-document/pull/382/commits/5f7e3a848db7d4bffdf0a060aadf84bcb8d83cd1

2021-10-11 04:47 UTC, fyamvbf commented on ja/application_framework/application_framework/handlers/common/global_error_handler.rst
> +  スレッドコンテキストの情報をログに出力する場合は、 :ref:`thread_context_clear_handler` より後に配置すること。
global_error_handler記述を修正
https://github.com/nablarch/nablarch-document/pull/382/commits/94b33e3763bd63ae80657cf07d46e327cdc6b4d5

2021-10-11 04:48 UTC, fyamvbf commented on ja/application_framework/application_framework/handlers/common/request_path_java_package_mapping.rst
> +アクションの handle メソッドを呼び出すタイミングの指定
immediateプロパティの説明記述変更
https://github.com/nablarch/nablarch-document/pull/382/commits/6bb90798b1d098a42327f9e895e8db0defb27b5c

2021-10-11 04:48 UTC, fyamvbf commented on ja/application_framework/application_framework/handlers/common/request_path_java_package_mapping.rst
> +    -   本ハンドラの実行直後にアクションのhandleメソッドが呼び出される。アクション内で明示的に後続のハンドラを呼び出す処理を記述しない場合は、後続のハンドラは呼び出されない。
immediateプロパティの説明記述変更
https://github.com/nablarch/nablarch-document/pull/382/commits/6bb90798b1d098a42327f9e895e8db0defb27b5c

2021-10-18 07:13 UTC, merged