NAB-440 バージョンアップポリシー文書の追加
nablarch/nablarch-document pull request #404
Opened 2021-12-17 02:43 UTC by fyamvbf

2021-12-17 08:59 UTC, kumagoro1202 requested changes

2021-12-17 08:59 UTC, kumagoro1202 commented on ja/about_nablarch/versionup_policy.rst
> +    - 4半期～半期 |br|
半期でいいです。

2021-12-17 08:59 UTC, kumagoro1202 commented on ja/about_nablarch/versionup_policy.rst
> +      不具合については、影響範囲を見定めリリーススケジュールを決定し、リリースします。
これをテーブル内に書くと折り返して見にくいです。
以下のようにテーブル外に注意書きした方がいいと思います。
https://nablarch.github.io/docs/LATEST/doc/application_framework/application_framework/libraries/log.html#id30

2021-12-17 08:59 UTC, kumagoro1202 commented on ja/about_nablarch/versionup_policy.rst
> +    - リリースサイクル
最大幅に広げたとき
```
リリースサイク
ル
```
とぶら下がり文字になります。調整してください。

2021-12-17 08:59 UTC, kumagoro1202 commented on ja/about_nablarch/versionup_policy.rst
> +    - 不具合対応、機能追加・変更（アプリケーションフレームワークについては、いわゆる「枯れた」状態にするための改善レベルの機能追加・変更）を行います。 |br|
（）内は冗長なので不要です。

2021-12-17 08:59 UTC, kumagoro1202 commented on ja/about_nablarch/versionup_policy.rst
> +      ・拡張コンポーネントの追加/変更 |br|
この例消しといてください。

2021-12-17 08:59 UTC, kumagoro1202 commented on ja/about_nablarch/versionup_policy.rst
> +基本的にオブジェクトコード（jarファイル）の差し替えと設定ファイルの変更のみでバージョンアップできます。
オブジェクトコード（jarファイル）の差し替えという表現に違和感があります。
確かにその通りなんですが、実態としてはbomのバージョンアップです。
Maven使ってなかった1.4時代からの表現に感じるので見直してください。

2021-12-17 11:49 UTC, fyamvbf commented on ja/about_nablarch/versionup_policy.rst
> +    - 4半期～半期 |br|
上記の通り対応しました。

2021-12-17 11:50 UTC, fyamvbf commented on ja/about_nablarch/versionup_policy.rst
> +      不具合については、影響範囲を見定めリリーススケジュールを決定し、リリースします。
バグフィックスも含めて対応しました。

2021-12-17 11:50 UTC, fyamvbf commented on ja/about_nablarch/versionup_policy.rst
> +    - リリースサイクル
調整しました

2021-12-17 11:50 UTC, fyamvbf commented on ja/about_nablarch/versionup_policy.rst
> +    - 不具合対応、機能追加・変更（アプリケーションフレームワークについては、いわゆる「枯れた」状態にするための改善レベルの機能追加・変更）を行います。 |br|
上記の通り対応しました。

2021-12-17 11:50 UTC, fyamvbf commented on ja/about_nablarch/versionup_policy.rst
> +      ・拡張コンポーネントの追加/変更 |br|
マイナーバージョンアップの例も含めて消しました

2021-12-17 12:42 UTC, fyamvbf commented on ja/about_nablarch/versionup_policy.rst
> +基本的にオブジェクトコード（jarファイル）の差し替えと設定ファイルの変更のみでバージョンアップできます。
この場所なので、mavenを知らない人でも理解できるような表現にて修正しました。

2021-12-20 00:56 UTC, kumagoro1202 commented on ja/about_nablarch/versionup_policy.rst
> +      ・拡張コンポーネントの追加/変更 |br|
消して欲しいのは"拡張コンポーネント"だけです。例があることでマイナーバージョンアップとリビジョンアップの違いがわかるようになっているのでまるごと消すのはやめてください。

2021-12-20 01:01 UTC, kumagoro1202 requested changes

2021-12-20 01:01 UTC, kumagoro1202 commented on ja/about_nablarch/versionup_policy.rst
> + ツールの詳細は、`nablarch-intellij-plugin <https://github.com/nablarch/nablarch-intellij-plugin>`_ を参照してください。
nablarch-intellij-pluginのリポジトリにいきなり飛ばさず以下へのリンクの方がいいと思いました。
https://nablarch.github.io/docs/LATEST/doc/development_tools/java_static_analysis/index.html#api

2021-12-20 01:05 UTC, kumagoro1202 commented on ja/about_nablarch/versionup_policy.rst
> +基本的にオブジェクトコード（jarファイル）の差し替えと設定ファイルの変更のみでバージョンアップできます。
もとの文と内容が違ってしまっています。
元の文は「基本的にオブジェクトコード(jarファイル)の差し替え`(=bomのバージョンアップ)`と設定ファイル`(=コンポーネント定義ファイルとconfigファイル)`の変更のみでバージョンアップできます。」です。
後半の設定ファイルはpom.xmlのことではありません。

使用するNablarchのバージョンの差し替えと設定ファイルの変更のみでバージョンアップできます。
として、使用するNablarchのバージョンの部分に以下へのリンクをはるのがいいかと思います。
https://nablarch.github.io/docs/LATEST/doc/application_framework/application_framework/blank_project/beforeFirstStep.html#nablarch

2021-12-21 10:29 UTC, fyamvbf commented on ja/about_nablarch/versionup_policy.rst
> + ツールの詳細は、`nablarch-intellij-plugin <https://github.com/nablarch/nablarch-intellij-plugin>`_ を参照してください。
上記対応しました　https://github.com/nablarch/nablarch-document/pull/404/commits/f543ffb16a350499f04b419daa776f8bf5ac5692

2021-12-22 01:38 UTC, fyamvbf commented on ja/about_nablarch/versionup_policy.rst
> +      ・拡張コンポーネントの追加/変更 |br|
対応しました　https://github.com/nablarch/nablarch-document/pull/404/commits/af99dcd85c750b93657943f6536ed29d3746f21c

2021-12-22 01:38 UTC, fyamvbf commented on ja/about_nablarch/versionup_policy.rst
> +基本的にオブジェクトコード（jarファイル）の差し替えと設定ファイルの変更のみでバージョンアップできます。
対応しました　https://github.com/nablarch/nablarch-document/pull/404/commits/0945fa7fd2a5109368f4bbed8d822778846a5963

2021-12-22 06:12 UTC, kumagoro1202 commented on ja/about_nablarch/versionup_policy.rst
> + ツールの詳細は、`nablarch-intellij-plugin <https://github.com/nablarch/nablarch-intellij-plugin>`_ を参照してください。
こっちのコミットですね。
https://github.com/nablarch/nablarch-document/pull/404/commits/ffb651c23ea7b8d0f13a865e7cef3fdf553ff389

2021-12-22 06:13 UTC, kumagoro1202 commented on ja/about_nablarch/versionup_policy.rst
> +基本的にオブジェクトコード（jarファイル）の差し替えと設定ファイルの変更のみでバージョンアップできます。
こっちのコミットですね。
https://github.com/nablarch/nablarch-document/pull/404/commits/ffb651c23ea7b8d0f13a865e7cef3fdf553ff389

2021-12-22 06:15 UTC, kumagoro1202 approved these changes

2021-12-22 06:16 UTC, merged