英語版登録
nablarch/nablarch-document pull request #406
Opened 2021-12-27 07:18 UTC by fyamvbf

2021-12-27 08:00 UTC, kumagoro1202 requested changes

2021-12-27 08:00 UTC, kumagoro1202 commented on en/about_nablarch/versionup_policy.rst
> +If we make changes that don't maintain backward compatibility, we'll explain what they're doing and how to deal with them in the "Possible System Impact Content and Actions" section of the `Release N
Possible System Impact Content and Actionsも直訳感がありますね。
"Impact on the system and how to deal with it"とかにするか日本語で「システムへの影響の可能性の内容と対処」と書いてもいいんじゃないですか。

2021-12-27 09:06 UTC, fyamvbf commented on en/about_nablarch/versionup_policy.rst
> +      Implementation example collection
修正しました。https://github.com/nablarch/nablarch-document/pull/406/commits/b41166d435f365c2798d790f4e8b46aa3d2c722e

2021-12-27 09:06 UTC, fyamvbf commented on en/about_nablarch/versionup_policy.rst
> +      Example: |br|
修正しました。 https://github.com/nablarch/nablarch-document/pull/406/commits/b31cb315562534d1040ea6e94813f881c617bf2b

2021-12-27 09:06 UTC, fyamvbf commented on en/about_nablarch/versionup_policy.rst
> +    - Respond to defects, add/change functions.
修正しました。 https://github.com/nablarch/nablarch-document/pull/406/commits/89c8430025e77a3f815392b805aeddedd05a3642

2021-12-27 09:06 UTC, fyamvbf commented on en/about_nablarch/versionup_policy.rst
> +.. [#release_schedule_for_bugs_revision_up] For defects, we will determine the scope of impact, determine the release schedule, and release it.
修正しました。 https://github.com/nablarch/nablarch-document/pull/406/commits/89c8430025e77a3f815392b805aeddedd05a3642

2021-12-27 09:07 UTC, fyamvbf commented on en/about_nablarch/versionup_policy.rst
> +  | 5   ： Product version 5 initial release
修正しました。 https://github.com/nablarch/nablarch-document/pull/406/commits/b31cb315562534d1040ea6e94813f881c617bf2b

2021-12-27 09:07 UTC, fyamvbf commented on en/about_nablarch/versionup_policy.rst
> +If we make changes that don't maintain backward compatibility, we'll explain what they're doing and how to deal with them in the "Possible System Impact Content and Actions" section of the `Release N
参照するリリースノートのExcelには日本語で書いてあるから、日本語の文字列も案内しないとつながらないですね。
ただ、日本語だけだとわかりにくいと思うので併記させました。
https://github.com/nablarch/nablarch-document/pull/406/commits/97238c638981afceab66a3caf8e38effc330b8ed

2021-12-27 09:08 UTC, fyamvbf commented on en/about_nablarch/versionup_policy.rst
> + **If you use non-public APIs in your project, backward compatibility will not be maintained when upgrading, and unexpected problems may occur.**
Unauthorized API に統一しました
https://github.com/nablarch/nablarch-document/pull/406/commits/8aef9eb210122e79e5b60fbe002176db90faa2d1

2021-12-27 09:08 UTC, fyamvbf commented on en/about_nablarch/versionup_policy.rst
> + For example, what does it mean to maintain backward compatibility of documents?
修正しました　https://github.com/nablarch/nablarch-document/pull/406/commits/46dfea8fd014b4cd2d9595b98ee4efeab08dd95e

2022-01-04 02:14 UTC, kumagoro1202 requested changes

2022-01-04 02:14 UTC, kumagoro1202 commented on en/about_nablarch/versionup_policy.rst
> +  e.g., Nablarch 5u6 → Nablarch 6 |br|
ここは
> e.g., Nablarch 5u6 → Nablarch 6

下では

> e.g., Nablarch 5u6 -> Nablarch 5u7

となっているので統一してください。

2022-01-04 04:56 UTC, fyamvbf commented on en/about_nablarch/versionup_policy.rst
> +  e.g., Nablarch 5u6 → Nablarch 6 |br|
表現を均一化しました　https://github.com/nablarch/nablarch-document/pull/406/commits/6837fb509d33fe73bfd2514c07034dd9d04924d3

2022-01-04 05:27 UTC, kumagoro1202 requested changes

2022-01-04 05:27 UTC, kumagoro1202 commented on en/about_nablarch/versionup_policy.rst
> + For more information on the tool, see :ref:`Checking for unauthorized API. <api-analysis>`
"Checking for unauthorized API"という項目はありません。
リンク先が一番下にあってスクロールされないのもあってリンクを開いた時にどこを見ろと言ってるかがわかりにくいのでリンク先のタイトル"Check if unauthorized APIs are being used"に合わせるべきだと思います。

2022-01-04 05:48 UTC, fyamvbf commented on en/about_nablarch/versionup_policy.rst
> + For more information on the tool, see :ref:`Checking for unauthorized API. <api-analysis>`
リンク元の文言をリンク先に合わせました。　https://github.com/nablarch/nablarch-document/pull/406/commits/472d482341b904cd5dcbcc70ea003957dca82d49

2022-01-04 05:59 UTC, kumagoro1202 requested changes

2022-01-04 05:59 UTC, kumagoro1202 commented on en/about_nablarch/versionup_policy.rst
> +except in cases where :ref:`Backward compatibility exception.<versionup_policy-backward_compatibility_is_not_maintained>`
ピリオドの前の空白を消すためにリンク先のタイトルを書いたみたいですが、不要です。
リンクの後ろの空白は必須ではないので以下のようにスペース消すだけで同じ効果が得られます。
あえて二重管理にするより空白消すだけのほうがいいと思います。
except in cases where :ref:`versionup_policy-backward_compatibility_is_not_maintained\` .
except in cases where :ref:`versionup_policy-backward_compatibility_is_not_maintained\`.

2022-01-04 06:42 UTC, fyamvbf commented on en/about_nablarch/versionup_policy.rst
> +except in cases where :ref:`Backward compatibility exception.<versionup_policy-backward_compatibility_is_not_maintained>`
他にも同様のことをやっているところがあったので、まとめて修正しました。　https://github.com/nablarch/nablarch-document/pull/406/commits/e7363ff18350105604c0f279c28e0f9e81fe8106

2022-01-04 06:51 UTC, kumagoro1202 approved these changes

2022-01-04 06:51 UTC, merged