Nab 445
nablarch/nablarch-document pull request #415
Opened 2022-01-31 08:18 UTC by fyamvbf

2022-01-31 09:01 UTC, kumagoro1202 commented
アーキタイプで設定しているのにデフォルト設定一覧.xlsxでプロパティ値の定義先と設定値が空になっているのはなぜですか？

2022-01-31 09:02 UTC, kumagoro1202 commented
英語版のdefault-configuration-list.xlsxが修正されていません。

2022-01-31 09:10 UTC, kumagoro1202 requested changes

2022-01-31 09:10 UTC, kumagoro1202 commented on ja/application_framework/application_framework/libraries/message.rst
> +  デフォルトのロケールは、:java:extdoc:`PropertiesStringResourceLoader.defaultLocale  <nablarch.core.message.PropertiesStringResourceLoader.setDefaultLocale(java.lang.String defaultLocale)>` (デフォルトの言語)で設定する。設定しな
`setDefaultLocale(java.lang.String defaultLocale)`となっていますが引数の部分に指定するのは型だけです。リンクがちゃんと効いていないです。

2022-02-04 11:08 UTC, fyamvbf commented on ja/application_framework/application_framework/libraries/message.rst
> +  デフォルトのロケールは、:java:extdoc:`PropertiesStringResourceLoader.defaultLocale  <nablarch.core.message.PropertiesStringResourceLoader.setDefaultLocale(java.lang.String defaultLocale)>` (デフォルトの言語)で設定する。設定しな
修正しました　https://github.com/nablarch/nablarch-document/pull/415/commits/e47eb8bef0874615d56525bc7ad2858f534d1727

2022-02-14 04:09 UTC, merged