NAB-453 汎用データフォーマットで同じフィールド名のオブジェクトと非オブジェクトが定義できないことを追記
nablarch/nablarch-document pull request #423
Opened 2022-02-28 06:56 UTC by fyamvbf

2022-03-02 11:36 UTC, kumagoro1202 requested changes

2022-03-02 11:36 UTC, kumagoro1202 commented on ja/application_framework/application_framework/libraries/data_io/data_format/format_definition.rst
> +  JSONおよびXMLデータ形式でフィールド定義を行う場合、同一フィールド名でフィールドタイプが ``OB`` のものと、そうでないものを混在させてはいけない。
混在させるとOBじゃないものが読み取られなくなるとかどういう副作用があるかを書いたほうがいいと思います。

2022-03-02 11:36 UTC, kumagoro1202 commented on ja/application_framework/application_framework/libraries/data_io/data_format/format_definition.rst
> +      1 value  N
レコードタイプの並びもdata→detailの順にした方がいいと思います。

2022-03-03 01:18 UTC, fyamvbf commented on ja/application_framework/application_framework/libraries/data_io/data_format/format_definition.rst
> +      1 value  N
修正しました　https://github.com/nablarch/nablarch-document/pull/423/commits/6d710aed6834a456460825f3881cafdf1e3bc9bb

2022-03-03 01:19 UTC, fyamvbf commented on ja/application_framework/application_framework/libraries/data_io/data_format/format_definition.rst
> +  JSONおよびXMLデータ形式でフィールド定義を行う場合、同一フィールド名でフィールドタイプが ``OB`` のものと、そうでないものを混在させてはいけない。
修正しました　https://github.com/nablarch/nablarch-document/pull/423/commits/6d710aed6834a456460825f3881cafdf1e3bc9bb

2022-03-03 02:13 UTC, kumagoro1202 requested changes

2022-03-03 02:13 UTC, kumagoro1202 commented on ja/application_framework/application_framework/libraries/data_io/data_format/format_definition.rst
> +  混在させた場合は、フィールドタイプに ``OB`` を指定したものとして取り扱われる。
主語がないので何がOBを指定したものとして取り扱われるかが読み取りにくいです。
そもそも具体的に何が利用者の困ることなのか書いたほうがいいと思います。
OBとして取り扱われるのは内部の話なので利用者にはそれがどう問題なのか明記した方が伝わると思います。
混在させた場合はフォーマットが正しく読み取れず値が空になるんですよね？(必ずそういう事象になるのか裏取りしたわけじゃないですが、少なくとも検知した事例では空になってたはずです。)そうであれば「混在させた場合は、フィールドタイプに ``OB`` を指定したものとして取り扱われる。」より「混在させた場合は、フィールドタイプがOBでないものの読み取りができずフィールドが空になる場合がある。」とかの方がいいと思います。
（「空になる場合がある」の部分は仕様に合わせて適宜書き換えてください。）

2022-03-03 06:14 UTC, fyamvbf commented on ja/application_framework/application_framework/libraries/data_io/data_format/format_definition.rst
> +  混在させた場合は、フィールドタイプに ``OB`` を指定したものとして取り扱われる。
修正しました　https://github.com/nablarch/nablarch-document/pull/423/commits/f23bd4ff19414814c462d751c4de7bff6ec921db

2022-03-03 23:45 UTC, merged