同期応答メッセージングの取引単体テスト説明から不要なファイル、プロパティを削除
nablarch/nablarch-document pull request #441
Opened 2022-07-11 01:53 UTC by hiji

2022-07-12 11:43 UTC, kumagoro1202 requested changes

2022-07-12 11:43 UTC, kumagoro1202 commented on ja/application_framework/application_framework/libraries/system_messaging/mom_system_messaging.rst
> +       コンポーネント設定ファイルに :java:extdoc:`SyncMessageConvertor<nablarch.fw.messaging.SyncMessageConvertor>` を設定する。
最初にやるべきことを示したいので「コンポーネント定義ファイルにSyncMessageConvertorを定義する。」を文章の先頭にして欲しいです。

> コンポーネント定義ファイルに [SyncMessageConvertor](https://nablarch.github.io/docs/LATEST/javadoc/nablarch/fw/messaging/SyncMessageConvertor.html) を定義する。
> [MessageSender](https://nablarch.github.io/docs/LATEST/javadoc/nablarch/fw/messaging/MessageSender.html) では、送受信する電文の変換処理を変更できるように、 変換処理を [SyncMessageConvertor](https://nablarch.github.io/docs/LATEST/javadoc/nablarch/fw/messaging/SyncMessageConvertor.html) に委譲している。 このクラスがフレームワーク制御ヘッダの読み書きを行っている。 
> 

あと`messageSender.DEFAULT.messageConvertorName`で委譲するConvertorのコンポーネント名を指定しているのでコンポーネント定義にはここに指定した名前でコンポーネントを定義するということに触れた方がいいのではと思いました。

と書いてから実装を見てみました。

https://github.com/nablarch/nablarch-fw-messaging/blob/master/src/main/java/nablarch/fw/messaging/MessageSender.java#L180-L197
と
https://nablarch.github.io/docs/LATEST/javadoc/nablarch/fw/messaging/MessageSenderSettings.html#MessageSenderSettings-java.lang.String-
のJavadocを見て気づいたんですが、`messageSender.DEFAULT.messageConvertorName`は必須設定項目ではないですね。
「リポジトリから取得する際に使用するコンポーネント名」というのは言葉が足りて無くて「SyncMessageConvertorの処理を差し替えるために継承した独自クラスをコンポーネント定義している場合に、リポジトリから取得する際に使用するコンポーネント名」ですね。
なので、

> 送受信する電文の変換処理を変更する場合は、コンポーネント定義ファイルに [SyncMessageConvertor](https://nablarch.github.io/docs/LATEST/javadoc/nablarch/fw/messaging/SyncMessageConvertor.html)を継承したクラス を定義する。
> [MessageSender](https://nablarch.github.io/docs/LATEST/javadoc/nablarch/fw/messaging/MessageSender.html) では、送受信する電文の変換処理を変更できるように、 変換処理を [SyncMessageConvertor](https://nablarch.github.io/docs/LATEST/javadoc/nablarch/fw/messaging/SyncMessageConvertor.html) に委譲している。 このクラスがフレームワーク制御ヘッダの読み書きを行っている。 変換処理を変更する場合はSyncMessageConvertorを継承したクラスを作成し、そのクラスをコンポーネント定義する。コンポーネントの名前をmessageSender.DEFAULT.messageConvertorNameに指定することでMessageSenderが委譲するメッセージコンバータを変更することができる。
> 

みたいな話になるのかと思いました。
messageSender.DEFAULT.messageConvertorNameを設定しなければデフォルトでSyncMessageConvertorが使われます。

2022-07-13 08:21 UTC, hiji commented on ja/application_framework/application_framework/libraries/system_messaging/mom_system_messaging.rst
> +       コンポーネント設定ファイルに :java:extdoc:`SyncMessageConvertor<nablarch.fw.messaging.SyncMessageConvertor>` を設定する。
修正しました。

3615dd651b6607b7d0bb7c78abe96d0f851eeda0

2022-07-13 08:27 UTC, hiji commented on ja/application_framework/application_framework/libraries/system_messaging/mom_system_messaging.rst
> +       コンポーネント設定ファイルに :java:extdoc:`SyncMessageConvertor<nablarch.fw.messaging.SyncMessageConvertor>` を設定する。
修正しました。 

c35aba022e2bdaf627497a8cb7d93a9f3fa634c3

メッセージコンバーターを拡張するときだけ `messageSender.DEFAULT.messageConvertorName` を指定するのが本来の使い方なのですね、ありがとうございます。

それをもとに考えて直してみたところ、`SyncMessageConverter`の拡張については [7.6.1.4.1. フレームワーク制御ヘッダの読み書きを変更する](https://nablarch.github.io/docs/LATEST/doc/application_framework/application_framework/libraries/system_messaging/mom_system_messaging.html#id24) で触れているため、冗長にならないようにそこへのリンクを案内する文章としてみました。

またここでの記述はあくまで標準的な設定向けであると思いますので、以下の修正もしました。

-  `message.properties` からは `messageSender.DEFAULT.messageConvertorName` の記述を削除
- コンポーネント定義ファイルから`SyncMessageConverter`の定義を削除

2022-07-14 00:41 UTC, kumagoro1202 requested changes

2022-07-14 00:41 UTC, kumagoro1202 commented on en/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/03_DealUnitTest/send_sync.rst
> +For How to switch components in each environment, see: ref: `how_to_change_componet_define` .
スペースが入ってリンクが死んでいます。

2022-07-14 01:17 UTC, hiji commented on en/application_framework/application_framework/libraries/system_messaging/mom_system_messaging.rst
>      messageSender.DEFAULT.messageConvertorName=defaultSyncMessageConvertor
削除しました。

c8be024c1f1de3eb5706a3b4ff68e772e31adfea

2022-07-14 01:22 UTC, kumagoro1202 approved these changes

2022-07-14 01:22 UTC, merged