textlintの指摘対応
nablarch/nablarch-document pull request #444
Opened 2022-08-04 05:01 UTC by hiji

2022-08-04 12:12 UTC, kumagoro1202 requested changes

2022-08-04 12:13 UTC, kumagoro1202 commented on ja/application_framework/application_framework/handlers/common/global_error_handler.rst
> +このハンドラでは捕捉した例外及びエラーの内容に応じて、以下の処理と結果を生成する。
違和感の原因は「処理と結果」を「生成する」に見えるから。
文の意味は「処理」と「結果を生成」するなのでおかしく見える。

2022-08-04 12:17 UTC, kumagoro1202 commented on ja/application_framework/application_framework/libraries/database_management.rst
> +データベースへの接続やSQLを実行する機能を提供する。
ここはやっぱりこのままでも問題ないかな。
データベースへの接続機能を提供する
SQLを実行する機能を提供する
の並列なら問題なく感じる。

2022-08-05 02:15 UTC, hiji commented on ja/development_tools/ui_dev/doc/internals/architecture_overview.rst
> +                                                       **サードパーティJSライブラリ** を利用する。
Slackでお伝えしましたとおり、rstの解析がうまくできていないのか、textlintが効いていない箇所が結構あるようでした...
「利用」のチェックについては、手動で検索して引っ掛かった箇所に対して、修正後で文章に違和感なければ修正しました。ただ、該当箇所が100件近くあったので、以下のコミットでまとめて確認頂ければと思います。

4d1d168b7930df0dd19e6ba108b167816d545ada

2022-08-05 02:16 UTC, hiji commented on ja/examples/02/index.rst
> +  以下のユーティリティを利用してメールアドレスを精査できる。
上記と同じです。

2022-08-05 02:17 UTC, hiji commented on ja/development_tools/toolbox/SqlExecutor/SqlExecutor.rst
> +ビルド済みのツールは配布可能であるため、本作業をするのはPJ内の1人でよい。
対応しました。

f0e8a6d45f28b35ca2c3a514b7fe55fc2ad81938

2022-08-05 02:17 UTC, hiji commented on ja/development_tools/testing_framework/guide/development_guide/06_TestFWGuide/RequestUnitTest_send_sync.rst
> +* Excelから読み込んだデータに対して任意で編集する。
対応しました。

f0e8a6d45f28b35ca2c3a514b7fe55fc2ad81938

2022-08-05 02:17 UTC, hiji commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/03_DealUnitTest/send_sync.rst
> +しかし、Excelファイルの編集や上書きして、タイムスタンプを更新することで、アプリケーションサーバ起動中にExcelファイルの再読み込みを行うことができる。
対応しました。

f0e8a6d45f28b35ca2c3a514b7fe55fc2ad81938

2022-08-05 02:17 UTC, hiji commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/03_DealUnitTest/index.rst
> +テスト準備として以下の作業をする。
対応しました。

f0e8a6d45f28b35ca2c3a514b7fe55fc2ad81938

2022-08-05 02:18 UTC, hiji commented on ja/application_framework/application_framework/web/feature_details/view/freemarker.rst
> +なお、本解説書は下のdependencyに記載のバージョンにて確認している。
対応しました。

16a08e4202856b28009812a65cd24cd8aea84e1c

2022-08-05 02:19 UTC, hiji commented on ja/about_nablarch/concept.rst
> +しかし、変化の激しいビジネス環境に対応するには、なるべく短期間かつ高品質でシステム構築する必要があります。
対応しました。

13d6be06b24c83138158d26a9b073de515c9d5e2

2022-08-05 02:19 UTC, hiji commented on ja/application_framework/adaptors/doma_adaptor.rst
> +  :ref:`Chunkステップ <jsr352-batch_type_chunk>` のItemWriterでデータベースに対するバッチ更新(バッチinsertやバッチupdateなど)する場合、バッチサイズの指定を明示的に行う必要がある。
対応しました。

13d6be06b24c83138158d26a9b073de515c9d5e2

2022-08-05 02:19 UTC, hiji commented on ja/application_framework/adaptors/micrometer_adaptor.rst
> +そして、 ``increment(long)`` の呼び出し間隔を計測することでトランザクション単位の時間を計測をしている。
対応しました。

13d6be06b24c83138158d26a9b073de515c9d5e2

2022-08-05 02:19 UTC, hiji commented on ja/application_framework/adaptors/web_thymeleaf_adaptor.rst
> +テンプレートエンジンを使用してレスポンスを出力する否かを判断する。
対応しました。

13d6be06b24c83138158d26a9b073de515c9d5e2

2022-08-05 02:20 UTC, hiji commented on ja/application_framework/application_framework/batch/functional_comparison.rst
> +ｄ
対応しました。

a9ab112aa1dd81bb7737a0ec0a6a8970b0024f9a

2022-08-05 02:20 UTC, hiji commented on ja/application_framework/application_framework/batch/jsr352/getting_started/chunk/index.rst
> +既存データから計算し、新たにデータを導出するバッチの実装方法を以下の順に説明する。
対応しました。

a9ab112aa1dd81bb7737a0ec0a6a8970b0024f9a

2022-08-05 02:20 UTC, hiji commented on ja/application_framework/application_framework/cloud_native/distributed_tracing/aws_distributed_tracing.rst
> +このインタフェースを使用することで、 ``HttpClientBuilder`` に追加で設定することや、 ``HttpClientBuilder`` そのものを差し替えるといった処理が可能となる。
対応しました。

a7d58dd6aca815121a6ff4efa87c38c54d668ae6

2022-08-05 02:23 UTC, hiji commented on ja/application_framework/application_framework/handlers/common/global_error_handler.rst
> +このハンドラでは捕捉した例外及びエラーの内容に応じて、以下の処理と結果を生成する。
「～を行う」だと引っ掛かりました。
除外設定してもよいのですが、「以下の処理を行い結果を生成する」といった文章に見直してみました。もし問題ありましたら除外設定しようと思います。

a9ab112aa1dd81bb7737a0ec0a6a8970b0024f9a

2022-08-05 02:25 UTC, hiji commented on ja/application_framework/application_framework/handlers/http_messaging/http_messaging_error_handler.rst
> +* 例外(エラー)に応じたログ出力とレスポンスを生成する。
箇条書きのところで除外設定がうまく効かなかったので、元の文章に近い形に見直しました（「ログ出力とレスポンス生成をする」）ので確認をお願いしたいです。

a9ab112aa1dd81bb7737a0ec0a6a8970b0024f9a

2022-08-05 02:28 UTC, hiji commented on ja/application_framework/application_framework/handlers/web/HttpErrorHandler.rst
> +後続のハンドラで発生した例外に対するログ出力やレスポンスへ変換するハンドラ。
[上記](https://github.com/nablarch/nablarch-document/pull/444#discussion_r938390271)と同じ。

4ad71245f664ff5ebf6ce07d9c2b93d012b1f6f2

2022-08-05 02:29 UTC, hiji commented on ja/application_framework/application_framework/libraries/data_io/data_format/format_definition.rst
> +Variable(可変長)データ形式で使用可能フィールドタイプ一覧
対応しました。

4c8de6718a3c2529a4d2c4a1eb09de3d04bc053e

2022-08-05 02:29 UTC, hiji commented on ja/application_framework/application_framework/libraries/database/functional_comparison.rst
> +.. [#validaiton] Nablarchでは、外部からのデータを受け付けたタイミングでバリデーションを実施し、バリデーションエラーがない場合のみEntityへの変換及びデータベースへ保存する。
対応しました。

4c8de6718a3c2529a4d2c4a1eb09de3d04bc053e

2022-08-05 02:30 UTC, hiji commented on ja/application_framework/application_framework/libraries/database/generator.rst
> +ユニバーサルDAO用に採番を設定
対応しました。

4c8de6718a3c2529a4d2c4a1eb09de3d04bc053e

2022-08-05 02:31 UTC, hiji commented on ja/application_framework/application_framework/libraries/database_management.rst
> +データベースへの接続やSQLを実行する機能を提供する。
問題ないとのことでしたが、区切りを強調するために読点を入れました。

4c8de6718a3c2529a4d2c4a1eb09de3d04bc053e

2022-08-05 02:31 UTC, hiji commented on ja/application_framework/application_framework/libraries/log.rst
> +そのため、新規にプレースホルダを追加したい場合は、以下の作業をする。
対応しました。

4c8de6718a3c2529a4d2c4a1eb09de3d04bc053e

2022-08-05 02:32 UTC, hiji commented on ja/application_framework/application_framework/libraries/log/failure_log.rst
> +このように、プレースホルダに対する出力処理をカスタマイズしたい場合は、以下の作業をする。
対応しました。

4c8de6718a3c2529a4d2c4a1eb09de3d04bc053e

2022-08-05 02:33 UTC, hiji commented on ja/application_framework/application_framework/libraries/session_store.rst
> +.. [3] 画面表示に使用する値はリクエストスコープを使用して受け渡しすればよい。
対応しました。

4c8de6718a3c2529a4d2c4a1eb09de3d04bc053e

2022-08-05 02:33 UTC, hiji commented on ja/application_framework/application_framework/libraries/tag.rst
> +オブジェクトの種類に合わせて、name属性には以下のとおり指定する。
対応しました。

4c8de6718a3c2529a4d2c4a1eb09de3d04bc053e

2022-08-05 02:33 UTC, hiji commented on ja/application_framework/application_framework/web/architecture.rst
> +     - 例外の種類に応じたログ出力とレスポンスを生成する。
上記と同じく文章を見直しました。

16a08e4202856b28009812a65cd24cd8aea84e1c

2022-08-05 11:26 UTC, kumagoro1202 commented on ja/application_framework/application_framework/handlers/http_messaging/http_messaging_error_handler.rst
> +* 例外(エラー)に応じたログ出力とレスポンスを生成する。
「ログ出力を行う」はひっかかるのに「ログ出力を行**い**」だと引っかからないんですね。。。
https://github.com/nablarch/nablarch-document/pull/444/files#diff-1b840c2841e73e84576fb7890fbf0317af48f01de5c459de9937d06ad1b61629R71
こことかも引っかかってないですね。rstとの相性の問題ですかね

2022-08-05 11:28 UTC, kumagoro1202 commented on ja/application_framework/application_framework/handlers/http_messaging/http_messaging_error_handler.rst
> +* 例外(エラー)に応じたログ出力とレスポンスを生成する。
「ログ出力とレスポンスを生成する」系のやつは「ログを出力し、レスポンスを生成する」にしてもらうと自然かなと思いました。

2022-08-05 11:31 UTC, kumagoro1202 commented on ja/application_framework/application_framework/libraries/tag.rst
> +:ref:`フォームのサブミットを行うボタン/リンク<tag_reference_submit>` の表示を切り替える機能をする。
元に戻っていること確認しました。
https://github.com/nablarch/nablarch-document/commit/4c8de6718a3c2529a4d2c4a1eb09de3d04bc053e

2022-08-05 11:32 UTC, kumagoro1202 commented on ja/application_framework/application_framework/handlers/web/HttpErrorHandler.rst
> +後続のハンドラで発生した例外に対するログ出力やレスポンスへ変換するハンドラ。
https://github.com/nablarch/nablarch-document/pull/444#discussion_r938721564

2022-08-05 11:32 UTC, kumagoro1202 commented on ja/application_framework/application_framework/web/architecture.rst
> +     - 例外の種類に応じたログ出力とレスポンスを生成する。
https://github.com/nablarch/nablarch-document/pull/444#discussion_r938721564

2022-08-08 00:51 UTC, hiji commented on ja/application_framework/application_framework/handlers/http_messaging/http_messaging_error_handler.rst
> +* 例外(エラー)に応じたログ出力とレスポンスを生成する。
システム開発ガイドでも「を行う」は使っている場面があったため、対象ルールを無効化することにし、こちらは文章は元に戻しました。

355c7d1aca749b0321ca689214e17b4f01d10764

> 「ログ出力を行う」はひっかかるのに「ログ出力を行い」だと引っかからないんですね。。。
https://github.com/nablarch/nablarch-document/pull/444/files#diff-1b840c2841e73e84576fb7890fbf0317af48f01de5c459de9937d06ad1b61629R71
こことかも引っかかってないですね。rstとの相性の問題ですかね

（rstファイルはルールチェックがうまく効いていない箇所が多そうため、対応すると逆に差分が発生することもあったりで、rstでのtextlintは微妙な感じがあるなと感じております...）

2022-08-08 00:51 UTC, hiji commented on ja/application_framework/application_framework/handlers/web/HttpErrorHandler.rst
> +後続のハンドラで発生した例外に対するログ出力やレスポンスへ変換するハンドラ。
https://github.com/nablarch/nablarch-document/pull/444#discussion_r939749600

2022-08-08 00:51 UTC, hiji commented on ja/application_framework/application_framework/web/architecture.rst
> +     - 例外の種類に応じたログ出力とレスポンスを生成する。
https://github.com/nablarch/nablarch-document/pull/444#discussion_r939749600

2022-08-08 10:34 UTC, kumagoro1202 requested changes

2022-08-08 10:34 UTC, kumagoro1202 commented on ja/application_framework/application_framework/web/getting_started/project_update/index.rst
> +      を使用して一意キー検索をする。
ここも戻してほしいです。

2022-08-08 10:34 UTC, kumagoro1202 commented on ja/application_framework/example/index.rst
> +Exampleアプリケーションは、Apache Mavenを使用してアプリケーションをビルド、実行する。以下のページを参考に、Apache MavenのPCへのインストール及び設定すること。
後半部分は「インストール及び必要な設定を行うこと」に戻してほしいです。

2022-08-08 10:34 UTC, kumagoro1202 commented on ja/development_tools/ui_dev/doc/reference_jsp_widgets/event_listen.rst
> +  イベントバブリングやデフォルトアクションの停止させることが可能である。
「デフォルトアクション**を**停止させること」にしてほしいです。

2022-08-08 10:34 UTC, kumagoro1202 commented on ja/examples/03/index.rst
> +ユーザ検索をする業務アプリケーションのクラスとJSPを構成に含めている。
ここも戻してほしいです。

2022-08-08 10:34 UTC, kumagoro1202 commented on ja/examples/03/index.rst
> +     // "SELECT_USER_BY_CONDITION"は、ユーザ検索をするSELECT文に対するSQL_ID。
「ユーザを検索するSELECT文」にしてほしいです。

2022-08-08 10:34 UTC, kumagoro1202 commented on ja/examples/03/index.rst
> +ユーザ検索をする業務アプリケーションを実装例に解説する。
ここも「ユーザを検索する」にしてほしいです。

2022-08-08 23:42 UTC, hiji commented on ja/about_nablarch/versionup_policy.rst
> +    - 不具合対応、機能追加・変更をします。
対応しました。

bf827d0498ef97dfd908aba8ac0bf74c36023592

2022-08-08 23:42 UTC, hiji commented on ja/application_framework/adaptors/micrometer_adaptor.rst
> +  カスタムプロバイダでは、任意で設定した ``CloudWatchAsyncClient`` を構築して返すように ``provide()`` メソッドを実装する。
対応しました。

bf827d0498ef97dfd908aba8ac0bf74c36023592

2022-08-08 23:42 UTC, hiji commented on ja/application_framework/application_framework/libraries/database/database.rst
> +like検索をする
対応しました。

bf827d0498ef97dfd908aba8ac0bf74c36023592

2022-08-08 23:42 UTC, hiji commented on ja/examples/03/index.rst
> +     // "SELECT_USER_BY_CONDITION"は、ユーザ検索をするSELECT文に対するSQL_ID。
対応しました。

bf827d0498ef97dfd908aba8ac0bf74c36023592

2022-08-08 23:42 UTC, hiji commented on ja/examples/03/index.rst
> +ユーザ検索をする業務アプリケーションを実装例に解説する。
対応しました。

bf827d0498ef97dfd908aba8ac0bf74c36023592

2022-08-08 23:45 UTC, hiji commented on ja/examples/03/index.rst
> +DbAccessSupportは、一覧検索用に検索するsearchメソッドを提供する。\
「～を行う」は除外しましたが「～を実行する」は現在除外しておらず、他の箇所でも言い換えをしていました。
「検索を実行」と「検索を行う」はそれほど変わりなように思ったので、「一覧検索用の検索を行うsearchメソッドを提供する。」に修正してみました。
違和感あるようでしたら、「～を実行する」ルールをここだけ除外、もしくは「～を行う」と同じく全体ルールとして除外しようと思いますので、ご指摘お願いします。

bf827d0498ef97dfd908aba8ac0bf74c36023592

2022-08-08 23:45 UTC, hiji commented on ja/examples/03/index.rst
> +ページングを使用する場合と同じ、ユーザ検索をする業務アプリケーションのクラスやJSPを実装例に使用する。
対応しました。

bf827d0498ef97dfd908aba8ac0bf74c36023592

2022-08-08 23:45 UTC, hiji commented on ja/examples/03/index.rst
> +ページングを使用する場合と同じ、ユーザ検索する業務アプリケーションのクラスやJSPを実装例に使用する。
対応しました。

bf827d0498ef97dfd908aba8ac0bf74c36023592

2022-08-09 04:14 UTC, kumagoro1202 commented on ja/examples/03/index.rst
> +ページングを使用する場合と同じ、ユーザ検索をする業務アプリケーションのクラスやJSPを実装例に使用する。
「ユーザを検索をする」と「を」が重複しています。

2022-08-09 04:26 UTC, hiji commented on ja/application_framework/application_framework/web/getting_started/project_update/index.rst
> +      を使用して一意キー検索をする。
対応しました。

e0f0f46aaa5e5044b800bdcaba80ec0a84b8b60e

2022-08-09 04:27 UTC, hiji commented on ja/application_framework/example/index.rst
> +Exampleアプリケーションは、Apache Mavenを使用してアプリケーションをビルド、実行する。以下のページを参考に、Apache MavenのPCへのインストール及び設定すること。
対応しました。

e0f0f46aaa5e5044b800bdcaba80ec0a84b8b60e

2022-08-09 04:27 UTC, hiji commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/03_DealUnitTest/send_sync.rst
> +モックアップクラスを使用すればキューを用意する必要がなくなるので、特別なミドルウェアのインストールや環境設定などを準備することなく、取引単体テストを行うことができる。
対応しました。

e0f0f46aaa5e5044b800bdcaba80ec0a84b8b60e

2022-08-09 04:27 UTC, hiji commented on ja/development_tools/ui_dev/doc/reference_jsp_widgets/event_listen.rst
> +  イベントバブリングやデフォルトアクションの停止させることが可能である。
対応しました。

e0f0f46aaa5e5044b800bdcaba80ec0a84b8b60e

2022-08-09 04:27 UTC, hiji commented on ja/examples/03/index.rst
> +ユーザ検索をする業務アプリケーションのクラスとJSPを構成に含めている。
対応しました。

e0f0f46aaa5e5044b800bdcaba80ec0a84b8b60e

2022-08-09 05:36 UTC, kumagoro1202 approved these changes

2022-08-09 05:37 UTC, merged