DB接続無しのバッチアプリケーション説明を追加（英語版）
nablarch/nablarch-document pull request #446
Opened 2022-08-26 05:49 UTC by hiji

2022-08-26 06:34 UTC, kumagoro1202 requested changes

2022-08-26 06:34 UTC, kumagoro1202 commented on en/application_framework/application_framework/blank_project/MavenModuleStructures/index.rst
日本語版でも見落としていましたが、Description is omittedと言いながらdescription書いちゃってますね。

2022-08-26 08:34 UTC, hiji commented on en/application_framework/application_framework/blank_project/MavenModuleStructures/index.rst
日本語版、英語版ともに構成説明を省略するように見直しました。

05a2ad4c9ac65dc7b04cc5d155afbffca2c3e05f

2022-08-29 02:45 UTC, hiji commented
除外ルールで囲っていたところがHTMLに出力されていなかったので、書き方を修正しました。
8daa5a8e1392ceef26caedce7e697a26246355a9

除外ルールで囲っていたところがHTMLに出力されていなかったので、書き方を色々と試してみたが、Textlintのエラーは発生させずにHTMLも正しく出力させる方法が見つけられなかった。仕方ないので、文章の末尾の言い換えて対応しました。
75cdab3e4c3957751c55217e12c815a7c8bbdebe

ページ内リンクが正しく動作していなかたったため、修正しました。
b2766b8a2b82b7b81bba95bdfc2cca3f1d33ebba

以前に取引単体テストを修正した際に、ページ最後尾の脚注を消してしまっていたようで、番号やリンクがズレていました。元に戻したのと同時に、ページ最後尾にありますがページ最初で参照していたので位置も移動させました。
2afff075d6a0cfa3e0069c189af4cb33e43a3156

2022-08-29 05:55 UTC, kumagoro1202 approved these changes

2022-08-29 05:55 UTC, merged