Feature nab 507/replace authentication
nablarch/nablarch-document pull request #459
Opened 2023-01-17 06:34 UTC by sukegawatakashitis

### 変更内容

以下の日本語、英語の実装説明内容を修正しました。
・nablarch-document/ja/examples/01

2023-01-17 10:08 UTC, kumagoro1202 requested changes

2023-01-17 10:08 UTC, kumagoro1202 commented on ja/examples/01/index.rst
> +                                                                         PasswordAuthenticatorのトランザクション制御が個別アプリケーションの処理に影響を与えないように、個別アプリケーションとは別のトランザクションを使用するように設定すること。
SystemAccountAuthenticatorのトランザクション制御ではないですか。

2023-01-17 10:08 UTC, kumagoro1202 commented on ja/examples/01/index.rst
> +    </component>
SystemAccountAuthenticatorの使用方法が2回書かれています。

2023-01-17 10:08 UTC, kumagoro1202 commented on ja/examples/01/index.rst
>    =============================== ==========================================================================
実装例に入っているSystemAccountは仮で、プロジェクトでGSPプラグインで自動生成したものを使うようにという注意書きを入れましょうという話が盛り込まれていません。

2023-01-19 00:31 UTC, sukegawatakashitis commented on ja/examples/01/index.rst
> +  Nablarch 5系より新しいNablarchと組み合わせる場合は、必要に応じてカスタマイズすること。
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/459/commits/9e0cb222f0bd9e1813d7aeabe237379bf3c90312

2023-01-19 01:11 UTC, opengl-8080 requested changes

2023-01-19 01:11 UTC, opengl-8080 commented on ja/examples/01/_images/Authentication_ClassDiagram.pu
> +@enduml
旧仕様ではシステム日時を `SystemTimeProvider` で取得するようになっており、そのことが図でも表現されていました。
新仕様ではシステム日時を `SystemTimeUtil` を使って取得するようになっているようですが、そのことが図から削除されていますが、それでいいのでしょうか？

（`SystemTimeUtil` の記載も必要であれば、「各クラスの責務」の方にも追加が必要になると思います）

2023-01-19 01:57 UTC, sukegawatakashitis commented on ja/examples/01/index.rst
>    ユーザIDロック            USER_ID_LOCKED            java.lang.String     ロックしていない場合は"0"、ロックしている場合は"1"
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/459/commits/19bd81f0f5d196131ad1591a5bdebf0459fb1046

2023-01-19 02:17 UTC, sukegawatakashitis commented on ja/examples/01/index.rst
> +    </component>
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/459/commits/c1f5f8a0ded675a573d87ac2142dbb40f6dad118

2023-01-19 02:25 UTC, sukegawatakashitis commented on ja/examples/01/index.rst
> +    <component name="authenticator" class="please.change.me.common.authentication.SystemAccountAuthenticator">
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/459/commits/3986808424e289cf6f10eef385a686265911dd13

テスト用のコンポーネント定義はこちらで修正PRを作成しました。
https://github.com/nablarch/nablarch-biz-sample-all/pull/12

2023-01-19 02:28 UTC, sukegawatakashitis commented on ja/examples/01/index.rst
> +                                                                         PasswordAuthenticatorのトランザクション制御が個別アプリケーションの処理に影響を与えないように、個別アプリケーションとは別のトランザクションを使用するように設定すること。
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/459/commits/726e82ce047a36446c82cb9cfa59f29ae9f75cc1

2023-01-19 03:04 UTC, sukegawatakashitis commented on ja/examples/01/index.rst
>    =============================== ==========================================================================
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/459/commits/a917affe09475569906762cc07dba9c42778a04a

2023-01-19 05:38 UTC, sukegawatakashitis commented on ja/examples/01/_images/Authentication_ClassDiagram.pu
> +'hide circle
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/459/commits/52aff82657b58c50058524ba5e7b7248e84309e1

2023-01-19 05:39 UTC, sukegawatakashitis commented on ja/examples/01/_images/Authentication_ClassDiagram.pu
> +        + setVersion(version: Long): void
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/459/commits/e33f9d42afac913abcb72b55f66d7c7265bf5560

2023-01-19 05:39 UTC, sukegawatakashitis commented on ja/examples/01/_images/Authentication_ClassDiagram.pu
> +AuthenticationUtil ..> SystemAccountAuthenticator : use
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/459/commits/5f352b51a8af9c71d5f22cc76080b53c1377f0f9

2023-01-19 05:40 UTC, sukegawatakashitis commented on ja/examples/01/_images/Authentication_ClassDiagram.pu
> +AuthenticationUtil ..> PasswordAuthenticator : use
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/459/commits/46aa316166c7ca328a826c9a82ed8f338fead10b

2023-01-19 05:41 UTC, sukegawatakashitis commented on ja/examples/01/_images/Authentication_ClassDiagram.pu
> +SystemAccountAuthenticator ..> UniversalDao : use
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/459/commits/c3bd7233205311df1026e062f7fa60daeb137ac2

2023-01-19 05:41 UTC, sukegawatakashitis commented on ja/examples/01/_images/Authentication_ClassDiagram.pu
> +skinparam classAttributeIconSize 0
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/459/commits/9d2ed46e2fd33e883dfa8da27ade89eba9731746

2023-01-19 05:42 UTC, sukegawatakashitis commented on ja/examples/01/_images/Authentication_ClassDiagram.pu
> +    class RuntimeException <<not sample>>
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/459/commits/f98f6fff98c952f5e5ef3dc7682e3e00665ebffe

2023-01-19 05:42 UTC, sukegawatakashitis commented on ja/examples/01/_images/Authentication_ClassDiagram.pu
> +    {static} + findBySqlFile(entityClass: Class<T>, sqlId: String, params: Object): T
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/459/commits/086a77431031062f15cb9d4ffe0afde7386232c2

2023-01-19 05:43 UTC, sukegawatakashitis commented on ja/examples/01/_images/Authentication_ClassDiagram.pu
> +@enduml
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/459/commits/ac0ec3d935cd16ec23a2794b50fb14ada7082d24

2023-01-19 06:01 UTC, kumagoro1202 commented on ja/examples/01/index.rst
>    ユーザIDロック            USER_ID_LOCKED            java.lang.String     ロックしていない場合は"0"、ロックしている場合は"1"
細かい話ですがtrueの条件を先に書くほうが理解しやすいと思います。
それから元はStringだから0と1という風にロックしている/していない場合に取る値を記載する必要がありますが真偽値なのでtrueかfalseの2値しかありえません。「ロックしている場合はtrue」だけでいいと思います。

2023-01-19 06:10 UTC, sukegawatakashitis commented on ja/examples/01/index.rst
>    ユーザIDロック            USER_ID_LOCKED            java.lang.String     ロックしていない場合は"0"、ロックしている場合は"1"
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/459/commits/5a776d73cf17d0c307fccf78754bb48f9dd358ca

2023-01-19 06:17 UTC, kumagoro1202 commented on ja/examples/01/index.rst
>    =============================== ==========================================================================
言葉が少なすぎて何のことかこれでは伝わりません。

まず、どういう前提をおいているのか（データベースに合わせたentityクラスはgsp-dba-maven-plugin(DBA作業支援ツール)を使って生成する）、その前提に対してこのサンプルがどう乖離しているのか（仮としてテーブル定義に記載した構造のテーブルから自動生成した体でentityクラスをおいている）、だから利用者は何をしないといけないのか（実装例に含まれているentityではなく自プロジェクトで生成したentityを使用する）を書いてください。
↑のカッコ内はイメージとして記載したものです。この言葉をそのまま繋いで修正しましたと言ってこないでくださいね。
また、GSPプラグインという呼び名は便宜上チーム内で通じるから使っているだけで、解説書にはそのような呼び方をしているところはありません。以下のページではgsp-dba-maven-plugin(DBA作業支援ツール)と記載しているので言葉を合わせてください。
https://nablarch.github.io/docs/LATEST/doc/application_framework/application_framework/blank_project/addin_gsp.html

2023-01-19 06:18 UTC, kumagoro1202 commented on ja/examples/01/_images/Authentication_ClassDiagram.pu
> +@enduml
各クラスの責務には実装例に含まれるクラスだけを記載しているのでSystemTimeUtilを記載する必要はないと思います。

2023-01-19 06:23 UTC, kumagoro1202 commented
0101_PBKDF2PasswordEncryptor.rstがまったく修正されていません。こちらも見直してください。

2023-01-19 07:09 UTC, opengl-8080 commented on ja/examples/01/_images/Authentication_ClassDiagram.pu
> +@enduml
すみません、私の勘違いです。

「PasswordAuthenticatorの使用方法」のところから `SystemTimeProvider` の説明を除去している修正を、「各クラスの責務」の修正と勘違いしていました。

> （SystemTimeUtil の記載も必要であれば、「各クラスの責務」の方にも追加が必要になると思います）

この分は取り下げます。
お手数ですが、「各クラスの責務」に追加した修正は削除してください。

2023-01-19 07:18 UTC, sukegawatakashitis commented on ja/examples/01/_images/Authentication_ClassDiagram.pu
> +@enduml
こちらで記載を削除しました。https://github.com/nablarch/nablarch-document/pull/459/commits/d11b3bcc225efb2b179c7d33bef8aed754c3640a

2023-01-19 08:29 UTC, sukegawatakashitis commented on ja/examples/01/index.rst
>    =============================== ==========================================================================
説明足らず申し訳ございません。
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/459/commits/2d9aae32b291d6855686ed045c8a30e59f1e2ea1

2023-01-19 09:30 UTC, sukegawatakashitis commented
> 0101_PBKDF2PasswordEncryptor.rstがまったく修正されていません。こちらも見直してください。

こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/459/commits/de602ca06b10b25e7334e280b238187556a7070c

2023-01-19 11:15 UTC, kumagoro1202 commented on ja/examples/01/index.rst
>    =============================== ==========================================================================
1. 文体はページの中で統一してください。このページはですます調ではなくである調になっています。
2. 同じものを指す言葉が表記ゆれしないよう注意してください。エンティティクラスかEntityクラスか統一してください。
3. ページ内や関連ページへのハイパーリンクを適宜入れてください。

テーブル定義のセクションにsystem-account-table-definitionというラベルをつけた前提で以下のようにするのでどうでしょう。

```
  Nablarch導入プロジェクトでは、エンティティクラスは :ref:`gsp-dba-maven-plugin(DBA作業支援ツール) <gsp-maven-plugin>` を使用して自動生成する。
  本サンプルには動作確認のため :ref:`system-account-table-definition` に記載の定義に合わせて自動生成したエンティティクラスを同梱している。
  プロジェクトにて実装する際は本サンプルのエンティティクラスを使用するのではなく、各プロジェクトで自動生成したエンティティクラスを使用するよう修正すること。
```

2023-01-19 11:21 UTC, kumagoro1202 requested changes

2023-01-19 11:21 UTC, kumagoro1202 commented on ja/examples/01/0101_PBKDF2PasswordEncryptor.rst
> +  *please.change.me.*\ **common.authentication.encrypt**
設定方法に記載のコンポーネント定義でパッケージがplease.change.me.common.authentication.PBKDF2PasswordEncryptorのままです。

2023-01-20 00:42 UTC, opengl-8080 commented on ja/examples/01/_images/Authentication_ClassDiagram.pu
> +@enduml
> >（SystemTimeUtil の記載も必要であれば、「各クラスの責務」の方にも追加が必要になると思います）
> この分は取り下げます。

取り下げたのは「各クラスの責務」に `SystemTimeUtil` の説明を追加することだけで、 UML に `SystemTileUtil` を追加する話までは取り下げていません。

2023-01-20 00:52 UTC, sukegawatakashitis commented on ja/examples/01/index.rst
>    =============================== ==========================================================================
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/459/commits/3375048cb6ec42ce0b0bdfb25533132cd5fed96d

2023-01-20 01:02 UTC, sukegawatakashitis commented on ja/examples/01/_images/Authentication_ClassDiagram.pu
> +@enduml
すみません。こちらのPRで、UML に SystemTileUtil を追加しました。
https://github.com/nablarch/nablarch-document/pull/459/commits/8dbe02a3cf9b242975f175c1919c0725962b73af

2023-01-20 01:08 UTC, sukegawatakashitis commented on ja/examples/01/0101_PBKDF2PasswordEncryptor.rst
> +  *please.change.me.*\ **common.authentication.encrypt**
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/459/commits/c33c670e98cf8692bc6e2767c942482562984e63

2023-01-20 01:27 UTC, kumagoro1202 approved these changes

2023-01-20 01:28 UTC, merged