実装例集：検索結果の一覧表示：実装説明修正
nablarch/nablarch-document pull request #461
Opened 2023-01-30 02:04 UTC by sukegawatakashitis

### 変更内容

以下の日本語の実装説明内容を修正しました。
・nablarch-document/ja/examples/03

2023-01-30 02:57 UTC, kumagoro1202 requested changes

2023-01-30 02:57 UTC, kumagoro1202 commented on ja/examples/03/index.rst
> +タグ関連図
この行ではなく24行目に対する指摘です。

> タグファイルは、フレームワークが提供する一覧検索用の検索機能と連携して、次の機能を提供する。

とありますが、「一覧検索用の検索機能」というのは古い方式です。新しい方式はユニバーサルDAOの検索機能を前提としているので

> タグファイルは、ユニバーサルDAOの検索機能と連携して、次の機能を提供する。

としてユニバーサルDAOをリンクにしてください。

2023-01-30 02:57 UTC, kumagoro1202 commented on ja/examples/03/index.rst
> +タグ関連図
この行ではなく32行目の図に対する指摘です。

並べ替え用の列見出しのリンクの吹き出しだけ外してよしとしていますが、図の列見出しがリンクになっているので整合性が取れていません。きちんと今のタグファイルで描画した一覧に差し替えてください。

2023-02-02 07:45 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +タグ関連図
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/f498dcf8467916296f3f1c084e50b6c07c39b2ca

2023-02-02 07:47 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +タグ関連図
こちらで描画し直した画像に差し替え、修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/fc1482ddbfc63a66cd8c95bb44dec7785205e004

2023-02-03 02:37 UTC, kumagoro1202 requested changes

2023-02-03 02:37 UTC, kumagoro1202 commented on ja/examples/03/index.rst
> +ページングを使用する場合と同じ、プロジェクトを全件検索する業務アプリケーションの検索処理やJSPを実装例に使用する。
1画面にすべての検索結果を表示する方法は特別なものじゃなく、単に返却するリストを取得する際にページングの指定をしないだけなので、こういう書き方は不適切です。元の方式で1画面にすべての検索結果を表示する方法がアナウンスされていたのはDbAccessSupportを使うとデフォルトで1ページの表示件数や最大件数が設定されてしまうからそれを回避する方法を案内する必要があったからです。
新しい方式ではあえて取り上げる必要はないと思います。

2023-02-03 02:37 UTC, kumagoro1202 commented on ja/examples/03/index.rst
> +検索画面の初期表示にて、デフォルトの検索条件で検索した結果を表示することが求められる場合、デフォルトの検索条件を指定し、\
これも古い方式ではウィンドウスコープへの設定というひと手間をかける必要があるので書いていたものと考えられます。新しい方式では初期表示で検索結果を出すのもリクエストを受けて出すのもやることは同じなので取り上げる必要はないと思います。

2023-02-03 02:37 UTC, kumagoro1202 commented on ja/examples/03/index.rst
ここを消しているのに冒頭の説明が消えていません。

> 業務アプリケーションへサンプル実装(タグファイル)を取り込む場合は、下記の手順で実施する。
> * 業務アプリケーションへタグファイルの配置
> * タグファイル内のプレフィックスの修正

2023-02-03 02:37 UTC, kumagoro1202 commented on ja/examples/03/index.rst
>  :ref:`ListSearchResult_Tag`                            検索結果の一覧表示を行う。
1個しか無いのに表にする意味がないです。リンク押したところで1行下に飛ぶだけでこの表を配置することで何も嬉しくならないです。

2023-02-03 02:37 UTC, kumagoro1202 commented on ja/examples/03/index.rst
> +showResult                             検索結果を表示するか否か。デフォルトはtrue。
showResultというフラグを入れたことでheaderRowFragment、bodyRowFragmentは必須ではなくなっています。

2023-02-03 02:39 UTC, kumagoro1202 commented on ja/examples/03/index.rst
> +java.util.ArrayListクラスを継承し、Paginationクラスのインスタンスをフィールドに持つ。
pageNumberを受け取るFormの実装についての解説がないのもおかしい。ページングを動かす場合はFormにpageNumberという属性を持たせて受け取らないといけない。

2023-02-03 03:00 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +  UniversalDao                    汎用的なDAO機能を提供するクラス。基本的な使い方は、 :java:extdoc:`nablarch.common.dao.UniversalDao` を参照。
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/413ea2dd48c0cbbc88305ad7959296bd120643bc

2023-02-03 04:54 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +UniversalDaoクラスは、SQLファイルを使用した検索を実行する :java:extdoc:`findAllBySqlFile <nablarch.common.dao.UniversalDao.findAllBySqlFile(java.lang.Class-java.lang.String-java.lang.Object)>` メソッドを提供する。\
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/f44160d71360f28ce7256f4e34bec280332703f0

2023-02-03 05:52 UTC, zuga commented on ja/examples/03/index.rst
> +java.util.ArrayListクラスを継承し、Paginationクラスのインスタンスをフィールドに持つ。
> ここではなくlistSearchResultタグの説明に対する指摘。
> 
> 現在listSearchInfoNameという名前の属性を定義しているが、実態はFormクラスの名前で用途はlistSearchSubmit.tagにおいてpageNumberをセットすることにしか使われていない。混乱の元なので名前を見直した方がいい。

こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/4d8a8fb8d83619f51d9699ab1b7780b0bce0a54e

2023-02-03 06:52 UTC, zuga commented on ja/examples/03/index.rst
> +java.util.ArrayListクラスを継承し、Paginationクラスのインスタンスをフィールドに持つ。
> ここではなくlistSearchResultタグの説明に対する指摘。
> 
> 現在listSearchInfoNameという名前の属性を定義しているが、実態はFormクラスの名前で用途はlistSearchSubmit.tagにおいてpageNumberをセットすることにしか使われていない。混乱の元なので名前を見直した方がいい。

こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/dffcd5c0c04900fef0fa57bd4c59e68cca0ab091

2023-02-03 06:54 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +java.util.ArrayListクラスを継承し、Paginationクラスのインスタンスをフィールドに持つ。
> ここではなくlistSearchResultタグの説明に対する指摘。
> 
> 現在listSearchInfoNameという名前の属性を定義しているが、実態はFormクラスの名前で用途はlistSearchSubmit.tagにおいてpageNumberをセットすることにしか使われていない。混乱の元なので名前を見直した方がいい。

こちらで修正しました。
https://github.com/nablarch/nablarch-document/pull/461/commits/dffcd5c0c04900fef0fa57bd4c59e68cca0ab091

2023-02-03 07:04 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +java.util.ArrayListクラスを継承し、Paginationクラスのインスタンスをフィールドに持つ。
> ここではなくlistSearchResultタグの説明に対する指摘。
> 
> 現在listSearchInfoNameという名前の属性を定義しているが、実態はFormクラスの名前で用途はlistSearchSubmit.tagにおいてpageNumberをセットすることにしか使われていない。混乱の元なので名前を見直した方がいい。

こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/dffcd5c0c04900fef0fa57bd4c59e68cca0ab091

2023-02-03 08:45 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +resultSetNameで取得した、ユニバーサルDAOの検索結果から、Paginationを変数に保存し、変数からresultCountプロパティを取得すること。
利用者に不要な記述を削除しました。resultCountFragmentの説明を修正しました。
https://github.com/nablarch/nablarch-document/pull/461/commits/793acabe87450c09d149f01ae2fe0c75226f8f44

2023-02-03 09:40 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +resultSetNameで取得した、ユニバーサルDAOの検索結果から、Paginationを変数に保存し、変数からresultCountプロパティを取得すること。
resultCountFragmentでJSPフラグメントを指定したい場合の説明を修正しました。
https://github.com/nablarch/nablarch-document/pull/461/commits/9e45d6f3c0e830f237573281c06720eb4226f2c9

2023-02-03 09:42 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +      [サーチ結果 <n:write name="searchResult.pagination.resultCount" />頁]
見直しがきちんとできていませんでした。こちらで修正しました。
https://github.com/nablarch/nablarch-document/pull/461/commits/9e45d6f3c0e830f237573281c06720eb4226f2c9

2023-02-03 09:48 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +ページングを使用する場合と同じ、プロジェクトを全件検索する業務アプリケーションの検索処理やJSPを実装例に使用する。
こちらで削除しました。https://github.com/nablarch/nablarch-document/pull/461/commits/9cc1d03d6818c5d614126c679933de06e44c1334

2023-02-03 09:48 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +検索画面の初期表示にて、デフォルトの検索条件で検索した結果を表示することが求められる場合、デフォルトの検索条件を指定し、\
こちらで削除しました。https://github.com/nablarch/nablarch-document/pull/461/commits/9cc1d03d6818c5d614126c679933de06e44c1334

2023-02-03 10:02 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/0298f03bb858f2b2bd8c78818235fbf9252e37ef
見直し足りてませんでした。すみません。

2023-02-06 00:43 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
>  :ref:`ListSearchResult_Tag`                            検索結果の一覧表示を行う。
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/a1b384cb3c26e403bb91ced8a48262477c020181

2023-02-06 00:44 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +showResult                             検索結果を表示するか否か。デフォルトはtrue。
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/3af4b3b5dbf4252e80edc9ceb578d8d60472291a

2023-02-06 01:36 UTC, kumagoro1202 commented on ja/examples/03/index.rst
> +UniversalDaoクラスは、SQLファイルを使用した検索を実行する :java:extdoc:`findAllBySqlFile <nablarch.common.dao.UniversalDao.findAllBySqlFile(java.lang.Class-java.lang.String-java.lang.Object)>` メソッドを提供する。\
> 指定されたSQL_IDとバインド変数から、検索を実行する。
SQL_IDで指定するSQL文は、業務に必要な検索条件を基に検索するSQL文(つまりSELECT文)を指定する。SQL文を基にした検索結果の件数取得や検索結果の開始位置と取得件数を指定した検索は、フレームワークで行う。
取得するページ数の指定と、1ページにつき何件取得するかを指定可能。
検索結果を保持したエンティティクラスオブジェクトのリストを返す。

これをこのページで説明する必要性がわからないです。
UniversalDaoでは複数件の検索結果をEntityListとして返すAPIを持つ。ページング機能を使う際は、UniversalDaoのページングを行うを参照。
だけでいいと思います。ここでfindAllBySqlFileがSQL_IDとバインド変数を使って云々というのを記載する必要はないと思います。フレームワークがやることで利用者が意識する必要がないことなので。
利用者に知ってもらうべきなのは一覧表示に使うリストはEntityListであることとページングはUniversalDaoのAPI使えばよしなに設定されて表示がうまくいくということです。

2023-02-06 01:37 UTC, kumagoro1202 commented on ja/examples/03/index.rst
> +java.util.ArrayListクラスを継承し、Paginationクラスのインスタンスをフィールドに持つ。
> pageNumberを受け取るFormの実装についての解説がないのもおかしい。ページングを動かす場合はFormにpageNumberという属性を持たせて受け取らないといけない。

これが対応されていない。

2023-02-06 01:47 UTC, kumagoro1202 commented on ja/examples/03/index.rst
下記の手順で実施する。で、手順の全体像がないまま業務アプリケーションへタグファイルの配置というセクションがくると手順がどこまでなのかわからず混乱します。

下記の手順で実施する。というのは手順が複数ある場合に成立する書き方だと思います。
業務アプリケーションへサンプル実装を取り込む場合は、下記の通り、listSearchResultパッケージを業務アプリケーションに配置する。だけにして「業務アプリケーションへタグファイルの配置」という見出しは必要ないと思います。

2023-02-06 01:49 UTC, kumagoro1202 commented on ja/examples/03/index.rst
> +resultSetNameで取得した、ユニバーサルDAOの検索結果から、Paginationを変数に保存し、変数からresultCountプロパティを取得すること。
口頭で話した通りpaginationのスコープを広げるのは危険なので上記は撤回し、paginationはJSPフラグメントを記載する際resultSetから取り出して指定する。

2023-02-06 02:00 UTC, kumagoro1202 requested changes

2023-02-06 02:37 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +UniversalDaoクラスは、SQLファイルを使用した検索を実行する :java:extdoc:`findAllBySqlFile <nablarch.common.dao.UniversalDao.findAllBySqlFile(java.lang.Class-java.lang.String-java.lang.Object)>` メソッドを提供する。\
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/1dbf3d4147180e4f1e3b481743dbea879af624d6

2023-02-06 02:57 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +resultSetNameで取得した、ユニバーサルDAOの検索結果から、Paginationを変数に保存し、変数からresultCountプロパティを取得すること。
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/dfbba3d3c20bf6a532125c89de68b70464a0d256

2023-02-06 04:43 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +java.util.ArrayListクラスを継承し、Paginationクラスのインスタンスをフィールドに持つ。
失礼しました。こちらで対応しました。https://github.com/nablarch/nablarch-document/pull/461/commits/c99aa1ba5c9a507e7b670e6c6af4210fcb8d0027

2023-02-06 04:53 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +現在のページ番号                          現在のページ番号は常に表示される。
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/2b431cb1a996dc1fbc8c2711173061dccdd567db

2023-02-06 04:53 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +前のページへ、次のページへ                  現在のページ番号から各画面要素が示すページに遷移可能な場合は、サブミット可能な状態で表示される。遷移不可の場合は、リンクであればラベル、ボタンであれば使用不可な状態で表示される。
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/9bdff0f42ac1c6eb9e3d71cdca711cb15a42fad5

2023-02-06 06:02 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +前のページへ、次のページへ                  現在のページ番号から各画面要素が示すページに遷移可能な場合は、サブミット可能な状態で表示される。遷移不可の場合は、リンクであればラベル、ボタンであれば使用不可な状態で表示される。
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/c6b21786e2af8d54be0df5130c77d3e9e6493d2d

2023-02-06 07:51 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +また、検索条件を変更した場合には、検索処理が再実行され、検索結果一覧の最初のページを表示する。
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/532b259faba526d73a8dc1a101432aa2dcf4d2b5

2023-02-06 08:10 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +                <n:a href="/action/project/show/${row.projectId}">
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/300c001e40ede6ab6dde1be60790e08ef1f15bdd

2023-02-06 08:18 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/7d724a9a054ee852b06aea85880952486933bd13

2023-02-06 08:19 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +タグファイルは、:ref:`universal_dao` の検索機能と連携して、次の機能を提供する。
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/25ee1d3f18af68d5ceea507573ba1eed9c063434

2023-02-06 09:05 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
>  一覧画面の出力例を示す。
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/a170628c0431e554f7142c4210594ab9071bc24f

2023-02-06 09:09 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +  ListSearchInfo                  一覧検索用の情報を保持する基底クラス。
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/71d80641dbdd107554ed44553b57cc8e65f36102

2023-02-06 09:10 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +  Pagination                      ページネーションのための値をもつクラス。
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/25447f16f86409f999ca0fc48036d3524ff4e8f4

2023-02-06 09:19 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +ページングについての詳細は、:ref:`こちら <universal_dao-paging>` を参照。
以下の対応で、UniversalDaoクラスの説明配下に配置しました。
https://github.com/nablarch/nablarch-document/pull/461#discussion_r1096893714

2023-02-06 09:25 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +         .page(searchCondition.getPageNumber()) // ページ数を指定
ユニバーサルDAOの
[ページングを行う](https://nablarch.github.io/docs/LATEST/doc/application_framework/application_framework/libraries/database/universal_dao.html#universal-dao-paging)
にリンクするように修正し、本ページからは削除しました。

2023-02-06 09:27 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +ListSearchInfoクラスは、一覧検索用の情報を保持する基底クラスである。
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/4913a5a176ad86eb22703807826ebce7320ea55a

2023-02-06 09:52 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> + <nbs:listSearchResult resultSetName="searchResult">
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/9ce79021fab60750cdb2f23c3cd670dbd8a056b6

2023-02-06 09:52 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> + <nbs:listSearchResult resultSetName="searchResult" useResultCount="true">
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/9ce79021fab60750cdb2f23c3cd670dbd8a056b6

2023-02-07 05:20 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +searchFormName                         searchFormをリクエストスコープから取得する際に使用する名前。|br|
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/bd0c1b6546e53d3f16aa07cb4927b5100a0a93d9

2023-02-07 08:00 UTC, kumagoro1202 requested changes

2023-02-07 08:16 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +フォームクラスについては、 :ref:`application_design` を参考にすること。
フォームクラスについての参考になるかと考えていましたが、あらためて読み返すと不要な案内であり、かつ利用者を混乱させると思いますので、削除しました。
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/85fec21a107ee3816081b28913c84ec86957b76b

2023-02-07 08:20 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +フォームクラスについては、 :ref:`application_design` を参考にすること。
「検索フォームを受け取り、～」で伝わるかと思いますので、
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/377568d965e4cb1f3a1f5c247d954a057ea07a90

2023-02-07 08:32 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +searchFormName                         検索フォームをリクエストスコープから取得する際に使用する名前。|br|
こちらで修正しました。
https://github.com/nablarch/nablarch-document/pull/461/commits/13ac165f56473a025145de6da48cfce11d0fa43b
https://github.com/nablarch/nablarch-document/pull/461/commits/1c12aaa8dbf78ee54f687ea187c9563277140245

2023-02-07 08:37 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +  JSPフラグメントから検索結果件数にアクセスするときは、resultSetNameで取得したユニバーサルDAOの検索結果の中のpaginationからresultCountプロパティを取得すること。
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/b4bfafb2c6dc32a9b4b3b8eb6e86af811ae9c4d1

2023-02-07 08:37 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> + [サーチ結果 <%-- resultSetのpaginationのresultCountプロパティ --%>件]
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/9da934c97caf584ff4c00a95acf6114327d76f59

2023-02-07 08:42 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +ページング機能を使用する場合、フォームにpageNumberの名前の属性およびアクセッサを定義すること。
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/bec832f0547e38e49ac1b5a7349a1a1d26b27deb

2023-02-07 08:45 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +最初、前へ、次へ、最後                     現在のページ番号から各画面要素が示すページに遷移可能な場合は、サブミット可能な状態で表示される。遷移不可の場合はラベルで表示される。「最初」はuseFirstSubmit属性にtrueを指定した場合に表示され、「最後」はuseLastSubmit属性にtrueを指定した場合に表示される。
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/39feeeb42dc23d881838c14aeb9c3aa00a80fd0c

2023-02-07 08:48 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +* 各画面要素のラベル(最初、次へなど)
こちらで元に戻しました。
https://github.com/nablarch/nablarch-document/pull/461/commits/3320a1aa070ab4f88f47a56b0a1a6198eda6ce33

2023-02-07 08:53 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +次へ、最後                               現在2ページ目で検索結果が10件のため、次へ、最後のページに遷移不可となりラベルで表示される。
こちらで元に戻しました。
https://github.com/nablarch/nablarch-document/pull/461/commits/dd65b874fa71907a1667ae49eda3895a1e409e16

2023-02-07 08:59 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +    private String pageNumber;
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/6278b8635b70bf0da9c6263b406cf11d13fca28a

2023-02-07 11:56 UTC, kumagoro1202 commented on ja/examples/03/index.rst
> +フォームクラスについては、 :ref:`application_design` を参考にすること。
そういう意味じゃなく、検索フォームを受け取り、resultSetName属性で指定された検索結果を表示するという文章全体がここにあることに違和感があるという意味です。
[listSearchResultタグ](https://github.com/nablarch/nablarch-document/pull/461#listsearchresult-tag) は、検索結果のリストを表示するタグである。 listSearchResultタグで出力する画面要素を下記に示す。
だけでいいと思います。
下のlistSearchResultタグの主要な属性の方にsearchFormNameとかresultSetNameとかは出てくるのでここで触れるべきではないという意味です。

2023-02-07 12:11 UTC, kumagoro1202 requested changes
526行目にPagingInfoという古い属性の表記が残っている。

2023-02-09 00:30 UTC, sukegawatakashitis commented on ja/examples/03/index.rst
> +フォームクラスについては、 :ref:`application_design` を参考にすること。
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/61db33ff8027f5cfdb1012812c9ffee719033915

2023-02-09 00:32 UTC, sukegawatakashitis commented
> 526行目にPagingInfoという古い属性の表記が残っている。

こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/461/commits/a9d12291129eea9dd4860cef7d59d60619f88eec

2023-02-09 04:25 UTC, kumagoro1202 approved these changes

2023-02-09 04:25 UTC, merged