OIDCのIDトークンを用いた認証サンプルを実装例集に追加
nablarch/nablarch-document pull request #462
Opened 2023-01-31 08:08 UTC by hiji

2023-01-31 11:12 UTC, kumagoro1202 requested changes

2023-01-31 11:20 UTC, kumagoro1202 requested changes

2023-01-31 11:20 UTC, kumagoro1202 commented on ja/examples/12/index.rst
> +  また、ローテーション以外でも、情報漏洩等の緊急自体では情報が変更されるといったことも考えられる。
typo
緊急事態

2023-02-01 13:07 UTC, hiji commented on ja/examples/12/index.rst
> +  * Azure Active Directory B2C（以下ADB2C）
リンク追加しました。

fbfd3ba5c4be8245839364b794f45bc41e269366

2023-02-01 13:09 UTC, hiji commented on ja/examples/12/index.rst
> +異常を検知した場合は、エラーレスポンスとしてHTTPステータスを401（Unauthorized）を設定したレスポンスを返却する。
文章を見直しました。

a4a0d206266ebd808b879da428610c2e5815113c

2023-02-01 23:59 UTC, kumagoro1202 approved these changes

2023-02-02 01:17 UTC, merged