WebFrontControllerのコンポーネント名動的取得の説明を記載
nablarch/nablarch-document pull request #467
Opened 2023-02-07 05:31 UTC by takikunxo

2023-02-07 06:21 UTC, kumagoro1202 requested changes

2023-02-07 06:21 UTC, kumagoro1202 commented on ja/application_framework/application_framework/web/feature_details/web_front_controller.rst
> +   * component-nameのパラメータ値には、コンポーネント設定ファイルに設定したコンポーネント名を設定すること。
これだとデフォルトのwebFrontControllerを使う場合でもinit-paramを指定する必要があるように読めます。

削除してもらった「コンポーネント名はwebFrontControllerとすること」というポイントの記述を戻し、2.4.1.2.3.のセクションを新設してサーブレットフィルタが移譲するWebフロントコントローラの名前を変更する方法だけ切り出してもらったほうがいいと思いました。

元の1個だけwebFrontControllerを定義するパターンと、nablarch-example-webのようにウェブとRESTでwebFrontControllerを2つ定義するパターンとで別々のスニペットにした方がわかりやすいと思います。


```xml
<context-param>
  <param-name>di.config</param-name>
  <param-value>web-boot.xml</param-value>
</context-param>

<listener>
  <listener-class>nablarch.fw.web.servlet.NablarchServletContextListener</listener-class>
</listener>

<filter>
  <filter-name>entryPoint</filter-name>
  <filter-class>nablarch.fw.web.servlet.RepositoryBasedWebFrontController</filter-class>
</filter>

<filter-mapping>
  <filter-name>entryPoint</filter-name>
  <url-pattern>/action/*</url-pattern>
</filter-mapping>
```

```xml
  <filter>
    <filter-name>webEntryPoint</filter-name>
    <filter-class>nablarch.fw.web.servlet.RepositoryBasedWebFrontController</filter-class>
  </filter>
  <filter>
    <filter-name>jaxrsEntryPoint</filter-name>
    <filter-class>nablarch.fw.web.servlet.RepositoryBasedWebFrontController</filter-class>
    <init-param>
      <param-name>component-name</param-name>
      <param-value>jaxrsController</param-value>
    </init-param>
  </filter>

  <filter-mapping>
    <filter-name>webEntryPoint</filter-name>
    <url-pattern>/action/*</url-pattern>
    <url-pattern>/</url-pattern>
  </filter-mapping>
  <filter-mapping>
    <filter-name>jaxrsEntryPoint</filter-name>
    <url-pattern>/api/*</url-pattern>
  </filter-mapping>
```

2023-02-08 04:52 UTC, takikunxo commented on ja/application_framework/application_framework/web/feature_details/web_front_controller.rst
> +   * component-nameのパラメータ値には、コンポーネント設定ファイルに設定したコンポーネント名を設定すること。
[こちら](https://github.com/nablarch/nablarch-document/pull/467/commits/178529dd44760f1b24197ee7619c9f9c5f6362f3)で一旦Revertしました。
その後、[こちら](https://github.com/nablarch/nablarch-document/pull/467/commits/9b4b5e9b67a47fe82de5ccec5ba6b57d41e625ae)で2.4.1.2.3.のセクションを新設しました。

2023-02-08 06:40 UTC, kumagoro1202 commented on ja/application_framework/application_framework/web/feature_details/web_front_controller.rst
> +   * component-nameのパラメータ値には、コンポーネント設定ファイルに設定したコンポーネント名を設定すること。
セクションの最初にポイントに書いてくれているこの機能を使う場面・動機を書いた方が理解しやすいんじゃないかと思いました。それと、コンポーネント定義も記載してあげたほうがいいと思います。

こんな感じがわかりやすいかなと思いますがどうでしょう。

```
2.4.1.2.3. 移譲するWebフロントコントローラの名前を変更する

ウェブアプリケーションをベースとしたアプリケーションにおいて一部のリクエストをRESTfulウェブサービスとして処理したい場合など、
ウェブアプリケーションとウェブサービスを併用したい場合が考えられる。
そのような場合は、ハンドラ構成の異なるWebフロントコントローラを複数個定義する必要がある。
RepositoryBasedWebFrontControllerはデフォルトでは"webFrontController"という名前で
システムリポジトリから移譲するWebフロントコントローラを取得する。
RepositoryBasedWebFrontControllerに初期化パラメータを設定することで、
システムリポジトリから取得するWebフロントコントローラの名前を変更することができる。

ウェブアプリケーション用とRESTfulウェブサービス用2つのハンドラ構成を持つ
Webフロントコントローラの設定例を以下に示す。

まず、コンポーネント定義で、webFrontControllerと異なるコンポーネント名でWebフロントコントローラを
設定する。

  <component name="webFrontController"
             class="nablarch.fw.web.servlet.WebFrontController">
    <property name="handlerQueue">
      <list>
        <!-- ウェブアプリケーション用のハンドラ構成 -->
      </list>
    </property>
  </component>

  <component name="jaxrsController"
             class="nablarch.fw.web.servlet.WebFrontController">
    <property name="handlerQueue">
      <list>
        <!-- RESTfulウェブサービス用のハンドラ構成 -->
      </list>
    </property>
  </component>

次にweb.xmlに上記で設定したWebフロントコントローラを使用するためのサーブレットフィルタを設定する。

ポイント
・<init-param>を使いcontrollerNameというパラメータにシステムリポジトリから取得する際のコントローラ名を設定する
・<filter-mapping>でそれぞれのWebフロントコントローラが処理対象とするURLのパターンを設定する。

[web.xmlのスニペット]
```

2023-02-08 11:54 UTC, takikunxo commented on ja/application_framework/application_framework/web/feature_details/web_front_controller.rst
> +   * component-nameのパラメータ値には、コンポーネント設定ファイルに設定したコンポーネント名を設定すること。
>RepositoryBasedWebFrontControllerに初期化パラメータを設定することで
初期化パラメータを設定するのは正しくはweb.xmlでしょうか。
一旦その体で[コミット](https://github.com/nablarch/nablarch-document/pull/467/commits/11e7e8377e46b0ebc1c366bb1c8f24336eed0997)しております。

2023-02-09 02:55 UTC, kumagoro1202 commented on ja/application_framework/application_framework/web/feature_details/web_front_controller.rst
> +   * component-nameのパラメータ値には、コンポーネント設定ファイルに設定したコンポーネント名を設定すること。
> RepositoryBasedWebFrontControllerに初期化パラメータを設定することで

設定するファイルはweb.xmlです。設定する対象のインスタンスはRepositoryBasedWebFrontControllerです。
以下の意味で書いてました。

> (web.xmlの設定で)RepositoryBasedWebFrontControllerに初期化パラメータを設定する(よう記述する)ことで

「web.xml に初期化パラメータを設定することで、システムリポジトリから取得するWebフロントコントローラの名前を変更することができる。」で通じるので今の状態でOKです。

2023-02-09 02:55 UTC, kumagoro1202 approved these changes

2023-02-09 02:56 UTC, merged