実装例集：ログ集計サンプル：実装説明修正 (en)
nablarch/nablarch-document pull request #481
Opened 2023-03-02 09:22 UTC by sukegawatakashitis

### 変更内容

以下の実装説明内容を修正しました。
・nablarch-document/en/examples/10

2023-03-09 10:48 UTC, kumagoro1202 requested changes

2023-03-09 10:48 UTC, kumagoro1202 commented on en/examples/10/contents/OnlineAccessLogStatistics.rst
> +    When the analysis results of the following two files are used as inputs for tabulation, and the batch execution date is October 10, 2012 and the tabulation period is set to two days in the past,
137行目、10月7日を7daysとしていておかしいです。
以下に修正してください。

Logs output on October 7 beyond the past two days, which is the aggregation range, are also output as aggregate results.

2023-03-09 10:48 UTC, kumagoro1202 commented on en/examples/10/contents/OnlineAccessLogStatistics.rst
> +  Specify "main/resources/statistics-batch.xml" of the amount summary function project.
上と同じ

2023-03-10 00:23 UTC, sukegawatakashitis commented on en/examples/10/contents/OnlineAccessLogStatistics.rst
> +  Specify "main/resources/statistics-batch.xml" of the amount summary function project.
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/481/commits/5b2e475cef3d903708c6a561c4ccc63574030b21

2023-03-10 00:23 UTC, sukegawatakashitis commented on en/examples/10/contents/OnlineAccessLogStatistics.rst
> +  Specify "main/resources/statistics-batch.xml" of the amount summary function project.
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/481/commits/5b2e475cef3d903708c6a561c4ccc63574030b21

2023-03-10 00:32 UTC, sukegawatakashitis commented on en/examples/10/contents/OnlineAccessLogStatistics.rst
> +    When the analysis results of the following two files are used as inputs for tabulation, and the batch execution date is October 10, 2012 and the tabulation period is set to two days in the past,
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/481/commits/0017ab10e5afc900a365ded51bcc7de8f8cd67bf

2023-03-10 00:40 UTC, sukegawatakashitis commented on en/examples/10/contents/OnlineAccessLogStatistics.rst
> +Daily aggregation result                Outputs aggregate results on a daily basis.
こちらで修正しました。https://github.com/nablarch/nablarch-document/pull/481/commits/cbaaee7ba4cec5fe519bab30d123e853b2ef7e25

2023-03-10 01:02 UTC, kumagoro1202 approved these changes

2023-03-10 01:02 UTC, merged