アップロードファイル数の上限に関する説明の追加
nablarch/nablarch-document pull request #483
Opened 2023-03-06 09:48 UTC by opengl-8080

- アップロードファイル数の上限を設定する方法について説明を追加
- デフォルト設定一覧に `maxFileCount` を追加
- アップロードファイルサイズ上限についていくつか説明に誤りがあったので修正
  - エラー時のステータスが 400 となっていたが実際は 413 なので 413 に修正
  - ファイルサイズのコメントが 約10M となっていたが実際に設定されている値は約 1MB なので 1MB に修正
- アップロードファイルサイズ上限について、セキュリティ的な観点から設定を推奨するような記述が無かったので記載

2023-03-06 12:07 UTC, kumagoro1202 requested changes

2023-03-06 12:07 UTC, kumagoro1202 commented on ja/application_framework/application_framework/handlers/web/multipart_handler.rst
> +不必要な処理を減らすため、マルチパートリクエストハンドラでは一度にアップロードできるファイル数に上限を設定できるようになっている。
上限超過したら何が返るか（400Bad Requestですよね）も記載してください。

2023-03-06 23:43 UTC, opengl-8080 commented on ja/application_framework/application_framework/handlers/web/multipart_handler.rst
> +不必要な処理を減らすため、マルチパートリクエストハンドラでは一度にアップロードできるファイル数に上限を設定できるようになっている。
記載しました。

https://github.com/nablarch/nablarch-document/pull/483/commits/0d58bda9db9a6c71a4cb10a6eb226825655f27b4

2023-03-07 00:38 UTC, kumagoro1202 approved these changes

2023-03-07 00:38 UTC, merged