Jakarta EE対応
nablarch/nablarch-document pull request #496
Opened 2023-04-04 04:31 UTC by opengl-8080

修正内容。

- develop の最新をマージ
- バージョンが 5uXX 前提の記述となっている部分を 6uXX 前提に修正
- Jakarta EE 10 前提となったことで変更が必要になった箇所の修正
- Java 17 前提となったことで変更が必要になった箇所の修正
- Java EE の API へのリンクを Jakarta EE の API へのリンクに修正
- 名前空間 javax を jakarta に修正
- JSR という記述を削除
- JSTL を読み込むときの uri の指定を修正
- waitt プラグインを前提とした説明を jetty プラグインを用いた場合に修正
- xml のスキーマ指定を Jakarta EE のものに修正
- 6uXX にはもっていかないコンテンツを削除
- Java EE の仕様名を用いている部分を Jakarta EE の仕様名に修正
- Jakarta EE 対応でライブラリのバージョンを上げた箇所を修正
- Jakarta EE の仕様名に関する説明ページを追加
- 仕様名が変わった機能の冒頭に、名前が変わったことを補足する説明を追加

2023-06-15 06:09 UTC, kumagoro1202 requested changes

2023-10-19 02:54 UTC, kumagoro1202 requested changes

2023-10-19 02:54 UTC, kumagoro1202 commented on ja/application_framework/application_framework/blank_project/setup_blankProject/setup_Web.rst
> +  mvn jetty-ee10:run
これは`jetty:run`で良くなったんでしたっけ？

2023-10-19 02:54 UTC, kumagoro1202 commented on ja/application_framework/application_framework/handlers/web/SessionStoreHandler.rst
> +:HttpOnly属性:  | 常に使用する
「常に」は要らないと思います。

2023-10-24 05:27 UTC, hiji commented on ja/application_framework/application_framework/nablarch/platform.rst
> + * Java SE 17
PostgreSQL 11は今年の11月でEOLを迎えるため、12月のv6リリース時点ですでにEOLを迎えた状態になってしまうのですが、こちらも除去してよかったでしょうか？

2023-10-24 05:29 UTC, kumagoro1202 commented on ja/application_framework/application_framework/nablarch/platform.rst
> + * Java SE 17
はい、いいです。

2023-10-24 06:21 UTC, kumagoro1202 commented on ja/application_framework/application_framework/handlers/web/SessionStoreHandler.rst
> +:HttpOnly属性:  | 常に使用する
それでもいいです。もともとNablarch5系だとAPIが対応してるかどうかで切り替えてたので書いてたんだと思いますが、そのような分岐がなくなったならそれに合わせて書き方見直してもらって大丈夫です。

2023-10-24 06:33 UTC, hiji commented on ja/about_nablarch/concept.rst
> +.. [1] RedisやWebSphere MQなど
修正しました。

02897461256d23c202e77ac5311bffd1068d95f9
4bf72b105653c5127caf58c6e4718e59eee4f93f

2023-10-24 06:33 UTC, hiji commented on ja/about_nablarch/versionup_policy.rst
> +  開始番号は6です。
修正しました。

61e42a0d696a166a0376993fa1bf7f031b78886f
f031505d58545f62500289d002855f586eea0fb1

2023-10-24 06:34 UTC, hiji commented on ja/application_framework/application_framework/blank_project/setup_blankProject/setup_Web.rst
> +  mvn jetty-ee10:run
修正しました。

ab53ff08349b0063b741c161adf04ac107b7f580

2023-10-24 06:34 UTC, hiji commented on ja/application_framework/application_framework/handlers/web/SessionStoreHandler.rst
> +:HttpOnly属性:  | 常に使用する
修正しました(表から削除）。

ab53ff08349b0063b741c161adf04ac107b7f580

2023-10-24 06:58 UTC, kumagoro1202 commented on ja/application_framework/application_framework/handlers/web/SessionStoreHandler.rst
> +:HttpOnly属性:  | 常に使用する
表から削除した状態見ましたが少し違和感を感じました。
MaxAge属性もセッション変数保存ハンドラ経由では設定できないものですが、HttpCookieに持ってるので書いてるのかなと。だとすると表から削除して下部の補足とか重要みたいなので記載するより、表内に入れてしまったほうがいいんじゃないかと思いました。


|**クッキー名:**|NABLARCH_SID|
|---|---|
|**Path属性:**|ホスト配下のすべてのパス<br>送信可能なパスを明示的に指定したい場合に別途設定すること|
|**Domain属性:**|指定しない<br>送信可能なドメインを明示的に指定したい場合に別途設定すること|
|**Secure属性:**|使用しない<br>HTTPS環境で使用する場合は、使用する に設定すること|
|**MaxAge属性:**|指定しない<br>セッションIDを保持するクッキーをセッションクッキー(ブラウザを閉じれば破棄されるクッキー)とするため、MaxAge属性は使用しない。<br>セッションストアの有効期間は、HTTPセッションに保存する。 複数のストア間で異なる有効期間を設定した場合は、最も期間の長い値をHTTPセッションに保存する。|
|**HttpOnly属性**|指定しない<br>HttpOnly属性は常に使用され、設定ファイル等からは変更できない。|

2023-10-25 02:14 UTC, hiji commented on ja/application_framework/application_framework/handlers/web/SessionStoreHandler.rst
> +:HttpOnly属性:  | 常に使用する
修正しました。重要で記載した内容もあわせて見直しました。

487676e90d29fe8bfa006a235c5f26989a218476

2023-10-25 02:21 UTC, kumagoro1202 requested changes

2023-10-25 02:21 UTC, kumagoro1202 commented on ja/application_framework/application_framework/handlers/web/SessionStoreHandler.rst
> +  （データベースに保存するための設定については :ref:`db_managed_expiration` を参照）
最初の文とカッコ書きの内容が繋がらないので
「セッションストアの有効期間はデフォルトではHTTPセッションに保存される。
複数のストア間で異なる有効期間を設定した場合は、最も期間の長い値が使用される。
  （有効期間の保存先をHTTPセッションからデータベースに変更する場合は :ref:`db_managed_expiration` を参照）」
とかの方が良いかなと思いました。

2023-10-25 02:36 UTC, hiji commented on ja/application_framework/application_framework/handlers/web/SessionStoreHandler.rst
> +  （データベースに保存するための設定については :ref:`db_managed_expiration` を参照）
見直しました。

8a4b72f83e7d8d0c54f3373aa125a84d9d7317ca

2023-10-25 02:38 UTC, kumagoro1202 approved these changes

2023-10-25 02:38 UTC, merged