Logbook実装例を英訳しました
nablarch/nablarch-document pull request #504
Opened 2023-05-18 08:56 UTC by chupaaaaaaan

2023-05-19 02:58 UTC, kumagoro1202 requested changes

2023-05-19 02:58 UTC, kumagoro1202 commented on en/examples/13/index.rst
> +  In this sample, Jersey uses a version that takes into account the version of Jackson used by the :ref:`jaxrs_adaptor`.
Jerseyがバージョンを使うというのは主語がおかしいです。

2023-05-23 08:23 UTC, chupaaaaaaan commented on en/examples/13/index.rst
> +Scope covered in this sample
修正しました。

2023-05-23 08:24 UTC, chupaaaaaaan commented on en/examples/13/index.rst
> +  In this sample, Jersey uses a version that takes into account the version of Jackson used by the :ref:`jaxrs_adaptor`.
修正しました。

2023-05-23 08:29 UTC, kumagoro1202 approved these changes

2023-05-23 08:30 UTC, merged