論理属性の記載位置を修正、タグリファレンスに論理属性への参照を追加
nablarch/nablarch-document pull request #505
Opened 2023-05-26 01:17 UTC by chupaaaaaaan

2023-05-26 05:54 UTC, kumagoro1202 requested changes

2023-05-26 05:54 UTC, kumagoro1202 commented on ja/application_framework/application_framework/libraries/tag.rst
> +論理属性を指定する
ここをただ独立させただけではだめです。書き方を変えないと「動的属性の論理属性についても～」だと文意が正確ではないです。動的属性に限った話ではなく、カスタムタグ全体での話にしてください。また最後のパラグラフは動的属性に限った話なので、こちらではなく、任意の属性を指定するのセクションに書かないといけないです。

2023-05-26 08:38 UTC, chupaaaaaaan commented on ja/application_framework/application_framework/libraries/tag.rst
> +論理属性を指定する
- カスタムタグで定義済みの論理属性の項目を独立させました。
- 論理属性として扱う動的属性の記述を修正しました。

2023-05-26 11:06 UTC, kumagoro1202 commented on ja/application_framework/application_framework/libraries/tag.rst
> +論理属性を指定する
例に書いてるn:script タグのasync属性は動的属性なので違う例にしてください。textタグのdisabledとかでいいんじゃないでしょうか。

2023-05-26 12:10 UTC, chupaaaaaaan commented on ja/application_framework/application_framework/libraries/tag.rst
> +論理属性を指定する
textタグを使用した例に変更しました。

2023-06-02 05:23 UTC, kumagoro1202 requested changes

2023-06-02 05:30 UTC, chupaaaaaaan commented on ja/application_framework/application_framework/libraries/tag.rst
> +asyncを例に実装例を以下に示す。
英語版と合わせて修正しました。

2023-06-02 05:38 UTC, kumagoro1202 requested changes

2023-06-02 05:38 UTC, kumagoro1202 commented on en/application_framework/application_framework/libraries/tag.rst
> +Handling of Boolean attribute
単数形にしたのはなぜ？

2023-06-02 05:38 UTC, kumagoro1202 commented on en/application_framework/application_framework/libraries/tag.rst
> +Handling of Boolean attribute
逆に変えていないSpecify any attributeはanyの後が単数形になってるのでおかしい。

2023-06-02 05:51 UTC, chupaaaaaaan commented on en/application_framework/application_framework/libraries/tag.rst
> +Handling of Boolean attribute
誤って消したのを見逃してしまってました。
「Specify any attribute」の方と合わせて複数形に直しました。

2023-06-02 06:28 UTC, kumagoro1202 approved these changes

2023-06-02 06:28 UTC, merged