BeanValidationのグルーピングについての記載を追加しました
nablarch/nablarch-document pull request #519
Opened 2023-07-20 06:50 UTC by chupaaaaaaan

2023-07-20 08:42 UTC, kumagoro1202 requested changes

2023-07-20 08:42 UTC, kumagoro1202 commented on ja/application_framework/application_framework/handlers/web_interceptor/InjectForm.rst
> +
58行目に既存typo「バリーション」

2023-07-20 08:42 UTC, kumagoro1202 commented on ja/application_framework/application_framework/handlers/web_interceptor/InjectForm.rst
> +``validationStrategy`` に :java:extdoc:`BeanValidationStrategy <nablarch.common.web.validator.BeanValidationStrategy>` を設定している場合は、 ``InjectForm`` アノテーションにBean Validationのグループを指定することができる。
79行目に合わせて「バリデーションにBean Validationを使用する場合」としてください。

2023-07-20 08:42 UTC, kumagoro1202 commented on ja/application_framework/application_framework/handlers/web_interceptor/InjectForm.rst
> +``validationStrategy`` に :java:extdoc:`BeanValidationStrategy <nablarch.common.web.validator.BeanValidationStrategy>` を設定している場合は、 ``InjectForm`` アノテーションにBean Validationのグループを指定することができる。
> ``InjectForm`` アノテーションにBean Validationのグループを指定することができる。

「Bean Validationの」は冗長だから不要。

2023-07-20 08:42 UTC, kumagoro1202 commented on ja/application_framework/application_framework/libraries/validation/bean_validation.rst
> +詳細は、 :ref:`jaxrs_bean_validation_handler` を参照。
参照先はハンドラじゃなく、ハンドラの中の「6.4.2.4. リソース(アクション)で受け取るForm(Bean)に対してバリデーションを実行する」とするべき。

2023-07-20 08:42 UTC, kumagoro1202 commented on ja/application_framework/application_framework/handlers/rest/jaxrs_bean_validation_handler.rst
> +* ``from`` ・・・ :java:extdoc:`Default <javax.validation.groups.Default>` を指定する
:java:extdoc:`Default <javax.validation.groups.Default>` 固定
とかの方がいいと思う。

2023-07-20 08:42 UTC, kumagoro1202 commented on ja/application_framework/application_framework/libraries/validation/bean_validation.rst
> +APIの詳細は、 :java:extdoc:`ValidatorUtil <nablarch.core.validation.ee.ValidatorUtil>` を参照。
参照先はvalidateWithGroupとvalidatePropertyの方がいい。ValidatorUtilに飛ばされてもどこを見ればいいのかわからないと思う。

2023-07-20 09:23 UTC, chupaaaaaaan commented on ja/application_framework/application_framework/handlers/web_interceptor/InjectForm.rst
> +
修正しました。

2023-07-20 11:03 UTC, chupaaaaaaan commented on ja/application_framework/application_framework/handlers/rest/jaxrs_bean_validation_handler.rst
> +* ``from`` ・・・ :java:extdoc:`Default <javax.validation.groups.Default>` を指定する
「固定」に変更しました。

2023-07-20 11:04 UTC, chupaaaaaaan commented on ja/application_framework/application_framework/handlers/web_interceptor/InjectForm.rst
> +``validationStrategy`` に :java:extdoc:`BeanValidationStrategy <nablarch.common.web.validator.BeanValidationStrategy>` を設定している場合は、 ``InjectForm`` アノテーションにBean Validationのグループを指定することができる。
記載を修正しました。

2023-07-20 11:09 UTC, chupaaaaaaan commented on ja/application_framework/application_framework/libraries/validation/bean_validation.rst
> +詳細は、 :ref:`jaxrs_bean_validation_handler` を参照。
当該項目へのリンクに修正しました。

2023-07-20 11:09 UTC, chupaaaaaaan commented on ja/application_framework/application_framework/libraries/validation/bean_validation.rst
> +APIの詳細は、 :java:extdoc:`ValidatorUtil <nablarch.core.validation.ee.ValidatorUtil>` を参照。
当該項目へのリンクに修正しました。

2023-07-21 05:08 UTC, kumagoro1202 requested changes

2023-07-21 05:08 UTC, kumagoro1202 commented on ja/application_framework/application_framework/handlers/web_interceptor/InjectForm.rst
> +バリデーションに :ref:`bean_validation` を使用する場合は、 ``InjectForm`` アノテーションにグループを指定することができる。
`InjectForm`アノテーションの`validationGroup`にグループを指定するとしてください。
実装例見ないとどの属性に指定するかわからないのはNG

2023-07-21 10:01 UTC, chupaaaaaaan commented on ja/application_framework/application_framework/libraries/validation/bean_validation.rst
> +
「RESTfulウェブサービスのユーザ入力値のチェックを行う」へのリンクを、「Bean Validationを使うための設定」に追加しました。

2023-07-21 10:02 UTC, chupaaaaaaan commented on ja/application_framework/application_framework/handlers/web_interceptor/InjectForm.rst
> +バリデーションに :ref:`bean_validation` を使用する場合は、 ``InjectForm`` アノテーションにグループを指定することができる。
他の箇所と合わせ、 `validationGroup` のJavadocへのリンクとしました。

2023-07-24 01:24 UTC, kumagoro1202 approved these changes

2023-07-24 01:24 UTC, merged