BeanValidationに対応したForm/Entityのテストについて、解説を追加しました。
nablarch/nablarch-document pull request #527
Opened 2023-08-31 07:10 UTC by chupaaaaaaan

2023-09-01 02:36 UTC, kumagoro1202 requested changes

2023-09-01 02:36 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> +そのため、上記のようなプロパティが存在し、Form全体での整合性を検証する必要がある場合は、別途テストを作成する必要がある。
ごちゃごちゃ書いているがあまり内容が伝わらない。
「上記までの単項目精査でテストできないような、`@AssertTrue`を指定した項目間精査などは、別途テストを作成する必要がある。」くらいの方がわかりやすいと思う。

2023-09-01 02:36 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> + |                                   | | の *n* に対応、\ *k*\ は1からの連番、省略可）   |
「nはexpectedMessageIdの n に対応、kは1からの連番、省略可」
だと、省略可がどこにかかるかわかりにくく、kを省略していいように見えなくもない。読点ではなく句点で
「nはexpectedMessageIdの n に対応、kは1からの連番。省略可」とした方がいい。

2023-09-01 02:36 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> + 数値を増やして右側に追加していく。
どこに対する注記？注記が後にあるのが混乱のもとだと思う。表の直下に注記があってその後テストケース表の説明という順番であるべき。

2023-09-01 02:36 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> +    入力パラメータ表には、Form全体の整合性を検証するために必要なプロパティの値を記載する。
どういう意味？Formのプロパティ全部記載するということ？テストに必要な項目だけ？必須項目だけ？何を記載すればいいのか読み取れない。

2023-09-01 02:36 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> +    下図では、個別のプロパティの値の妥当性確認の他、"newPasswordとconfirmPasswordが等しいか否か"を ``boolean`` として返すプロパティに対する異常系のケースを作成している。
等しいか否かをbooleanとして返すという表現はわかりにくい。等しいことをバリデーションするプロパティとかでいいのでは？

2023-09-01 02:36 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> +    下図では、個別のプロパティの値の妥当性確認の他、"newPasswordとconfirmPasswordが等しいか否か"を ``boolean`` として返すプロパティに対する異常系のケースを作成している。
個別のプロパティの値の妥当性確認というのがここで書かれている理由がわからない。これは普通の単項目精査で確認できるものでは？なぜこの例に含めている？

2023-09-01 02:36 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> +    ※Formの保有するプロパティ名のExcelへの記述手順は、 :ref:`property-name-copy-label` を参照。
IntelliJを推奨しておきながらEclipseでの手順を案内するのは不信感を持たれる。IntelliJの手順にアップデートするべき。

2023-09-01 02:36 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> +    ※Formの保有するプロパティ名のExcelへの記述手順は、 :ref:`property-name-copy-label` を参照。
Nablarch Validationの方にリンクさせているが、現在推奨するバリデーションはBeanValidationなので、どちらかにだけ書くのであればBeanValidationに記載してNablarch Validationから参照する形にするべき。

2023-09-01 02:36 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> +    下図では、個別のプロパティの値の妥当性確認の他、"newPasswordとconfirmPasswordが等しいか否か"を ``boolean`` として返すプロパティに対する異常系のケースを作成している。
口頭で確認の結果上記を含めたのはExcelフォーマットにあるカラムを使うためと理解。無用な混乱を生むだけなので単項目精査で確認できるものはこの例から削除すること。

2023-09-01 02:36 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> +Form全体の精査のテストケース
口頭で確認した結果BeanValidationの仕様上プロパティを絞ってバリデーションできないことを名前に込めたと理解。しかしここでフォーカスするべきはForm全体の精査ではなくやはり項目間精査などであるのでこの名前は変えること。注意として必須項目のバリデーションも行われてしまうからエラーにならない値を設定することを追記する。

2023-09-01 02:41 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest.rst
> +|messageIdWhenEmptyInput      |未入力時に期待するメッセージ（省略可）            |
修正しました。

2023-09-01 04:58 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest.rst
> +
追記しました。
合わせて、EntityTestConfigurationの項目にも説明を追加しました。

2023-09-01 04:59 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest.rst
> +.. _entityUnitTest_EntityTestConfiguration_BeanValidation:
修正しました。

2023-09-01 05:01 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest.rst
> +.. _entityUnitTest_EntityTestConfiguration_BeanValidation:
修正しました。

2023-09-01 05:08 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> + 数値を増やして右側に追加していく。
順番を変更しました。

2023-09-01 05:08 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> + |                                   | | の *n* に対応、\ *k*\ は1からの連番、省略可）   |
修正しました。

2023-09-01 07:04 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/index.rst
> +   03_entityUnitTestWithBeanValidation
Form/Entityの単体テストを2階層、Action/Componentの単体テストを1階層として表示するのは難しそう（`:maxdepth:`ディレクティブで`2`を指定すると、Action/Componentの単体テストの中身の見出しが出てくる）のため、以下のようにしました。

（クラス単体テストのページ）
- Form/Entityの単体テスト
- Action/Componentの単体テスト

（Form/Entityの単体テストのページ）
- Bean Validationに対応したForm/Entityの単体テスト
- Nablarch Validationに対応したForm/Entityの単体テスト

2023-09-01 07:10 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> +    入力パラメータ表には、Form全体の整合性を検証するために必要なプロパティの値を記載する。
下のコメントと合わせ、相関精査を前提とした記載に修正しました。

2023-09-01 07:33 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest.rst
> +messageIdWhenEmptyInput、messageIdWhenInvalidLengthを省略した場合は、それぞれ :ref:`entityUnitTest_EntityTestConfiguration_BeanValidation` で
修正しました。

2023-09-01 07:33 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest.rst
> +.. _entityUnitTest_EntityTestConfiguration_BeanValidation:
修正しました。

2023-09-01 07:34 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> +* 単項目精査のテストケース作成を容易になる。
修正しました。

2023-09-01 08:07 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> +interpolateKey_1 には埋め込み文字のキー名を、 interpolateKey_1 には埋め込み文字の値を、それぞれ記載する。
修正しました。

2023-09-01 08:20 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> +    :scale: 100
注記として記載しました。他の表についても、注記として記載可能なものは注記に回しました。

2023-09-01 08:23 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> +.. image:: ./_image/entityUnitTest_singleValidationDataExample_BeanValidation.png
末尾の～は省略の意味です。かなり長くなるので記号を付けましたが、わかりにくそうなので記号を小さくし、横に「省略」と記載しました。
group未入力は誤りなので修正しました。

2023-09-01 08:35 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> +Form全体の精査のテストケース
いずれも修正しました。

2023-09-01 08:39 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> +そのため、上記のようなプロパティが存在し、Form全体での整合性を検証する必要がある場合は、別途テストを作成する必要がある。
修正しました。

2023-09-01 09:01 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> +    ※Formの保有するプロパティ名のExcelへの記述手順は、 :ref:`property-name-copy-label` を参照。
Nablarch Validationにリンクさせている内容に関連し、コンストラクタのテストについてはNablarch Validation固有の話題だった（Nablarch Validationを使用する場合は、Map<>を引数に取るコンストラクタが必要になるので、そのようなコンストラクタのテストについて記載している）ため、記載を削除しました。
https://nablarch.github.io/docs/LATEST/doc/application_framework/application_framework/libraries/validation/nablarch_validation.html#nablarch-validation-execute

2023-09-01 11:27 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> +    ※Formの保有するプロパティ名のExcelへの記述手順は、 :ref:`property-name-copy-label` を参照。
そのほかのリンクは、Nablarch ValidationからBean Validationのページを参照するように修正しました。

2023-09-01 12:51 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> +    ※Formの保有するプロパティ名のExcelへの記述手順は、 :ref:`property-name-copy-label` を参照。
Nablarch Validation側のコンストラクタのテストの記載について、必要なコンストラクタについてのテストである旨記載しました。

2023-09-01 12:54 UTC, chupaaaaaaan commented
01_entityUnitTestWithBeanValidation.rst 297行目、02_entityUnitTestWithNablarchValidation 275行目の記載を追加しました。

2023-09-03 23:58 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest.rst
> +
typo
「max欄及びmin欄の記載よって決まり」
「max欄及びmin欄の記載**に**よって決まり」

2023-09-04 00:36 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest.rst
> +
「省略時にどの設定が使用されるか」
「省略時に使用される設定」
という言葉に違和感。それぞれ
「省略時にどの設定値が使用されるか」
「省略時に使用される設定値」
とか
「省略時にどのデフォルト値が使用されるか」
「省略時に使用されるデフォルト値」
などが自然だと思います。
「設定したデフォルト値が使用される。省略時にどの設定が使用されるかは、」という流れなので
「設定したデフォルト値が使用される。省略時にどのデフォルト値が使用されるかは、」というのが前の文とも整合性が取れていて一番いいと思います。
これが「設定した値が使用される。省略時にどの設定値が使用されるかは、」だったら設置値を採用してもいいと思う。

2023-09-04 01:01 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest.rst
> +
> [@Length](https://nablarch.github.io/docs/LATEST/javadoc/nablarch/core/validation/validator/Length.html) において、 max > min である場合、 文字列長が超過・不足のいずれの場合であっても、出力されるメッセージは同じである

は不要

2023-09-04 01:21 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest/02_entityUnitTestWithNablarchValidation.rst
> ++--------------+----------------+-------------------------+
「maxAndMinMessageId(超過時)、underLimitMessageId(不足時)」になるのでは？

2023-09-04 01:21 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest/01_entityUnitTestWithBeanValidation.rst
> ++--------------+--------------+----------------+-------------------------+
「maxAndMinMessageId(超過時)、underLimitMessageId(不足時)」になるのでは？

2023-09-04 01:21 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest/01_entityUnitTestWithBeanValidation.rst
> +メッセージ全体を ``{}`` で囲んだ場合は、メッセージIDと見なされ、 :ref:`message` で解決される。
例を書いた方がいい。（Excelフォーマットの例は下部にあるが、ここでメッセージの記載方法にフォーカスして例を書いておくべき。）

2023-09-04 01:21 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> +.. image:: ./_image/entityUnitTest_singleValidationDataExample_BeanValidation.png
そもそも全量書いてるかどうかはどうでもいい情報ではないですか。ピックアップして例を見せるというのは普通のことで取り立ててこの例にだけ省略していることを記載する必要がないと思いました。

2023-09-04 01:24 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> +そのため、上記のようなプロパティが存在し、Form全体での整合性を検証する必要がある場合は、別途テストを作成する必要がある。
「Formの1個のプロパティに対して、フィールドもしくはゲッターメソッドに付与されたアノテーションが正しいかテストされるが」ここが相変わらずごちゃごちゃしています。「単項目精査のテスト」=「Formの1個のプロパティに対して、フィールドもしくはゲッターメソッドに付与されたアノテーションが正しいかのテスト」なのだから言い換える必要がない。

2023-09-04 01:30 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> + 数値を増やして右側に追加していく。
162行目辺りも同様。またNablarch Validationの「3.1.1.1.2.1.3.1. テストケース表の作成方法」も同様。

2023-09-04 01:54 UTC, kumagoro1202 requested changes

2023-09-04 01:54 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest/01_entityUnitTestWithBeanValidation.rst
> +必要に応じて、個別にコンストラクタのテストを実装すること。
触れる必要がないと思う。Nablarch Validationは仕様上Mapを引数に取るコンストラクタでバリデーション済みの値を一気に設定するからテストやりたいという要望があるけど、BeanValidationはそもそもそのようなコンストラクタを作るのは普通じゃないのでテストしたい場面もないと思う。setterとgetterのテストがあれば十分なので触れる必要がない。触れてるのはNablarch Validationとの対比というコンテキストに頭が支配されてるからだと思う。

2023-09-04 01:54 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest/01_entityUnitTestWithBeanValidation.rst
> +これらのプロパティが必要になる場合は、個別に記載すること。
この説明は不要だと思う。一般的な認識でプロパティと言った時にアクセサメソッドだけでクラス変数持たないものも含むという考えにはなりにくく混乱させるだけだと思う。

2023-09-04 01:54 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest/01_entityUnitTestWithBeanValidation.rst
> +   「Fields」ボタン及び「Non-public」ボタンを活性化させること。
これIntelliJの公式ドキュメントとかに記載はないの？

2023-09-04 01:54 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest/01_entityUnitTestWithBeanValidation.rst
> +   そのため、underLimitMessageIdとmaxAndMinMessageIdは同じ値を設定する必要がある。
NablarchValidationの指摘同様。

2023-09-04 02:57 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest.rst
> +
上記修正しました。

1b02710bb06f6570dceaecec40b8b0a1a8b3dfba

2023-09-04 03:01 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> +そのため、上記のようなプロパティが存在し、Form全体での整合性を検証する必要がある場合は、別途テストを作成する必要がある。
表現を削除しました。

a29d5f0c30cc400fb37d98ce920f63225c5267aa

2023-09-04 03:05 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest/01_entityUnitTestWithBeanValidation.rst
> ++--------------+--------------+----------------+-------------------------+
修正しました。

22827fd1e0e2568a21a1e853afdb6b233037ed4c

2023-09-04 03:18 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest/01_entityUnitTestWithBeanValidation.rst
> +メッセージ全体を ``{}`` で囲んだ場合は、メッセージIDと見なされ、 :ref:`message` で解決される。
例を追加しました。

8ab4d44073ffdbacb0b306a045a6b3f32233d88f

2023-09-04 03:20 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest/01_entityUnitTestWithBeanValidation.rst
> +必要に応じて、個別にコンストラクタのテストを実装すること。
削除しました。

d9db7098cc745c11ba5df97a266244ea025ffa1a

2023-09-04 03:25 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest/01_entityUnitTestWithBeanValidation.rst
> +これらのプロパティが必要になる場合は、個別に記載すること。
削除しました。

50a074d31c8cc81ae4f3b48c6fddc795dc1c76e5

2023-09-04 03:28 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest/01_entityUnitTestWithBeanValidation.rst
> +   「Fields」ボタン及び「Non-public」ボタンを活性化させること。
公式ドキュメントに記載あります。
https://github.com/nablarch/nablarch-document/pull/527#discussion_r1314372033

2023-09-04 03:29 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest/01_entityUnitTestWithBeanValidation.rst
> +   そのため、underLimitMessageIdとmaxAndMinMessageIdは同じ値を設定する必要がある。
削除しました。

ecf28b9ca268f532c8e331ca609a9468501a1c38

2023-09-04 03:32 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest/02_entityUnitTestWithNablarchValidation.rst
> ++--------------+----------------+-------------------------+
修正しました。

9f16ebb24cfd544bc68914b540588528e24d5088

2023-09-04 03:38 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> + 数値を増やして右側に追加していく。
表全体にわたる記載なので、注記としない方がよいかと思いましたが、それぞれ「未入力を許可するか」「メッセージ」が最初に出てきたセルに注記を付するとしました。

5c7b81a28105d9a1b480927fd70b57ffc7ecc507

2023-09-04 03:53 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> +.. image:: ./_image/entityUnitTest_singleValidationDataExample_BeanValidation.png
他のものは省略なしで載せているので、利用者が図だけ見て「文字種精査が不足している」と思わないためにも省略しているのは明記したほうがいいかなと思いましたが、Excelシート自体も載せているのでその部分の懸念はしなくてもよいかと思いました。
省略の表記を削除しました。

9ce23b2ca92190171e36f4f4bacd36642d98c31f

2023-09-04 04:10 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest.rst
> +
NablarchValidationの方が直っていない。

2023-09-04 04:14 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest/01_entityUnitTestWithBeanValidation.rst
> +   「Fields」ボタン及び「Non-public」ボタンを活性化させること。
いや存在を聞いているのではなく公式ドキュメントを案内するべきではないのという指摘です。

2023-09-04 04:19 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> + 数値を増やして右側に追加していく。
注記とするべきという指摘ではなく、注記と表が離れているのが問題だという指摘です。表全体が対象となる記載を注記とするべきではないと思います。

---

| A | B |
|---|---|
| C※ | D |

この表はなんたらかんたら

※Cは〇〇の時に☓☓

---

より

---

| A | B |
|---|---|
| C※ | D |

※Cは〇〇の時に☓☓

この表はなんたらかんたら

---

がいいという話。

2023-09-04 04:39 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest.rst
> +
すみません、修正しました。

ee1919cbb4130b9bca8408b989f12011d7bf3f8b

2023-09-04 05:14 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest/01_entityUnitTestWithBeanValidation.rst
> +   「Fields」ボタン及び「Non-public」ボタンを活性化させること。
口頭確認の通り、節自体を削除しました。

420954a5c727deb17afe8f195b77bff6874d9799

2023-09-04 05:20 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/03_entityUnitTestWithBeanValidation.rst
> + 数値を増やして右側に追加していく。
口頭確認の通り、修正しました。

d8b5cd32d43fb69afc7afee8c02ed94ee3239060

2023-09-04 05:29 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest.rst
> +
「max欄及びmin欄の記載よって決まり」が直っていない。

2023-09-04 05:36 UTC, kumagoro1202 commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest/01_entityUnitTestWithBeanValidation.rst
> +   「Fields」ボタン及び「Non-public」ボタンを活性化させること。
消しすぎて自動テストフレームワーク設定値のアンカーが無くなってる。

2023-09-04 05:44 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest/01_entityUnitTestWithBeanValidation.rst
> +   「Fields」ボタン及び「Non-public」ボタンを活性化させること。
すみません、修正しました。

de65d6a1aff483640768aa69f7259771086f0126

2023-09-04 05:45 UTC, chupaaaaaaan commented on ja/development_tools/testing_framework/guide/development_guide/05_UnitTestGuide/01_ClassUnitTest/01_entityUnitTest.rst
> +
何度もすみません、修正しました。

de65d6a1aff483640768aa69f7259771086f0126

2023-09-04 06:03 UTC, kumagoro1202 approved these changes

2023-09-04 06:03 UTC, merged