有識者レビューの指摘対応
nablarch/nablarch-document pull request #542
Opened 2023-12-07 07:32 UTC by hiji

2023-12-08 04:56 UTC, hiji commented on ja/migration/index.rst
> +実行時に上記のようなスタックトレースが出力されてエラーになる場合、クラスパスの順序においてslf4j-nablarch-adaptorをLogbackより後にすることでエラーを解消できる。
対応しました。

6acf00a8e5a5fc2f52d43c2d4d9868be46ca8ddc

2023-12-08 06:14 UTC, tisurgm requested changes

2023-12-08 06:30 UTC, hiji commented on ja/migration/index.rst
> +nablarch-example-webをはじめ、アーキタイプから作ったNablarchプロジェクトなどには `gsp-dba-maven-plugin (外部サイト) <https://github.com/coastland/gsp-dba-maven-plugin/tree/v5-master>`_ があらかじめ組み込まれている。
指摘いただいている箇所はgspプラグインなのでウェブ以外も対象なのですが、waittプラグインのところはおっしゃるようにウェブだけ対象になるので、文章を修正しました。

14a9795dc5ab6d9a66de2eb55776a76a310ae221

2023-12-08 11:57 UTC, tisurgm commented on ja/migration/index.rst
> +nablarch-example-webをはじめ、アーキタイプから作ったNablarchプロジェクトなどには `gsp-dba-maven-plugin (外部サイト) <https://github.com/coastland/gsp-dba-maven-plugin/tree/v5-master>`_ があらかじめ組み込まれている。
あ、waittの段落と間違えていました。。。

2023-12-08 13:39 UTC, charon-r13b commented on ja/migration/index.rst
>        <version>...</version>
もう少し↑ですが

`    <!-- JBereteをJavaSEで動作させるための依存関係 -->`

`JBeret`の誤りですね…。

2023-12-11 00:02 UTC, hiji commented on ja/migration/index.rst
> +詳細については `gsp-dba-maven-pluginのガイド (外部サイト) <https://github.com/coastland/gsp-dba-maven-plugin/tree/v5-master#generate-entity>`_ を参照のこと。
紛らわしいのですが、GSPプラグイン 5 からは `annotation-api` を本体の依存関係に含めたので、READMEからは追加の手順が削除されています。ですので、補足は不要になります。

https://github.com/coastland/gsp-dba-maven-plugin/blob/5.0.0-develop/README.md

2023-12-11 06:52 UTC, hiji commented on ja/migration/index.rst
> +詳細については `gsp-dba-maven-pluginのガイド (外部サイト) <https://github.com/coastland/gsp-dba-maven-plugin/tree/v5-master#generate-entity>`_ を参照のこと。
口頭で説明いただき私の勘違いであることがわかりましたので、補足で案内を追加しました。

54865a7525e1bf0f28bc02dd06255761fdd8cc59

2023-12-11 09:31 UTC, charon-r13b commented on ja/migration/index.rst
>        <version>...</version>
修正確認しました。

2023-12-11 10:51 UTC, tisurgm approved these changes

2023-12-13 06:14 UTC, merged