HttpRequest#getParam、HttpRequest#getParamMapの利用箇所を修正
nablarch/nablarch-document pull request #561
Opened 2024-02-26 08:18 UTC by oguchi-shiori03

2024-02-28 07:21 UTC, kumagoro1202 requested changes

2024-02-28 07:21 UTC, kumagoro1202 commented on ja/application_framework/application_framework/web_service/rest/feature_details/resource_signature.rst
> +    public HttpResponse search(JaxRsHttpRequest req) {
口頭で伝えた通り全ドキュ目のでｊAX-RSのリソースクラスの箇所はJaxRsHttpRequestを使うように書き換えてください。

2024-02-28 07:21 UTC, kumagoro1202 commented on ja/application_framework/application_framework/web_service/rest/getting_started/search/index.rst
> +      public List<Project> find(JaxRsHttpRequest req) {
URLとのマッピングを定義の項目にあるコード例がHttpRequestのままです。

2024-02-28 07:25 UTC, kumagoro1202 commented
https://github.com/nablarch/nablarch-document/blob/8ea3f3d76249bedd8c6b4bb79d6d1a3fae96e511/ja/application_framework/application_framework/handlers/common/thread_context_handler.rst
も修正してください。

2024-02-29 01:25 UTC, oguchi-shiori03 commented on ja/application_framework/adaptors/router_adaptor.rst
> +        public Person foo(JaxRsHttpRequest request) {
ディスパッチされるメソッドが直前にあるコード例と一致してない箇所の修正をしました。

2024-02-29 01:27 UTC, oguchi-shiori03 commented on ja/application_framework/application_framework/web_service/rest/feature_details/resource_signature.rst
> +    public HttpResponse search(JaxRsHttpRequest req) {
jax-rsのリソースクラスでHttpRequestを利用している箇所をJaxRsHttpRequestを使用するように変更しました。

2024-02-29 01:28 UTC, oguchi-shiori03 commented on ja/application_framework/application_framework/web_service/rest/getting_started/search/index.rst
> +      public List<Project> find(JaxRsHttpRequest req) {
JaxRsHttpRequestに変更しました。

2024-02-29 05:36 UTC, kumagoro1202 approved these changes

2024-02-29 05:36 UTC, merged