Nab 596/add doma adaptor config
nablarch/nablarch-document pull request #622
Opened 2024-08-19 12:12 UTC by kankichi00

- https://github.com/nablarch/nablarch-doma-adaptor/pull/34 
- https://github.com/nablarch/nablarch-example-thymeleaf-web/pull/34 

上記でDomaの最新化を行いました。
Domaのバージョン2.30.0から使用するために必要な依存関係が変わったため、解説書に追記しました。

- [（Migration Guide for Doma 2.30.0）](https://github.com/domaframework/doma/wiki/Migration-Guide-for-Doma-2.30.0)
- [DomaのReadme](https://github.com/domaframework/doma#maven)

2024-08-19 13:08 UTC, tishijiri commented on ja/application_framework/adaptors/doma_adaptor.rst
> +Domaのバージョン2.30.0以上を使用する場合は、以下を参考にプロジェクトの依存関係を修正する必要がある。
Domaのバージョンは前提を前述しているので、「このバージョンを使用する場合は」みたいな前書きは必要ないです。なので、単純にこういう風に設定する、みたいな案内にしましょう。

2024-08-19 13:09 UTC, tishijiri commented on ja/application_framework/adaptors/doma_adaptor.rst
> +依存関係の修正
修正になるかは`maven-compiler-plugin`を設定済みかどうかによるので、依存関係の設定、みたいな追加か修正かは気にしなくてよい書き方の方がいいように思いました。

2024-08-19 13:10 UTC, tishijiri commented on ja/application_framework/adaptors/doma_adaptor.rst
> +    </dependency>
これは`nablarch-doma-adaptor`から推移的に依存するので不要に思います。

2024-08-19 13:14 UTC, tishijiri commented on ja/application_framework/adaptors/doma_adaptor.rst
> +                        <arg>-Adoma.resources.dir=${project.basedir}/src/main/resources</arg>
これコピペされたらまずいので、コメントアウトした状態にしておきましょうか。

2024-08-20 00:49 UTC, kankichi00 commented on ja/application_framework/adaptors/doma_adaptor.rst
> +Domaのバージョン2.30.0以上を使用する場合は、以下を参考にプロジェクトの依存関係を修正する必要がある。
修正しました。https://github.com/nablarch/nablarch-document/pull/622/commits/901fad7d308b3b6101407589467167ae552426b8

2024-08-20 00:49 UTC, kankichi00 commented on ja/application_framework/adaptors/doma_adaptor.rst
> +依存関係の修正
修正しました。https://github.com/nablarch/nablarch-document/pull/622/commits/901fad7d308b3b6101407589467167ae552426b8

2024-08-20 00:49 UTC, kankichi00 commented on ja/application_framework/adaptors/doma_adaptor.rst
> +    </dependency>
削除しました。https://github.com/nablarch/nablarch-document/pull/622/commits/901fad7d308b3b6101407589467167ae552426b8

2024-08-20 00:49 UTC, kankichi00 commented on ja/application_framework/adaptors/doma_adaptor.rst
> +                        <arg>-Adoma.resources.dir=${project.basedir}/src/main/resources</arg>
コメントアウトしました。https://github.com/nablarch/nablarch-document/pull/622/commits/901fad7d308b3b6101407589467167ae552426b8

2024-08-20 00:56 UTC, kankichi00 commented on ja/application_framework/adaptors/doma_adaptor.rst
> +                        <arg>-Adoma.resources.dir=${project.basedir}/src/main/resources</arg>
コメントアウトの仕方を変更しました。https://github.com/nablarch/nablarch-document/pull/622/commits/748ab5c6339d6b9a9a8b8673a217794e4256df4d

2024-08-20 07:04 UTC, charon-r13b commented on ja/application_framework/adaptors/doma_adaptor.rst
> +詳細は `Doma(外部サイト、英語) <https://github.com/domaframework/doma#maven>`_ を参照。
これ、ドキュメントじゃなくてGitHubを案内するの？

2024-08-21 12:35 UTC, charon-r13b commented on ja/application_framework/adaptors/doma_adaptor.rst
> +詳細は `Doma(外部サイト、英語) <https://github.com/domaframework/doma#maven>`_ を参照。
ドキュメントおよび日本語版を案内するようにしました

350c4c41a72a0cd04943ae12fc2d5cb528fd33b3

2024-08-22 08:02 UTC, tishijiri commented on ja/application_framework/adaptors/doma_adaptor.rst
> +
6u1はベータ版的な位置付けであるためあまり表に残したくないのと、以前の書き方との違いを案内しようとすると説明が難しくなるということがあるので、あくまでDomaで非推奨になったこと、ここでは非推奨のやり方ではない方で案内していること、を案内してあげるだけでいいかなと思いました。
あと、非推奨であったころの書き方も案内してあげれば伝わりやすいかなと思ったので、非推奨であることをコードコメントでも書いた上でconfig属性を指定していた頃のコードも記載してはどうかなと思いました。

これらの点を踏まえて、書いてくれているtipをベースに少し見直してみましたが、イメージ伝わりますでしょうか？（実際に書くときはリンクとかコードブロックとかはちゃんとしないとですが）

```
Daoアノテーションにはconfig属性で使用するConfigクラスを指定することができるが、Doma 2.44.0 よりconfig属性を指定することは非推奨になっている。
あくまで非推奨であるため、config属性を指定した場合には以前と同じ動作は行われるが、ここではconfig属性を指定しない方法を案内する。
なお、config属性を指定していない場合にDomaDaoRepository#get(java.lang.Class) を使用してDaoの実装クラスをルックアップすると、DomaConfig を使用してDaoの実装クラスを生成する。

// 現在はconfig属性の指定は非推奨になっている
@Dao(config = DomaConfig.class)
public interface ProjectDao {
    // 省略
}
```

2024-08-23 06:40 UTC, charon-r13b commented on ja/application_framework/adaptors/doma_adaptor.rst
> +
書いていて情報がtipsに収めるには情報が多すぎると思ったので、セクションを独立させてコード例を追加しました。

7be7280

2024-08-23 06:50 UTC, tishijiri commented on ja/application_framework/adaptors/doma_adaptor.rst
> +Nablarch 5で :java:extdoc:`DomaConfig<nablarch.integration.doma.DomaConfig>` を使用した実装例を以下に示す。
DomaConfig、DomaTransactionNotSupportedConfig、Config カスタマイズ、という３つについてそれぞれ順番に説明されていると思うのですが、読んでて区切りがよく分からくなってしまったりもしたため、文章だけでじゃなくて見出しつけて明確に分けておいた方が読みやすいように思いましたが、どうでしょうか。

2024-08-23 07:37 UTC, charon-r13b commented on ja/application_framework/adaptors/doma_adaptor.rst
> +Nablarch 5で :java:extdoc:`DomaConfig<nablarch.integration.doma.DomaConfig>` を使用した実装例を以下に示す。
見出し分けと説明を追加しました。

61e3e1f

2024-08-23 08:26 UTC, kumagoro1202 requested changes

2024-08-23 08:26 UTC, kumagoro1202 commented on ja/application_framework/adaptors/doma_adaptor.rst
> +            /* DomaDaoRepository#getの第2引数にDomaTransactionNotSupportedConfig.classを第2引数に指定 */
「第2引数に」が重複しているのでどちらか消してください。

2024-08-23 08:30 UTC, charon-r13b commented on ja/application_framework/adaptors/doma_adaptor.rst
> +            /* DomaDaoRepository#getの第2引数にDomaTransactionNotSupportedConfig.classを第2引数に指定 */
後者を削除しました。

b0aafeb

2024-08-23 08:31 UTC, kumagoro1202 approved these changes

2024-08-23 08:32 UTC, merged