Exampleをナビゲーションのトップレベルに移動
nablarch/nablarch-document pull request #623
Opened 2024-08-20 09:33 UTC by tisuchida

もともとExampleは「Nablarchアプリケーションフレームワーク」の直下にあったが、Example自体はフレームワークの一部ではない。
そのため、より適切な位置としてナビゲーションのトップレベルに移動した。

トップレベルに移動した場合、Nablarch実装例集とディレクトリ名が被るなどNablarch実装例集との違いが見た目上わかりづらくなるため、実装例集のコンテンツ名を「実践的な実装サンプル集」に合わせて変更した。

さらに、ディレクトリ名もコンテンツをよく表すような名前に変更した。

2024-08-21 02:00 UTC, charon-r13b commented on ja/examples/index.rst
> +Exampleアプリケーション
タイトルは素直に「Example」でよい気がします。

2024-08-21 02:02 UTC, charon-r13b commented on ja/examples/index.rst
> +本章では、Nablarchアプリケーションフレームワークを使用して作成したExampleアプリケーションに必要な環境構築手順と、アプリケーションの実行手順を解説する。
初見でこのページを見ると、突然

> Nablarchアプリケーションフレームワークを使用して作成したExampleアプリケーションに

という表現が登場し、Exampleアプリケーションというものがなんなのかがわからないまま話が進みます。

Nablarchの処理方式別に作成したものであることを言ってあげた方がよいのでは？

2024-08-21 02:06 UTC, charon-r13b commented on ja/examples/index.rst
> +Exampleアプリケーションの実行手順は、各ExampleアプリケーションのgithubのREADMEを参照すること。
実行手順はREADMEに書かれているけど、アプリケーションの説明などはないので、開発イメージを掴むにはGetting Startedを見るとよいといった内容を追加しては？  
※Thymleafはないから注記が要るけど

2024-08-21 02:26 UTC, charon-r13b commented on ja/practical_samples/index.rst
> +実践的な実装サンプル集
実践的な実装サンプル集という割に、各ページを見るとひたすら「これはサンプルだよ」と念押ししてくるので「実践的」が頭につくとちょっと微妙な感じがします。

- 実装サンプル集
- 機能実装サンプル集
- 目的別実装サンプル集

あたりを候補としては？

2024-08-21 06:37 UTC, tisuchida commented on ja/examples/index.rst
> +Exampleアプリケーション
見出しとして見たときに、「Exampleアプリケーション」には違和感があるという指摘でした。
「Example」に修正しました。

3b1fdc824229bbbd3e53cb089e55c1871f911042

2024-08-21 06:47 UTC, tisuchida commented on ja/examples/index.rst
> +本章では、Nablarchアプリケーションフレームワークを使用して作成したExampleアプリケーションに必要な環境構築手順と、アプリケーションの実行手順を解説する。
Exampleアプリの説明を追加しました。
※周辺の文も併せて修正しています。

05eaceff4c27a1eae034a278e818fd98e0f2fc57

2024-08-21 07:04 UTC, tisuchida commented on ja/examples/index.rst
> +Exampleアプリケーションの実行手順は、各ExampleアプリケーションのgithubのREADMEを参照すること。
Getting Startedの案内をするだけではGetting Startedへたどり着くのが難しいと思い、
記載を追加するとともに、処理方式毎にGetting Startedへのリンクを追加しました。

合わせて、「テーブルをキューとして使ったメッセージング」が「MOMによるメッセージング」の配下にあるような見出し構成になっていたので修正しました。

d7ad3dd012d59925e0df239c7c6fc80af9498c3f

2024-08-21 07:20 UTC, tisuchida commented on ja/practical_samples/index.rst
> +実践的な実装サンプル集
目的別実装サンプル集が最も当てはまるように見えたので、そちらを採用して修正しました。

3adb795837fc3a340881f3510739762e62ad78ce

2024-08-21 12:53 UTC, charon-r13b commented on ja/examples/index.rst
> +Exampleアプリケーションの実行手順は、各ExampleアプリケーションのgithubのREADMEを参照すること。
> JSPとカスタムタグを使用したサンプル（ Getting Started ）

のように並べられてしまうと、サンプル＝Getting Startedのように見えてしまうので、リポジトリへのリンクの下に「このExampleを使用したGetting Startedはこちら」（こちら がリンク）などのようにしてはどうだろうか？

2024-08-22 05:52 UTC, tisuchida commented on ja/examples/index.rst
> +Exampleアプリケーションの実行手順は、各ExampleアプリケーションのgithubのREADMEを参照すること。
Getting Startedの案内リンクを、リポジトリへのリンクの下に移動しました。
HTTPメッセージングの送信については対応するGetting Startedがないので、Thymeleafと同様の記載としました。
MOMについては、Getting Startedページの内容がなくそちらにリンクする意味もあまりないと思い、各Exampleに対応する機能説明へのリンクを追加しました。

dddc583d17a539a0c3717c5861d9172e0d18908d

2024-08-22 06:02 UTC, tisuchida commented on ja/practical_samples/index.rst
> +実践的な実装サンプル集
ディレクトリ名を「samples_by_purpose」に変更しました。

245309a97349dcfd155c111861f8aeb416724f67

2024-08-22 06:08 UTC, tisuchida commented on ja/examples/index.rst
> +Exampleアプリケーションの実行手順は、各ExampleアプリケーションのgithubのREADMEを参照すること。
リンクの文章は、指摘の通り「こちら」だけにするのがよさそうに見えたので、修正しました。
05431c6c96fa248bf310ffd7e4356a03c62dc957

2024-08-22 06:37 UTC, tisuchida commented on ja/practical_samples/index.rst
> +実践的な実装サンプル集
別途指摘を踏まえ、ディレクトリ名を「use_case_samples」に変更しました。

68c28f33fe9cad358fc3468adcb83e5be8529e34

2024-08-22 07:24 UTC, tisuchida commented on ja/practical_samples/index.rst
> +実践的な実装サンプル集
英語のニュアンスを考慮し、目的別実装サンプル集のディレクトリ名を「use_case_examples」に変更しました。
「Example」とどちらもディレクトリ名に「example」が入ってわかりづらくなるかと思い、Exampleの方もディレクトリ名を変更しました。
Exampleが「実行制御基盤別の実装サンプル」であることを踏まえ、「runtime_platform_examples」としています。

2e3534b3aca2b6e73e7d944e6cd430be4d3502cf

2024-08-23 05:18 UTC, charon-r13b commented on ja/examples/index.rst
> +Exampleアプリケーションの実行手順は、各ExampleアプリケーションのgithubのREADMEを参照すること。
MOMについては、以下のように書いた後に

>     ※MOMによるメッセージングでは、個別のGetting Startedを用意していない。
>     :ref:`mom_system_messaging` ライブラリの機能説明でExampleアプリケーションを使用しているため、そちらを参照すると良い。

そのまま↓のように続くと「どういうこと？結局Getting Startedあるの？ないの？」と受け取られそうな気がします。  
※よーく読むと意図はわかる

> このExampleで実装されている機能の説明は こちら

こんな感じで書いては？

> ※MOMによるメッセージングに対してはExampleアプリケーションのみの提供になり、Getting Startedは提供していない。  
> Exampleアプリケーションを使用した実装例の説明を :ref:`mom_system_messaging` に含めているので、こちらを参照するとよい。

また、リポジトリの後に続く文はこんな感じでどうだろう？

> このExampleアプリケーションを使用した実装例の説明は こちら

2024-08-23 05:31 UTC, charon-r13b commented on ja/practical_samples/index.rst
> +実践的な実装サンプル集
解説書本文もリポジトリも「sample」（サンプル、業務サンプル等）なので、ここだけ「example」に寄せなくてもいいと思います…。

> Exampleが「実行制御基盤別の実装サンプル」であることを踏まえ、「runtime_platform_examples」としています。

あとplatformと書くとフレームワークより広い意味に捉えられそうなので、「processing_architecture_examples」（処理方式）かなとも思うのですが、仰々しいのでサンプルの方が「samples」に戻るのなら「examples」のままでもいいかなと思います。

2024-08-23 06:46 UTC, tisuchida commented on ja/practical_samples/index.rst
> +実践的な実装サンプル集
日本語は「例」の意味で「サンプル」という言葉を使っているように見えるので、「サンプル」をそのまま「sample」に置き換えず、ニュアンスとしてもより適した「example」とした方がいいのではないかと思いました。
また、英語版は、実装例集も「Nablarch Implementation Examples」と訳されています。解説書外の「nablarch-biz-sample-all」リポジトリに合わせるよりは解説書内の表現を合わせることを優先し、「Example」にした方がいいかなと思った次第です。

`runtime_platform` は、英語版の「実行制御基盤」の訳からとっているので、そちらも合わせたほうがいいのではないかなと思っています。

2024-08-23 08:21 UTC, tisuchida commented on ja/examples/index.rst
> +Exampleアプリケーションの実行手順は、各ExampleアプリケーションのgithubのREADMEを参照すること。
指摘の文章の方がわかりやすいと思いますので、そちらを踏まえて修正しました。
1点、以下のコメントの内容を反映しています。
https://github.com/nablarch/nablarch-document/pull/621#discussion_r1728356916

432a7156140c3725825a195d9226e495bcba53c2

2024-08-23 08:38 UTC, tisuchida commented on ja/practical_samples/index.rst
> +実践的な実装サンプル集
英語版の「example」を「sample」に直すと、今度は英語のニュアンスが壊れてしまうことになるので、そのような修正はできないと思います。

当初は英語版の表現・解説書内の表現を整合させることが重要と判断して修正しましたが、上記の指摘はそちらの整合性よりもnablarch-biz-sample-allとの整合性の方が重要という判断だと思いますので、そのように修正しました。

一番きれいなのは日本語もすべて「サンプル」を「例」に、「nablarch-biz-sample-all」を「nablarch-biz-example-all」とすることと思いますが、リポジトリ名を変更することは容易にはできないと思いますので、ディレクトリ名をexampleではなくsampleとするのが一番良いと思います。

ただ、exampleとsampleが並ぶのは（ディレクトリ名とはいえ）気持ち悪いので、実装例側のディレクトリは（リポジトリとの関連を強く連想させるように）「biz-samples」、Example側のディレクトリは「examples」としました。

2024-08-23 09:48 UTC, tisuchida commented
コンフリクトを解消しました。

2024-08-23 11:19 UTC, tishijiri commented on ja/examples/index.rst
> +     ※本サンプルについては、対応するGetting Startedを用意していない
ちらほら「Getting Startedを用意していない」みたいなのが書いていて、あんまり案内としてよくない印象を与えかねないのでやめたほうがいいのではと個人的には思いました。
この追加はどういう意図があるんでしょうか？
もしExampleを読みやすくするための紹介とかであれば、単純に処理方式ごとのページ（GettingStartedじゃなくてその上のページ）を案内すれば全部のExampleに対して案内できるし、Exampleを読むときの基本知識のページでもあるのでそれでいいのではとも思ったのですが、どうでしょうか？

2024-08-23 11:31 UTC, tishijiri commented on ja/biz_samples/index.rst
> +目的別実装サンプル集
これは好みなので提案なだけですが、漢字が続いていて少し気になりました。
「の」を入れて、「目的別の実装サンプル集」の方が私は読みやすかったのですが、どうでしょうか？

2024-08-23 11:39 UTC, kumagoro1202 requested changes

2024-08-23 11:39 UTC, kumagoro1202 commented on ja/examples/index.rst
> +     ※本サンプルについては、対応するGetting Startedを用意していない
ExampleのインデックスとGetting Startedを同時に扱うからごちゃごちゃするのではと思いました。
冒頭に

> ここで紹介するExampleを使用した処理方式ごとのGetting Startedと実装例の解説を用意している。各ページへのリンクは本ページ下部にまとめる。
> ～ Exampleの紹介 ～
> Exampleを使用した解説　　←新しいセクション作る
> - Getting Started
>    - ウェブアプリケーション
>    - ウェブサービス
>       - REST
> ・
> ・
> ・
> - 実装例
>    - MOMメッセージング
>       - 応答不要
> ・
> ・
> ・

みたいな感じにするとかどうでしょう。

2024-08-23 11:41 UTC, kumagoro1202 requested changes

2024-08-23 11:41 UTC, kumagoro1202 commented on ja/examples/index.rst
> +  ウェブアプリケーション
アプリケーションの実行手順についてのセクション内にExampleの一覧出てくるの違和感あります。別セクションにしたほうがいいのでは。

2024-08-26 02:06 UTC, tisuchida commented on ja/examples/index.rst
> +Exampleアプリケーションは、Nablarchアプリケーションフレームワークの機能の使用方法を示した実装例であり、 :ref:`実行制御基盤 <runtime_platform>` 毎に作成している。
解説書内の「処理方式」と「実行制御基盤」の使われ方は、以下のような差異があります。
- 処理方式・・・ウェブ、バッチなど
- 実行制御基盤・・・「RESTfulウェブサービス」「Nablarch独自のバッチアプリケーション」など
Exampleは「実行制御基盤」ごとに作成しているものなので、「実行制御基盤」に合わせるのが良いと思います。

「実行制御基盤」のリンク先では確かに「～～編」が4つ並んでいますが、誤解を生むほどではないとは思います。

上記を踏まえ、修正しました。

a35e69ef40a0cf07ddf4b199f967ad10b1244f52

2024-08-26 02:08 UTC, tisuchida commented on ja/biz_samples/index.rst
> +目的別実装サンプル集
ここはその通りだと思いますので、修正しました。

3ac5b0ab52dad5d73c0b0bb6becf03c03dcec9d9

2024-08-26 04:49 UTC, tisuchida commented on ja/examples/index.rst
> +     ※本サンプルについては、対応するGetting Startedを用意していない
個人的には、ウェブアプリケーションならウェブアプリケーションのExampleと解説ページは1箇所にまとまっているほうが利用者からのアクセスはしやすいように見えます。

ページを全体的に見直したところ、そもそも箇条書きのネストがかなり深くなっているために乱雑に配置されているように見えました。そのため、箇条書きのネストではなく、それぞれを独立した見出しとして記載するように修正しました。
このようにすると、Exampleと解説ページが同時に扱われていても、それほどごちゃごちゃしてはいないと思うのですが、いかがでしょうか。

2f793933a76e908d6da93b3efcfa4d9a6111923b

2024-08-26 04:55 UTC, tisuchida commented on ja/examples/index.rst
> +  ウェブアプリケーション
ここは私もその通りだと思いますので、一覧は別セクションにしました。
合わせて、実行方法の構成も変更しました。

https://github.com/nablarch/nablarch-document/pull/623#discussion_r1730661456 で合わせて変更しています。

（変更前）
- 環境構築手順について
- アプリケーションの実行手順について
- Java 21 で動かす場合について

（変更後）
- Exampleの実行方法
  - 環境構築手順
  - アプリケーションの実行手順
  - Java 21 で動かす場合
- Exampleの一覧
  - ウェブアプリケーション
  - ウェブサービス
  - バッチアプリケーション
  - メッセージング

2024-08-26 04:56 UTC, tisuchida commented on ja/examples/index.rst
> +     ※本サンプルについては、対応するGetting Startedを用意していない
当初は、Getting Startedで具体的な開発の流れを追っているのでそちらを案内するのがわかりやすいかと思いましたが、以前のGetting Startedの配置変更の議論の際に「Getting Startedを読むためには、前提として処理の流れなどを理解する必要がある」という意見がありました。
そのため、今回の指摘の通り実行制御基盤ごとのページを案内するのがより良いと思います。

上記を踏まえ、修正しました。
https://github.com/nablarch/nablarch-document/pull/623#discussion_r1730661456
で合わせて修正しました。

2024-08-26 06:09 UTC, tishijiri commented on ja/examples/index.rst
> +- `JSPとカスタムタグを使用したサンプル(外部サイト) <https://github.com/nablarch/nablarch-example-web>`_
外部サイトって注記、チームが管理しているものについては無くていいようにも思えた（冗長な気がした）んですが、他のところでも同じようにしているんでしょうか？
合わせたわけじゃないのなら取ってしまった方がよいように思いまして。

2024-08-26 06:14 UTC, tishijiri commented on ja/examples/index.rst
> +:ref:`ウェブアプリケーション編の解説 <web_application>` 、 :ref:`Thymeleafアダプタの解説 <web_thymeleaf_adaptor>` も合わせて確認すること。
「確認すること」というのは確認してくださいという意味だとは思いますが、「解説を読みたい人はこちらにあります」くらいの案内になるように表現を弱めていいのではないかなと思いました。（いい文章はパッと思いつかなくて申し訳ないのですが…）

2024-08-26 06:19 UTC, tishijiri commented on ja/examples/index.rst
> +:ref:`ウェブアプリケーション編の解説 <web_application>` 、 :ref:`Thymeleafアダプタの解説 <web_thymeleaf_adaptor>` も合わせて確認すること。
これはできたらくらいに思っただけなので、いい案がなければ対応してくれなくても大丈夫です。

2024-08-26 06:23 UTC, tisuchida commented on ja/examples/index.rst
> +- `JSPとカスタムタグを使用したサンプル(外部サイト) <https://github.com/nablarch/nablarch-example-web>`_
#621 でFintanコンテンツへのリンクに「外部サイト」とつけたところから今回も付けたのですが、改めて解説書を見直すと、なくてもよさそうです（解説書全体でgrep検索）。

- `https://github.com/nablarch` のものについては、いずれもついていませんでした。
- 上記以外は、解説書全体としては必ずしも統一されてはいなさそうですが、おおむね「外部サイト」の案内はついているようです。

上記を踏まえ、修正しました。

2f44c7c4693d9ceaabcc1466d3e44fd5ccd48eed

2024-08-26 06:35 UTC, tisuchida commented
MOMによるメッセージングの箇条書きで、行間が空きすぎてしまう問題に対処しました。
42dd41d59536856b90f32bcca262e5aef02f1c72

2024-08-26 06:39 UTC, tisuchida commented on ja/examples/index.rst
> +:ref:`ウェブアプリケーション編の解説 <web_application>` 、 :ref:`Thymeleafアダプタの解説 <web_thymeleaf_adaptor>` も合わせて確認すること。
過去の議論から、解説書の読ませ方としては「最初に各実行制御基盤の解説を読んで、理解してもらってからgetting started (≒Example）を触ってもらう」が強く想定されている、と認識しています。
そのため、解説への誘導は強めにした方が良いかなと思い「すること」の表現としましたが、解説を読むかどうかはExampleに来た人にゆだねるくらいでもよいかと思い直しました。

それを踏まえて修正しました。

a1feec1038142d5b5886c94212721bf6fb5b7f78

2024-08-26 06:55 UTC, tishijiri commented on ja/examples/index.rst
> +:ref:`ウェブアプリケーション編の解説 <web_application>` 、 :ref:`Thymeleafアダプタの解説 <web_thymeleaf_adaptor>` も合わせて確認すること。
修正後の確認は不要ですが、「適宣参照」だと少し冷たい感じもしたので、「適宣参照すること」などにした方が個人的には読みやすそうには思いました。よければ一度検討してみてください。

2024-08-26 07:04 UTC, tisuchida commented on ja/examples/index.rst
> +:ref:`ウェブアプリケーション編の解説 <web_application>` 、 :ref:`Thymeleafアダプタの解説 <web_thymeleaf_adaptor>` も合わせて確認すること。
「すること」を入れたほうが突き放した感じがなくなりそうだったので、そのように修正しました。

99acbf04f982fb376ff97bdaeecda63e8dcaff04

2024-08-26 08:06 UTC, kumagoro1202 requested changes

2024-08-26 08:06 UTC, kumagoro1202 commented on ja/examples/index.rst
> +Exampleアプリケーションの実行手順は、各ExampleアプリケーションのgithubのREADMEを参照すること。
「githubのREADME」というのは正式な文章としては不適切ではと思います。「GitHubリポジトリのトップにあるREADME」とかじゃないですかね。

2024-08-26 08:06 UTC, kumagoro1202 commented on ja/examples/index.rst
> +ExampleはJava 17での実行を前提としている。
ExampleなのかExampleアプリケーションなのか統一してほしい。見出しは長くなるからExampleで文章中ではExampleアプリケーションみたいな基準があるわけでもないので気になりました。

2024-08-26 08:06 UTC, kumagoro1202 commented on ja/examples/index.rst
> +- `Thymeleafを使用したサンプル <https://github.com/nablarch/nablarch-example-thymeleaf-web>`_
ここだけ「～使用したサンプル」というのが気になりました。
- ウェブアプリケーション（JSP）
- ウェブアプリケーション（Thymeleaf）
とかではだめでしょうか。

2024-08-26 08:06 UTC, kumagoro1202 commented on ja/examples/index.rst
> +- `RESTfulウェブサービスのサンプル <https://github.com/nablarch/nablarch-example-rest>`_
サンプルなのかExampleなのか、別の所で議論があったと思います。意味合いとしてサンプルは不適切じゃないでしょうか。

2024-08-26 08:11 UTC, tisuchida commented on ja/examples/index.rst
> +Exampleアプリケーションの実行手順は、各ExampleアプリケーションのgithubのREADMEを参照すること。
確かにそちらの方が適切ですね（あまり気にしていなかったです。。。）

修正しました。

4e1dba70a03974b1640920de77e2a098ccb8ab3c

2024-08-26 08:25 UTC, tisuchida commented on ja/examples/index.rst
> +ExampleはJava 17での実行を前提としている。
すべて「Exampleアプリケーション」に統一する方針にしました。
- 意味としては「Exampleアプリケーション」の方が良いと思います。
- このページを参照している箇所も、「Example」を「Exampleアプリケーション」としても問題なく意味が通る文章となるため、統一可能と判断しました。


d7fcdd6ab830b67ec1b276c694bf3b39ede0c842

2024-08-26 08:39 UTC, tisuchida commented on ja/examples/index.rst
> +- `Thymeleafを使用したサンプル <https://github.com/nablarch/nablarch-example-thymeleaf-web>`_
ここも特に気にしていませんでした。。。

他の箇所の表現を見直したことで目立つようになってしまったため、統一したほうがいいと思います。
修正しました。

c2e5aac3a36512fa76122b1fd03102da5f18e9fb

2024-08-26 09:27 UTC, tisuchida commented on ja/examples/index.rst
> +- `RESTfulウェブサービスのサンプル <https://github.com/nablarch/nablarch-example-rest>`_
「Example」の方が適切である、というのは私も同意します。

当初は、実装例集等で「サンプル」という表現が「例」という意味で使用されていることを踏まえて「サンプル」にそろえる方向で修正していましたが、
Example（及びExampleを参照しているGetting Started）には「サンプル」という表現は他になく、このドキュメント内では「Example」としても特に混乱はないと判断しました。

以下で、「サンプル」を「Example」に修正しています。

982374d0b98778c832064e39bec3cdfe2e887e27

2024-08-26 12:31 UTC, kumagoro1202 commented on ja/examples/index.rst
> +- `RESTfulウェブサービスのサンプル <https://github.com/nablarch/nablarch-example-rest>`_
ひとつの処理方式に対して、見出し・解説・Exampleと何度も同じ文言が繰り返され冗長で読みにくく感じます。
これでいいんじゃないですか？
```
Exampleの一覧
=============

実行制御基盤ごとのExampleを以下に示す。各Exampleを題材とした実装の解説を用意している。以下一覧の「解説」リンクから参照できるため、必要に応じて参照すること。

ウェブアプリケーション
----------------------

- `ウェブアプリケーション (JSP) <https://github.com/nablarch/nablarch-example-web>`_ (:ref:`解説 <web_application>`)
- `ウェブアプリケーション (Thymeleaf) <https://github.com/nablarch/nablarch-example-thymeleaf-web>`_ (:ref:`解説 <web_thymeleaf_adaptor>`)

ウェブサービス
--------------

- `RESTfulウェブサービス <https://github.com/nablarch/nablarch-example-rest>`_ (:ref:`解説 <restful_web_service>`)
- `HTTPメッセージング (受信) <https://github.com/nablarch/nablarch-example-http-messaging>`_ (:ref:`解説 <http_messaging>`)

  - `HTTPメッセージング (送信) <https://github.com/nablarch/nablarch-example-http-messaging-send>`_

.. tip::
 HTTPメッセージング(送信)は、HTTPメッセージング(受信)にリクエストを送信するためのクライアントとして用意している。
 HTTPメッセージング(送信)の実装は単なるバッチアプリケーションであり、ウェブサービスの実装例としてはHTTPメッセージング(受信)を参照すること。

バッチアプリケーション
----------------------

- `Jakarta Batchに準拠したバッチアプリケーション <https://github.com/nablarch/nablarch-example-batch-ee>`_ (:ref:`解説 <jsr352_batch>`)
- `Nablarchバッチアプリケーション <https://github.com/nablarch/nablarch-example-batch>`_ (:ref:`解説 <nablarch_batch>`)

メッセージング
--------------

- MOMによるメッセージング

  .. _`example_application-mom_system_messaging-async_message_send`:

  - `応答不要メッセージ送信 <https://github.com/nablarch/nablarch-example-mom-delayed-send>`_ (:ref:`解説 <mom_messaging>`)

  .. _`example_application-mom_system_messaging-sync_message_send`:

  - `同期応答メッセージ送信 <https://github.com/nablarch/nablarch-example-mom-sync-send-batch>`_　(:ref:`解説 <mom_messaging>`)

  .. _`example_application-mom_system_messaging-async_message_receive`:

  - `応答不要メッセージ受信 <https://github.com/nablarch/nablarch-example-mom-delayed-receive>`_ (:ref:`解説 <mom_messaging>`)

  .. _`example_application-mom_system_messaging-sync_message_receive`:

  - `同期応答メッセージ受信 <https://github.com/nablarch/nablarch-example-mom-sync-receive>`_ (:ref:`解説 <mom_messaging>`)

- `テーブルをキューとして使ったメッセージング <https://github.com/nablarch/nablarch-example-db-queue>`_ (:ref:`解説 <db_messaging>`)
```
![image](https://github.com/user-attachments/assets/5671cd3e-d48f-4ee3-b93a-d81a6feecc56)

2024-08-27 01:33 UTC, kumagoro1202 commented on ja/examples/index.rst
> +- `RESTfulウェブサービスのサンプル <https://github.com/nablarch/nablarch-example-rest>`_
チームで会話しました。
- 解説として各処理方式のトップにリンクしていますが、Getting Startedにリンクするようにしてください。
- HTTPメッセージング(送信)はExampleとして必要なさそうに見えるので、中身を確認して不要であればリポジトリをアーカイブして一覧からも消してください。
  - HTTPメッセージング(送信)はHTTPメッセージング(受信)にリクエストを一回送るだけのバッチだが、Getting Startedにも登場せずなんの解説もない。HTTPメッセージング(受信)に簡易なクライアントを用意してあり動作確認はできるようになっているのでHTTPメッセージング(送信)は不要に見える。
- MOMによるメッセージングのリンク先は4つとも同じMOMメッセージングのGetting Startedにしてください。Getting Startedに飛んだあとすぐにライブラリの解説に飛んでもらう必要がありますが、Getting Startedにある文章を読ませたいので、そこで良いです。

2024-08-28 01:53 UTC, tisuchida commented on ja/examples/index.rst
> +- `RESTfulウェブサービスのサンプル <https://github.com/nablarch/nablarch-example-rest>`_
> HTTPメッセージング(送信)はExampleとして必要なさそうに見えるので、中身を確認して不要であればリポジトリをアーカイブして一覧からも消してください。

確認したところ、HTTPメッセージング(送信)では固有の機能（[HTTPメッセージ送信](https://nablarch.github.io/docs/6-LATEST/doc/application_framework/application_framework/libraries/system_messaging/http_system_messaging.html#http-system-messaging-message-send)）を使用していました。そのため、Exampleとしては残しておく必要があると考えます（本件会話済み）。

提案いただいた構成の方が読みやすかったため、そちらに合わせて修正しました。
解説へのリンクについて、Thymeleaf、HTTPメッセージング(送信)以外はいずれもGetting Startedへのリンクに修正しています。
Thymeleafはアダプタの解説ページ、HTTPメッセージング(送信)はHTTPメッセージ送信の機能解説箇所にリンクしています。

a080de1258081e73e82f5a57ea7aaf2b1d0044e6

2024-08-28 02:14 UTC, kumagoro1202 requested changes

2024-08-28 02:14 UTC, kumagoro1202 commented on ja/examples/index.rst
> +    .. _`example_application-mom_system_messaging-async_message_send`:
ここに空行がないのでidの付与が意図したものになっていないです。
以下のように`example-application-mom-system-messaging-async-message-send`のidがli要素ではなくul要素についてしまっています。
```html
<ul>
  <li>
    <dl class="first docutils">
      <dt>MOMによるメッセージング</dt>
      <dd></dd>
    </dl>
    <ul class="simple" id="example-application-mom-system-messaging-async-message-send">
      <li>
        <a class="reference external" href="https://github.com/nablarch/nablarch-example-mom-delayed-send">応答不要メッセージ送信</a>(
        <a class="reference internal" href="../application_framework/application_framework/messaging/mom/getting_started.html#mom-messaging-getting-started">
          <span class="std std-ref">解説</span>
        </a>)
      </li>
      <li id="example-application-mom-system-messaging-sync-message-send">
        <a class="reference external" href="https://github.com/nablarch/nablarch-example-mom-sync-send-batch">同期応答メッセージ送信</a>(
        <a class="reference internal" href="../application_framework/application_framework/messaging/mom/getting_started.html#mom-messaging-getting-started">
          <span class="std std-ref">解説</span>
        </a>)
      </li>
```

2024-08-28 02:33 UTC, kumagoro1202 commented on ja/examples/index.rst
> +    .. _`example_application-mom_system_messaging-async_message_send`:
もっと言うと一行ずつにリファレンス貼る必要性は低いと思います。（1行目と2行目が別のアンカーで飛べたとしてもブラウザ上の表示ではほとんど違いがなく利用者にとって嬉しいものではない。）また、解説のリンクを各Exampleの後ろに置くのも無駄に思えました。
メンテナンスの際の可読性下げるだけに感じるので以下でいいのではと思います。（リンクさせてる側も要修正）
```
メッセージング
--------------

.. _`example_application-mom_system_messaging`:

- MOMによるメッセージング (:ref:`解説 <mom_messaging_getting_started>`)

  - `応答不要メッセージ送信 <https://github.com/nablarch/nablarch-example-mom-delayed-send>`_
  - `同期応答メッセージ送信 <https://github.com/nablarch/nablarch-example-mom-sync-send-batch>`_
  - `応答不要メッセージ受信 <https://github.com/nablarch/nablarch-example-mom-delayed-receive>`_
  - `同期応答メッセージ受信 <https://github.com/nablarch/nablarch-example-mom-sync-receive>`_

- `テーブルをキューとして使ったメッセージング <https://github.com/nablarch/nablarch-example-db-queue>`_ (:ref:`解説 <db_messaging_getting_started>`)
```

2024-08-28 04:14 UTC, tisuchida commented on ja/examples/index.rst
> +    .. _`example_application-mom_system_messaging-async_message_send`:
2つ目のコメントで提案いただいた形式の方が見やすいと私も感じるので、そのように修正しました。
（関連リンクも修正しています）

40c32fc0135404a761cd39c7512e44ea99623470

> ここに空行がないのでidの付与が意図したものになっていないです。

すみません、気づいていませんでした。

確認したところ、空行の有無にかかわらず、箇条書きの先頭要素にラベルを設定してhtmlビルドした場合、`<li>`要素ではなく`<ul>`要素にidが付与されていました（そのようになる、という情報は見つかりませんでした）

※実際、 https://github.com/nablarch/nablarch-document/pull/623#discussion_r1733801767 の記載でビルドしてもそのようになります。

書き方を変えて試してみても同様のふるまいだったため、先頭の`<li>`にidを付与するのはできなさそうです。
ドキュメント構造の上からは不適切な要素にidが付与されているものの、利用者がリンクを開いた際の表示にはほとんど影響がないことも考慮し、`<ul>`要素にidが付与されていることは許容してもよいかと思うのですが、いかがでしょうか。

2024-08-28 04:58 UTC, kumagoro1202 commented on ja/examples/index.rst
> +    .. _`example_application-mom_system_messaging-async_message_send`:
> 確認したところ、空行の有無にかかわらず、箇条書きの先頭要素にラベルを設定してhtmlビルドした場合、<li>要素ではなく<ul>要素にidが付与されていました（そのようになる、という情報は見つかりませんでした）
> 
> ※実際、 https://github.com/nablarch/nablarch-document/pull/623#discussion_r1733801767 の記載でビルドしてもそのようになります。
> 
> 書き方を変えて試してみても同様のふるまいだったため、先頭の<li>にidを付与するのはできなさそうです。
> ドキュメント構造の上からは不適切な要素にidが付与されているものの、利用者がリンクを開いた際の表示にはほとんど影響がないことも考慮し、<ul>要素にidが付与されていることは許容してもよいかと思うのですが、いかがでしょうか。

ちょっと言っている意味がわからないのですが、最初のコメントで問題視しているのはul要素にidが付与されることではなく、1行目のラベルがul要素のidに設定され、2行目のラベルはli要素に設定されているという非対称性です。それを解消するには各行に空行を入れ
```
メッセージング
--------------

- MOMによるメッセージング

  .. _`example_application-mom_system_messaging-async_message_send`:

  - `応答不要メッセージ送信 <https://github.com/nablarch/nablarch-example-mom-delayed-send>`_ (:ref:`解説 <mom_messaging_getting_started>`)

  .. _`example_application-mom_system_messaging-sync_message_send`:

  - `同期応答メッセージ送信 <https://github.com/nablarch/nablarch-example-mom-sync-send-batch>`_ (:ref:`解説 <mom_messaging_getting_started>`)

  .. _`example_application-mom_system_messaging-async_message_receive`:

  - `応答不要メッセージ受信 <https://github.com/nablarch/nablarch-example-mom-delayed-receive>`_ (:ref:`解説 <mom_messaging_getting_started>`)

  .. _`example_application-mom_system_messaging-sync_message_receive`:

  - `同期応答メッセージ受信 <https://github.com/nablarch/nablarch-example-mom-sync-receive>`_ (:ref:`解説 <mom_messaging_getting_started>`)

- `テーブルをキューとして使ったメッセージング <https://github.com/nablarch/nablarch-example-db-queue>`_ (:ref:`解説 <db_messaging_getting_started>`)
```
とすることで、以下のようなHTMLが出力されるので、これであれば問題ないです。
```
<ul>
  <li>
    <p class="first">MOMによるメッセージング</p>
    <ul class="simple" id="example-application-mom-system-messaging-async-message-send">
      <li>
        <a class="reference external" href="https://github.com/nablarch/nablarch-example-mom-delayed-send">応答不要メッセージ送信</a>(
        <a class="reference internal" href="../application_framework/application_framework/messaging/mom/getting_started.html#mom-messaging-getting-started">
          <span class="std std-ref">解説</span>
        </a>)
      </li>
    </ul>
    <ul class="simple" id="example-application-mom-system-messaging-sync-message-send">
      <li>
        <a class="reference external" href="https://github.com/nablarch/nablarch-example-mom-sync-send-batch">同期応答メッセージ送信</a>(
        <a class="reference internal" href="../application_framework/application_framework/messaging/mom/getting_started.html#mom-messaging-getting-started">
          <span class="std std-ref">解説</span>
        </a>)
      </li>
    </ul>
```
最終的に変更してくれたものはul要素にid付与されるのが自然だと思うので問題ではないです。

2024-08-28 05:05 UTC, kumagoro1202 commented on ja/examples/index.rst
> +    .. _`example_application-mom_system_messaging-async_message_send`:
口頭で会話して「テーブルをキューとして使ったメッセージング」までを子要素として持つul要素につくことが問題だと言っていることは理解しました。
「テーブルをキューとして使ったメッセージング」にもラベルをつけることで回避は可能ですが、そこまでやる意味もないので、現状の書き方でOKとします。

2024-08-28 05:05 UTC, kumagoro1202 approved these changes

2024-08-28 05:07 UTC, merged