アダプタの後方互換性についての考え方を追記
nablarch/nablarch-document pull request #652
Opened 2024-09-26 08:41 UTC by tishijiri

2024-09-26 08:51 UTC, kumagoro1202 requested changes

2024-09-26 08:51 UTC, kumagoro1202 commented on ja/about_nablarch/versionup_policy.rst
> +なお、アダプタのAPIについては考え方が異なり、Publishedアノテーションが付与されていてもこの後方互換性ポリシーの対象外となります。
なんとなくでしかないのですが、「考え方が異なり」という部分に引っかかりました。「ただし、アダプタの場合はPublishedアノテーションが付与されていても後方互換性ポリシーの対象外となります。」とかがしっくりきます。

2024-09-26 08:51 UTC, kumagoro1202 commented on ja/about_nablarch/versionup_policy.rst
> +アダプタは外部ライブラリのAPIに依存するため、何らかの理由で外部ライブラリをバージョンアップする際にどうしても後方互換性を維持できない場合があるためです。
「何らかの理由で」はなくて良いと思いました。

2024-09-26 08:51 UTC, kumagoro1202 commented on ja/about_nablarch/versionup_policy.rst
> +後方互換性を維持できるように最大限努めますが、後方互換性が維持できない場合があることはご承知おきください。
じゃぁ何でアダプタにもPublishedつけるの？という疑問が生まれると思います。
利用者が安全に使用することを想定したAPIにだけPublishedをつけてる。だから他のPublishedついてないAPIは基本使わないでねというのを書いたほうが良いと思います。

2024-09-26 08:57 UTC, tishijiri commented on ja/about_nablarch/versionup_policy.rst
> +なお、アダプタのAPIについては考え方が異なり、Publishedアノテーションが付与されていてもこの後方互換性ポリシーの対象外となります。
フレームワークの方は「API」を明示しているので、「アダプタのAPIについては」といった表現にしたうえで修正しました。

bca8c960f0d140a19642ad116c092069cb384a46

2024-09-26 08:58 UTC, tishijiri commented on ja/about_nablarch/versionup_policy.rst
> +アダプタは外部ライブラリのAPIに依存するため、何らかの理由で外部ライブラリをバージョンアップする際にどうしても後方互換性を維持できない場合があるためです。
削除しました

2a85396ea6aaa52091d257387f38e74339007724

2024-09-26 09:28 UTC, tishijiri commented on ja/about_nablarch/versionup_policy.rst
> +後方互換性を維持できるように最大限努めますが、後方互換性が維持できない場合があることはご承知おきください。
> ページ内で「後方互換性」と「後方互換」が混じってるのもどちらかに統一しておいてほしいです。

「後方互換性」に統一しました
b2ef3ef9545c18df07546557bba3a3f72f32036f

2024-09-26 09:30 UTC, tishijiri commented on ja/about_nablarch/versionup_policy.rst
> +後方互換性を維持できるように最大限努めますが、後方互換性が維持できない場合があることはご承知おきください。
> 利用者が安全に使用することを想定したAPIにだけPublishedをつけてる。だから他のPublishedついてないAPIは基本使わないでねというのを書いたほうが良いと思います。

文章を見直しました
c42973d0452da0d2f2d4805528b92d5e57c085f2

2024-09-26 11:58 UTC, kumagoro1202 requested changes

2024-09-26 11:58 UTC, kumagoro1202 commented on ja/about_nablarch/versionup_policy.rst
> +また、Publishedアノテーションを付与していないAPIについては非公開APIと同様に使用しないでください。
改めて読むと前後の文章からこの書き方だとアダプタが暗にフレームワークの一部に含まれてることになってしまっていますね。含まれないというスタンスは明記したほうが良いかと思いました。

> なお、アダプタはここで言うフレームワークには含まれません。外部ライブラリを使用するために用意されたコンポーネントであり、Nablarchとして必須ではないため区別しています。また、アダプタは外部ライブラリのAPIに依存し、外部ライブラリの破壊的変更に伴ってバージョンアップの際にどうしても後方互換性を維持できない場合があります。
> 利用者が使用することを想定したアダプタのAPIにはPublishedアノテーションを付与しています。しかし上記の通り、アダプタのAPIは後方互換性ポリシーの対象外となります。
> Publishedアノテーションを付与していないアダプタのAPIについては非公開APIと同様に使用しないでください。

2024-09-26 13:19 UTC, tishijiri commented on ja/about_nablarch/versionup_policy.rst
> +また、Publishedアノテーションを付与していないAPIについては非公開APIと同様に使用しないでください。
指摘点は理解しましたが、提案いただいた文章で以下の点については個人的に気になったため、これらを踏まえた上で文章を見直しています。
- 「必須ではないため区別している」ということを伝える意義があまりわからなかった
  - 外部ライブラリ用のコンポであるためフレームワークには含めませんだけでいいと思えた
- Publishedアノテーションがついているものは後方互換性を維持できるように努力することは伝えないと、利用者は使う気になれないように思えた
  - 利用者から見てアノテーションがついているものとついていないものの境界が分からないため、基本的には維持できるようには気にしてくれるという境界を明確に引くべきだと思った

e218006296270ff6bedaf293aff6528a6adfd9b0

2024-09-27 02:25 UTC, kumagoro1202 requested changes

2024-09-27 02:25 UTC, kumagoro1202 commented on en/about_nablarch/versionup_policy.rst
> +Note that adapters are components provided for using external libraries, and are not included in the framework referred to here.
> external libraries, and are not

ここにカンマは要らないと思います。

2024-09-27 02:25 UTC, kumagoro1202 commented on en/about_nablarch/versionup_policy.rst
> +However, the Published annotation is added to adapter APIs that are intended for use by users.
> for use by users.

for user use. の方が簡潔だと思いました。

2024-09-27 02:25 UTC, kumagoro1202 commented on en/about_nablarch/versionup_policy.rst
> +We strive to maintain backward compatibility, but for this reason they are not covered by the backward compatibility policy.
以下のようにした方が自然だと思いました。

> While we strive to maintain backward compatibility, adapters are not covered by the backward compatibility policy for this reason.

2024-09-27 02:25 UTC, kumagoro1202 commented on en/about_nablarch/versionup_policy.rst
> +Adapter APIs that do not have the Published annotation should not be used, just as unauthorized APIs.
好みの問題ですが以下のようにするのはどうでしょう。

> Adapter APIs without the Published annotation should not be used, just like unauthorized APIs.

2024-09-27 02:30 UTC, tishijiri commented on en/about_nablarch/versionup_policy.rst
> +Note that adapters are components provided for using external libraries, and are not included in the framework referred to here.
修正しました。

a7a417398545b47bbd19d7e7dd31c3762062d9cd

2024-09-27 02:30 UTC, tishijiri commented on en/about_nablarch/versionup_policy.rst
> +However, the Published annotation is added to adapter APIs that are intended for use by users.
修正しました。

4548d89a3646a87c40bcb574d67065f6fa142e24

2024-09-27 02:30 UTC, tishijiri commented on en/about_nablarch/versionup_policy.rst
> +We strive to maintain backward compatibility, but for this reason they are not covered by the backward compatibility policy.
修正しました。

22e58c0580d10fe9c9e2311899e0e916114c20ec

2024-09-27 02:31 UTC, tishijiri commented on en/about_nablarch/versionup_policy.rst
> +Adapter APIs that do not have the Published annotation should not be used, just as unauthorized APIs.
それでよいと思いましたので、そのように修正しました。

c05388889b2d5abe858eb4ac1297c2ac7301c474

2024-09-27 02:33 UTC, kumagoro1202 approved these changes

2024-09-27 02:33 UTC, merged